### ISSUE TITLE
Using --role ROLE and start runs the job in the foreground instead of background

### ISSUE THREAD

**Issue by Ladas** [ansible/ansible-runner#100]
Using ```--role ROLE``` and ```start``` runs the job in the foreground instead of background.

Using ```--playbook PLAYBOOK``` and ```start``` runs the job in the background, as expected.

Looks like these might be different code paths?

**Comment by Ladas** [comment]
ping @matburt

**Comment by matburt** [comment]
Yeah, this has turned into a major problem that we need to fix. We're tracking the code path unification here: https://github.com/ansible/ansible-runner/issues/98
