### ISSUE TITLE
--containerized is not a recognized argument

### ISSUE THREAD

**Issue by howardjones** [ansible/ansible-runner#1008]
I am trying to use ansible-runner to test playbooks in the same Execution Environment that I use with AWX, mainly to contain the dependency nightmare of azure.azcollection.

https://ansible-runner.readthedocs.io/en/stable/intro/ talks about using the --containerized argument to use an Execution Environment. But:

```
# ansible-runner run --containerized  demo --role private-edns --hosts localhost  --debug                                                         
usage: ansible-runner [-h] [--version] [--debug] [--logfile LOGFILE] [-b BINARY] [-i IDENT] [--rotate-artifacts ROTATE_ARTIFACTS] [--artifact-dir ARTIFACT_DIR] [--project-dir PROJECT_DIR]
                      [--inventory INVENTORY] [-j] [--omit-event-data] [--only-failed-event-data] [-q] [-v]
                      {run,start,stop,is-alive,transmit,worker,process} ...
ansible-runner: error: unrecognized arguments: --containerized

   
# ansible-runner --version                                                               
2.1.2
```

It also suggests that `ansible-runner -h` will give more information about containerized ansible. The output from that command doesn't even include the word "container"!

With debug turned on, I can see that even when I specify an EE image using `--container-image`, I get:

    containerization disabled

but no indication why.

**Comment by senorsmile** [comment]
I am new to ansible-runner and running into the same issue going through the docs. 

NB: I'm using v2.3.1 and following that version of the docs: https://ansible-runner.readthedocs.io/en/2.1.3/intro/

**Comment by Shrews** [comment]
Looks to me that this option was both added and removed in https://github.com/ansible/ansible-runner/pull/470 but the added documentation did not account for the removal of the option. The [process isolation](https://ansible-runner.readthedocs.io/en/stable/intro/#process-isolation-settings-for-runner) settings are the correct way to use containers.  We just need to remove this bit from our documentation, or possibly merge the two sections into something more correct.

**Comment by Akasurde** [comment]
resolved_by_pr #1043
