### ISSUE TITLE
-q option doesn't work well

### ISSUE THREAD

**Issue by firemeteor** [ansible/ansible-runner#102]
When I use the ansible-runner(1.0.5) command with -q option, there will still be output。
The output is as follows:

TASK [config xxx] *****************************************************

TASK [create xxx] ******************************************************

TASK [remove xxx] **********************************************

TASK [unarchive xxx] ************************************************

192.168.6.246              : ok=29   changed=15   unreachable=0    failed=0

**Comment by matburt** [comment]
hmm, I am not able to reproduce this. Can you give me some other details on how you are invoking Runner... python version? etc.

**Comment by firemeteor** [comment]
Both ansible-runner command and python interface are the same result。And sometimes is ok。

My environment detail is as follows:
ansible 2.4.0.0
  config file = /root/.ansible.cfg
  configured module search path = [u'/usr/share/my_modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jun 13 2017, 12:42:46) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

**Comment by firemeteor** [comment]
@matburt 

I modified demo/project/test.yml, added the task to 200, and then executed ansible-runner to reproduce the problem.

[node1] (local) root@192.168.0.18 ~/ansible-runner
$ docker run ansible-runner:latest ansible-runner run /runner --playbook test.yml -q

TASK [debug] *******************************************************************


TASK [debug] *******************************************************************



    "msg": "Test!"
}


    "msg": "Test!"
}


    "msg": "Test!"
}


    "msg": "Test!"
}


    "msg": "Test!"
}

**Comment by privateip** [comment]
I just submitted PR #116 that should fix this bug
