### ISSUE TITLE
`ansible-runner` base image improperly overrides `$HOME`, breaking various Ansible things

### ISSUE THREAD

**Issue by nitzmahone** [ansible/ansible-runner#1024]
The `ansible-runner` base image doesn't actually change the `root` user's homedir, it just overrides the `HOME` envvar to `/home/runner` while leaving the actual homedir in `/etc/passwd` as `/root`. Anything that attempts to resolve root's homedir by asking the system what it should be (eg, Ansible, all over the place via `echo ~root`) will get the wrong answer. For places where Ansible expands the directory control-side and uses the expanded value, it's still "wrong" but not broken, but for things like, eg, `async_status` which expect the homedir to resolve properly (and in a matching way) on the target as well as remotely, things will be broken badly. 

In particular, this issue breaks `async_status` for all tasks started over the `local` connection, since the status module is looking for the job status file in `~/.ansible_async/(jid)`, but the control-side pre-creates it in `~root/.ansible_async(jid)`. If properly overridden, those two resolve to the same value, but since it's not properly overridden, the status module can't find the JID file. This effectively means any `async` task that uses the local connection (`connection: local`, `local_action`, probably networking) will be broken on any EE based on the runner default EE.

Probably just need to `usermod -d /home/runner root` early in the Dockerfile, but it might be more complicated since it's root...

**Comment by Shrews** [comment]
https://github.com/ansible/ansible-runner/commit/b72f1e933f373a1f7dcffb5a8abba6804692f0b1

**Comment by nitzmahone** [comment]
Yeah, I went chasing down that rabbithole a bit yesterday- long ago, `runner` was an actual user in the container, then it wasn't. Its homedir was originally `/home/runner`, then it changed to `/runner` for $reasons_unknown, then the user was removed and put back to root, but left overriding its homedir (the wrong way) as `/runner`, then changed back to `/home/runner` (which is the commit you linked above). There's also a hack in `entrypoint` that completely replaces `/etc/passwd`, but I'm not sure what purpose that hack actually serves (it references RHEL8) or if it's still needed or used.

**Comment by tgoetheyn** [comment]
I can confirm this breaks the playbook when trying to use `async_status`

the task which starts async creates a result file in /home/runner
```
changed: [localhost] => (item=srvcon09) => {
    "ansible_job_id": "188704455333.61",
    "ansible_loop_var": "async_item",
    "async_item": "srvcon09",
    "changed": true,
    "finished": 0,
    "results_file": "/home/runner/.ansible_async/188704455333.61",
    "started": 1
}
```

The async status job fails becaus it looks in the wrong directory
```
    "ansible_job_id": "188704455333.61",
    "attempts": 1,
    "changed": false,
    "finished": 1,
    "invocation": {
        "module_args": {
            "_async_dir": "/root/.ansible_async",
            "jid": "188704455333.61",
            "mode": "status"
        }
    },
    "msg": "could not find job",
    "results_file": "/root/.ansible_async/188704455333.61",
    "started": 1,
    "stderr": "",
    "stderr_lines": [],
    "stdout": "",
    "stdout_lines": []
}
```

**Comment by sean-m-sullivan** [comment]
Can confirm as well, we are seeing a job for localhost with async failing on lateast AAP

**Comment by cidrblock** [comment]
I suspect this is related, or at least a symptom? https://github.com/ansible/ansible-runner/pull/805
