### ISSUE TITLE
Publish Docker image for version 1.4.9

### ISSUE THREAD

**Issue by rdepke** [ansible/ansible-runner#1026]
Hi, 
from what I see the 1.4.x branch is still support see latest release https://github.com/ansible/ansible-runner/releases/tag/1.4.9 and I also understand that the upstream was moved from Dockerhub (https://hub.docker.com/r/ansible/ansible-runner/tags?page=2) to quay.io https://quay.io/repository/ansible/ansible-runner?tab=tags.

I also noticed that the base image uses the no longer support centos:8 https://github.com/ansible/ansible-runner/blob/1.4.9/Dockerfile, so maybe this needs to be changed first.

I'd like to kindly ask you to publish images for supported versions to quay.io, so it can be used from there. 

Best regards

**Comment by Shrews** [comment]
The images we publish definitely need attention as they are currently built nightly (or when PRs merge) and are not based on actual released versions of either `ansible-runner` or `ansible` (they track the HEAD of both git repositories). I don't see us adding anything for the older `1.4.x` branch until that is changed, if even then. I consider these images as "use at your own risk" and you are likely better off building your own images so you can be more specific about software versions.

**Comment by rdepke** [comment]
Thanks @Shrews for your response. We will consider than to build our own image or speed up the migration to a newer version. I leave it to you if you want to close this issue or not.
