### ISSUE TITLE
latest ansible version

### ISSUE THREAD

**Issue by cortex3** [ansible/ansible-runner#1028]
Hi,
I couldn't find anything in the docs or in the github issues about this.
Is it possible to use a more recent ansible version with this docker image?
We've ran into a bug in ansible 2.9 and would prefer to use ansible 2.12 instead.

**Comment by Shrews** [comment]
Can you clarify what "this docker image" is?

**Comment by cortex3** [comment]
Oh I'm sorry, I didn't realize that the docker image in the dockerhub is no longer maintained. quay.io uses an up-to-date version.
