### ISSUE TITLE
Delete https://hub.docker.com/r/ansible/ansible-runner

### ISSUE THREAD

**Issue by ryanmerolle** [ansible/ansible-runner#1033]
I know ansible-runner migrated from [dockerhub](https://hub.docker.com/r/ansible/ansible-runner/tags) for [quay](https://quay.io/repository/ansible/ansible-runner?tab=tags) awhile ago.  Is there any reason why no one has deleted the org and images?  I noticed some docker repo proxy solutions pull down the repo details for the first matching image name.  For many of those proxies dockerhub is usually preferred, so new images, tags, etc never show up or pulled down because dockerhub has a match on the image.

**Comment by eqrx** [comment]
@shanemcd @matburt do you have access to the org and can do something about this? Thanks :)

**Comment by matburt** [comment]
This is done!

**Comment by ryanmerolle** [comment]
Thanks @matburt
