### ISSUE TITLE
How to get details of playbook executions

### ISSUE THREAD

**Issue by aleyamayab** [ansible/ansible-runner#1036]
Good morning, how can I do to be able to capture the output of my execution of my playbook in a log file, to have integrity of my playbook

![image](https://user-images.githubusercontent.com/100615826/163001028-c4842150-6233-4a05-8b32-b72a818f104c.png)

**Comment by eqrx** [comment]
Hey! Stdout is actually captured in a file which you can grab for this use case! See the documentation here: https://ansible-runner.readthedocs.io/en/stable/intro/#runner-artifacts-directory-hierarchy :) Hope that helps!
