### ISSUE TITLE
Doc example isn't working as is.

### ISSUE THREAD

**Issue by swbsf** [ansible/ansible-runner#104]
Hi there,

Maybe I'm missing something, but here are the steps to reproduce : 

- python 3.6.5
- ansible-runner 1.0.5

- test.yml : 
```
$ cat test.yml 
---
- hosts: localhost
  tasks:
    - shell: ping -c 1 localhost
```
- code : 
```
import ansible_runner
r = ansible_runner.run(private_data_dir='/tmp/demo', playbook='test.yml')
print(r.stats)
```

- Gives TypeError : 

>Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "/home/steven/PycharmProjects/ansible-API/venv/lib/python3.6/site-packages/ansible_runner/runner.py", line 245, in stats
>    last_event = last_event[0]['event_data']
> TypeError: 'filter' object is not subscriptable

- Replacing print(r.stats) with : 
```
for each_host_event in r.events:
     print(each_host_event.event)
```
- Throws : 

> AttributeError: 'dict' object has no attribute 'event'

**Comment by matburt** [comment]
Your first issue is fixed here:

https://github.com/ansible/ansible-runner/commit/0edbdd3a488b203725476e52bfee7a70854a3a86

For your second issue,  you'll need to treat the events as a dictionary:

```
for each_host_event in r.events:
    print(each_host_event['event'])
```
