### ISSUE TITLE
devel has wrong version number

### ISSUE THREAD

**Issue by anxstj** [ansible/ansible-runner#1041]
If ansible-runner is directly installed from the git repository (like AWX is doing it), then it shows the wrong (or at least a confusing) version number.

```
$ git clone https://github.com/ansible/ansible-runner.git
$ LANG=C git status
On branch devel
Your branch is up to date with 'origin/devel'.
$ pip install .
...
$ ansible-runner --version
2.1.1.dev42
```
The latest release (and tag) is 2.1.3. So I would assume that the current version from devel has at least the same version number as the latest release.

**Comment by Shrews** [comment]
tl;dr is you can't depend on this number in the `devel` branch as the reported version is based on the latest git tag in the current branch.

When new (non-patch) releases of `ansible-runner` are created, the `devel` branch is git tagged (e.g., `2.1.0`) and a new branch is created (`release_2.1`). Subsequent patch releases of the 2.1 branch are tagged on the new `release_2.1` branch, not the `devel` branch. This is why the `devel` branch version calculation is behind the `release_2.1` branch.
