### ISSUE TITLE
Official image on Docker Hub is Down?

### ISSUE THREAD

**Issue by dyerjos** [ansible/ansible-runner#1044]
https://registry.hub.docker.com/r/ansible/ansible-runner I'm getting a 404 error when attempting to pull the latest ansible/ansible-runner image. I didn't have issues until about 3 or 4 pm CST April 19th. Is this only a problem for me or are other people having issues with the official image on docker hub?

**Comment by dyerjos** [comment]
I was able to fix my pipelines by pointing to `quay.io/ansible/ansible-runner:latest` instead of `ansible/ansible-runner:latest` . If the issue here is that the repo was intentionally shutdown on docker hub to force traffic to Red Hat's quay.io , it would be nice if this migration was mentioned in the doc's here on github or something of the sort.

**Comment by latch-lio** [comment]
We're facing the same issue. Was it intentional?

**Comment by kurokobo** [comment]
Intentionally deleted. Refer #1033

**Comment by dyerjos** [comment]
Thank you for clarifying what is going on here. My company was still using the Docker Hub image and we were not aware that it was being shut down. I'll close this ticket.
