### ISSUE TITLE
quay.io/ansible/ansible-runner:latest has no aarch64 version

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible-runner#1046]
Apparently the runner image from `quay.io/ansible/ansible-runner:latest` is not dual-arch x64/aarch64 and that is a serious issue as we would expect more and more users to user aarch64 (Apple Silicon being a major driver).

Directly impacts @ansible/devtools creator-ee project.

Blocks: https://github.com/ansible/creator-ee/issues/7

**Comment by shanemcd** [comment]
JFYI we just merged a PR for receptor that shows how to do architecture emulation with qemu and docker buildx: https://github.com/ansible/receptor/pull/652

**Comment by sivel** [comment]
We have decided to no longer maintain, support, or create container images for ansible-runner going forward.

Please see https://github.com/ansible/ansible-runner/issues/1199 for more information.
