### ISSUE TITLE
`ansible-runner` not pulling variables from `group_vars` 

### ISSUE THREAD

**Issue by HoopesC** [ansible/ansible-runner#1061]
I am unsure if I am doing something wrong or missing something. I am trying to convert my Ansible role from CLI usage to ansible-runner and I am having an issue getting the runner to pull variables from `private_data_dir/inventory/group_vars`. 

```python
def ansible(hostname, ansible_role, encpwd, tags): 
    r = ansible_runner.interface.run_async (private_data_dir='<private/data/dir/path>', role=f'{ansible_role}', hosts=f'{hostname}', cmdline=f"--ask-pass --ask-become-pass --tags '{tags}' -e 'encpwd={encpwd}'")

```

**Comment by Akasurde** [comment]
@HoopesC Thanks for reporting this issue. What is the problem that you are facing? I am able to refer `group_vars` from `private_data_dir/inventory/group_vars`.

**Comment by HoopesC** [comment]
My apologies for taking up your time @Akasurde, I had another individual look over all of my code and it was a silly mistake I missed. I was missing the group names in my `inventory/hosts` file. I have Python updating my inventory and I forgot to have it place the host under the appropriate group.
