### ISSUE TITLE
ansible-runner stable docker image not using latest version

### ISSUE THREAD

**Issue by ryanmerolle** [ansible/ansible-runner#1064]
Looking at quay, it seems the ansible-runner stable tags have a label of a `build-date` of `2022-03-08` & when you download the image, in pip the installed `ansible-runner` version is `2.1.4.dev2` instead of `2.2.0`.

Can someone correct this build to reflect the new ansible-runner version?

Thanks!

**Comment by Akasurde** [comment]
@ryanmerolle Thanks for reporting this. We are working on revamping the pypi and container release pipelines. We will keep you posted.

**Comment by ryanmerolle** [comment]
It looked like pypi was fine.  ansible-builder has both missing.

Thanks!

**Comment by ryanmerolle** [comment]
Any updates?

**Comment by pse007** [comment]
Any updates?

**Comment by fsdrw08** [comment]
Any updates?

**Comment by sivel** [comment]
We have decided to no longer maintain, support, or create container images for ansible-runner going forward.

Please see https://github.com/ansible/ansible-runner/issues/1199 for more information.
