### ISSUE TITLE
Docker Image - Ansible discovers /usr/libexec/platform-python as python binary which is python3.6

### ISSUE THREAD

**Issue by blindrood** [ansible/ansible-runner#1068]
When running EE in AWX ansible discovers python binary with path /usr/libexec/platform-python which is a symlink to python3.6 binary. While dependencies are installed via pip they're refering to /usr/bin/python which is python3.8. This causes issues during playbook execution like "no module named 'something'" because python3.6 doesn't know about pip packages installed for python3.8
This can be easily patched by adding
```
ln -sf /usr/bin/python /usr/libexec/platform-python
```
but shouldn't happen at all

**Comment by blindrood** [comment]
ansible-collections/community.postgresql#252

**Comment by sivel** [comment]
This is likely due to the fact that you have a `localhost` entry in your inventory without an `ansible_python_interpreter` specified, so it uses interpreter discovery, which correctly chooses the preferred `/usr/libexec/platform-python`

I would not recommend performing such a symlink operation.

**Comment by blindrood** [comment]
I don't have localhost entry at all in inventory and I don't see the need. Especially because this simply used to work before.
I think that, because Ansible doesn't support Python3.6 anymore, this shouldn't be part of ansible-runner image at all

**Comment by Shrews** [comment]
I agree with @sivel that this very much looks like an inventory issue (defined by user or via AWX). The limited amount of information provided makes this very difficult to diagnose.

> because this simply used to work before.

- What changed in your setup between "working" and "not working"?

- Are there any logs showing the error that you can provide?

- Can you provide a reproducer for this that doesn't involve AWX? (We don't have the ability to test that scenario.)

If a reproducer cannot be supplied showing the fault is with `ansible-runner`, I think you'll probably have to check with the AWX folks for support on this.

**Comment by MallocArray** [comment]
We have this same issue with the ansible-runner image for an Execution Environment when doing `connection: local` at the playbook level for any tasks that need to run on the localhost, such as several VMware and Netapp modules.  The issue has been discussed here:
<https://github.com/ansible/ansible/issues/16724>
<http://willthames.github.io/2018/07/01/connection-local-vs-delegate_to-localhost.html>

Currently we are working around it by having both `connection: local` at the playbook level and each task also has `delegate_to: localhost` as needed, but still comes back to the question of why does the ansible-runner container image still bundle 3.6 when it has reached end of life?
<https://peps.python.org/pep-0494/>
"As of 2021-12-23, 3.6 has reached the end-of-life phase of its release cycle. 3.6.15 was the final security release. The code base for 3.6 is now frozen and no further updates will be provided nor issues of any kind will be accepted on the bug tracker."

I know for sure we don't have an entry in our Inventory file for localhost

**Comment by sivel** [comment]
EL8, which is used for the base containers, has a default system python located at `/usr/libexec/platform-python` (which is Python 3.6), and `ansible-core` has special knowledge of this interpreter currently.  It cannot be removed, as it is part of the base operating system and required for many system utilities written in Python such as `dnf` which is a protected package.

As mentioned in a number of places, `connection: local` is almost never what you want, as it only changes the connection plugin for the current host in the loop, it doesn't change any other setting.  `delegate_to: localhost` with the implicit localhost, or creating an explicit localhost with the details described at https://docs.ansible.com/ansible-core/devel/inventory/implicit_localhost.html is what is required to get target execution to use the same python interpreter as was used to spawn the ansible CLI utilities.

**Comment by sivel** [comment]
Closing per above and due to inactivity.

**Comment by juresaht2** [comment]
For people who find this over google looking for a solution, it's:
```yaml
    localhost:
      ansible_host: localhost
      ansible_user: root
      ansible_python_interpreter: "/usr/bin/python3"
      ansible_connection: local
```

The important bit is the `ansible_python_interpreter` of course, but you might need the rest when using `delegate_to: localhost`.
