### ISSUE TITLE
fact recognize error

### ISSUE THREAD

**Issue by safeblood** [ansible/ansible-runner#1073]
``` yaml
- hosts: a windows host
  gather_facts: yes
  tasks:
    - name: debug ansible_os_family twice
      debug:
        msg: "{{ ansible_os_family }}
```

``` python
rc = ansible_runner.RunnerConfig(private_data_dir=somedir,playbook='above.yml')
rc.prepare()
r=ansible_runner.Runner(config=rc)
r.run()
```

![image](https://user-images.githubusercontent.com/10238800/167974597-697c8408-c3d7-45ba-98d8-f49fc90e1e8b.png)

**Comment by Akasurde** [comment]
@safeblood Thanks for reporting this issue. Could you please provide the output of this playbook with `ansible-playbook` command?

**Comment by safeblood** [comment]
> @safeblood Thanks for reporting this issue. Could you please provide the output of this playbook with `ansible-playbook` command?

with all verbose or just this? this is the result from ansible-playbook
![image](https://user-images.githubusercontent.com/10238800/167997358-75947f23-f17a-4788-bfb4-30aef4505d7e.png)

this is result of the ansible-runner
![image](https://user-images.githubusercontent.com/10238800/167997732-65fa99bb-55e1-4195-bed5-b9d630f6337a.png)

I try ansible-runner cli and it works fine.
![image](https://user-images.githubusercontent.com/10238800/167999026-25d45d04-289f-4c01-b1bc-ba4700ba0ceb.png)

The problem appeared just in python module

**Comment by safeblood** [comment]
I finally find the problem the flask_restful. Case close.
