### ISSUE TITLE
Is there a way to run a role using ansible-runner as sudo

### ISSUE THREAD

**Issue by morningspace** [ansible/ansible-runner#1082]
I'd like to run an ansible role using ansible-runner as sudo. According to this post, https://stackoverflow.com/questions/31663592/applying-a-role-under-sudo-user, it looks I have to write an additional playbook to do so. I wonder if this could be supported at ansible-runner level by some configuration or command line args, so that no need to write a playbook for this.

**Comment by Shrews** [comment]
The only way I can think of doing this is to run the role directly. `ansible-runner` has no ability to add extra functionality to the underlying Ansible program.

You can have `ansible-runner` run a role directly (https://ansible-runner.readthedocs.io/en/stable/standalone/#running-roles-directly), and you can use the `--cmdline` option to pass additional arguments to `ansible-playbook` to use `become` to switch user. Example:

```
   ansible-runner run my_data_dir --role some_role --cmdline="-b -K"
```

In the example above, `ansible-playbook` would ask for the BECOME password, so you'll need to use the `env/passwords` file to set the password, as described [here](https://ansible-runner.readthedocs.io/en/stable/intro/#env-passwords).

**Comment by Akasurde** [comment]
@morningspace Could you please confirm if the solution provided by @Shrews works for you? Thanks.

**Comment by morningspace** [comment]
Hi @Akasurde yes, it does work for me. Thanks @Shrews , closing it.

**Comment by Akasurde** [comment]
@morningspace Thanks for the feedback. @Shrews Thanks for the suggestion.
