### ISSUE TITLE
Documentation bug: Need to update min supported Python for 2.x.y versions

### ISSUE THREAD

**Issue by toni-moreno** [ansible/ansible-runner#1083]
Hello guys. I'm trying to create an execution evironment for awx over and old ubuntu with python 2.7.17 

the documentation site confirms python 2.7+  support  (https://ansible-runner.readthedocs.io/en/2.0.0/install.html) but an error happened when executed the following command

`ansible-runner worker --private-data-dir=/runneransible-runner worker --private-data-dir=/runner`

with this script.

```python
#!/usr/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from ansible_runner.__main__ import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

And the following error raises

```
$ ansible-runner worker --private-data-dir=/runneransible-runner worker --private-data-dir=/runner
Traceback (most recent call last):
  File "/usr/local/bin/ansible-runner", line 5, in <module>
    from ansible_runner.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/ansible_runner/__init__.py", line 3, in <module>
    from .interface import run, run_async, \
  File "/usr/local/lib/python2.7/dist-packages/ansible_runner/interface.py", line 88
    print(f'Unable to find process isolation executable: {pi_executable}')
                                                                        ^
SyntaxError: invalid syntax
```

Could you please how can I bypass/fix this error  for python 2.7 ?

thank you very much in advance!

**Comment by Shrews** [comment]
Looks like that line using the f-string was introduced in PR #470. I see several uses of f-strings (not compatible with Python 2.x) in the `release_2.0` branch, so I suspect that the documentation is outdated. Runner version `1.4.x` was the original version that supported the older Python, and we do not test any `2.x.y` versions with any python less than `3.8`. Given the above, I consider this a documentation bug, and you'll need at least python `3.8` for your runner version.

**Comment by Shrews** [comment]
Seems this doc was updated in PR #855 but RTD is not updated for some reason.

**Comment by Shrews** [comment]
Rebuilt the `2.0.3` docs that show the updated docs (https://ansible-runner.readthedocs.io/en/2.0.3/install/). No way to go back and correct the older versions, unfortunately.

Thanks for reporting this issue. Closing this per above.

**Comment by toni-moreno** [comment]
Thank you very much @Shrews 

but I'm still with problems I need to run this container as AWX execution environment with and old ansible version (2.3.3.0) this is becaouse I'm working with python 2.7. but I guess I need run ansible-runner  as "worker" to run as execution environment and it won't be posible with 1.4.X release. Is'nt it?
