### ISSUE TITLE
Add the possibility to run user scripts in entrypoint

### ISSUE THREAD

**Issue by arnaudmm** [ansible/ansible-runner#1096]
Hello,

This is a common pattern to give users the opportunity to run their own scripts without overriding the original entrypoint.

You can see an example with mysql docker image here:

In Dockerfile you create an empty directory : [see here](https://github.com/docker-library/mysql/blob/275e9822858884a85434448cb6777683692365e6/8.0/Dockerfile.debian#L37)

In entrypoint script, you execute whatever you find:

[Call to function](https://github.com/docker-library/mysql/blob/275e9822858884a85434448cb6777683692365e6/8.0/docker-entrypoint.sh#L385)
[Function definition](https://github.com/docker-library/mysql/blob/275e9822858884a85434448cb6777683692365e6/8.0/docker-entrypoint.sh#L56)

Then, when building your own image, you just have to drop your scripts in the correct directory. We could start with something basic (only bash scripts)

I am available to open a PR if this is ok for you guys. It would be awesome because today we are overriding the entrypoint and it's a pain to maintain.

Thanks!

**Comment by eqrx** [comment]
Hey, thank you for the issue. Did you mean to create this issue for ansible-builder? Runner only runs images as they are.

**Comment by arnaudmm** [comment]
Hey! Thanks for your answer and your time.

We are using `quay.io/ansible/awx-ee:latest` image which source code is here if i'm right : https://github.com/ansible/awx-ee

So I would like to edit entrypoint file located in this image (/usr/bin/entrypoint)

But I am a little bit lost to determine where this file comes from 🤔 My first guess was from this repository..

**Comment by Akasurde** [comment]
@arnaudmm Please refer to https://github.com/raukadah/tripleo-ansible-ee/blob/347131a3f0387c4806db6d50722c522d70265317/execution-environment.yml#L14 to override the entrypoint. 

I closing this issue as this is more related to Ansible Builder than Ansible Runner. Thanks.
If the problem persists please open a new issue in the Ansible Builder repo.
