### ISSUE TITLE
env/envvars cannot be used if its encrypted by ansible-vault?

### ISSUE THREAD

**Issue by deadline527** [ansible/ansible-runner#1099]
I noticed the env/extravars is processed fine when encrypted using ansible-vault, but the envvars file it seems is not being read correctly if its encrypted. Im not sure if this is expected behavior or not. Would like to understand if its even possible to encrypt the envvars file with ansible vault to protect the contents of the data inside. 

My guess is that the envvars are loaded way before any of the ansible functionality is called, hence its unable to decrypt correctly.

**Comment by Akasurde** [comment]
@deadline527 Thanks for the issue. Decrypting `env/envvars` is not supported and we don't have plans to support it anytime soon. I will go ahead and close this issue for now. Thanks.
