### ISSUE TITLE
How can I use custom module in a playbook

### ISSUE THREAD

**Issue by XiYanXian** [ansible/ansible-runner#1100]
hwo can i assign a module_path to use my custom module?

**Comment by eqrx** [comment]
Hey, see for https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-module-path, you basically have to set an environment variable here. If you have more specific questions about that I would suggest you turn to the ansible core team (https://github.com/ansible/ansible). Good luck.

**Comment by Akasurde** [comment]
Use `envvars` as - 

```
# cat main.yml
---
- hosts: localhost
  tasks:
    - my_fullname:
        last: Bond
# cat main.py
import ansible_runner

result = ansible_runner.run(
    private_data_dir=".",
    playbook="/<PATH_TO_PLAYBOOK>/env_vars/main.yml",
)
# cat env/envvars
---
ANSIBLE_LIBRARY: /tmp/a
# cat /tmp/a/my_fullname.py
#!/usr/bin/env python

from ansible.module_utils.basic import AnsibleModule
...
```
