### ISSUE TITLE
`finished_callback` how to get runner_ident

### ISSUE THREAD

**Issue by buxiaomo** [ansible/ansible-runner#1107]
I want save stdout to mongo on callback finished func , how can I get `runner_ident ` on finished callback

**Comment by Shrews** [comment]
You should be able to get to the `runner_ident` value somewhat indirectly through the passed in Runner object's config data. Something like:

```
def mycallback(runner):
    print(f"runner_ident is {runner.config.ident}")

out, err, rc = ansible_runner.run_command(executable_cmd='whoami', finished_callback=mycallback)
```
