### ISSUE TITLE
Custom execution environments fail with "ansible-runner" project updates

### ISSUE THREAD

**Issue by 24-komal** [ansible/ansible-runner#1109]
Because of the recent changes of the "ansible-runner" project the current images of the Ansible Automation Platform are failing with the error message --> 

"ERROR! Invalid callback for stdout specified: awx_display"
 
According to the AWX project --> https://github.com/ansible/awx/issues/12023

It is due to a recent movement of a python file. When building a default execution image with any image tag from "[quay.io/ansible/ansible-runner](https://quay.io/ansible/ansible-runner)", this error is occurring. The latest build on [quay.io](https://quay.io/) is 3 months old. When building the current devel branch container image directly and using the local images, those EE`s are functioning as expected.
Will the "upstream" images be updated in the near future / more frequent to eliminate errors?

It is rather painful for us to track every subproject that is used in the execution environment build process and we need the custom images to add required dependencies to the container images.

It is working with building the image from the Dockerfile of the "ansible-runner" project locally and then use that local container image for building the execution environment.

The comment is aiming more around the dependent images to build EE`s. They are provided on quay.io, but not built regularly:
https://quay.io/repository/ansible/ansible-runner?tab=tags&tag=latest
> last build: 3 months ago > none of the tags is working
Official docs -
https://docs.ansible.com/automation-controller/latest/html/userguide/ee_reference.html#ref-ee-definition

Pointing to that faulty image, which leads to research on how to fix the ansible-builder error.

**Comment by sivel** [comment]
We have decided to no longer maintain, support, or create container images for ansible-runner going forward.

Please see https://github.com/ansible/ansible-runner/issues/1199 for more information.
