### ISSUE TITLE
PEP396 - Add __version__ to main module.

### ISSUE THREAD

**Issue by mitchmahan** [ansible/ansible-runner#1110]
When trying to get the module version for ansible_runner the following code does not work:

```
import ansible_runner
print(ansible_runner.__version__)
```

https://peps.python.org/pep-0396/#specification

_3. When a module (or package) includes a version number, the version SHOULD be available in the __version__ attribute._

Currently, I believe the VERSION string is only available via the following:
```
from ansible_runner.__main__ import VERSION
```

**Comment by webknjaz** [comment]
![Screenshot_2022-08-09-12-23-42-55_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/578543/183625808-b5a6fef5-8a84-468d-b27d-8c1ecfbc6d51.jpg)

**Comment by webknjaz** [comment]
FWIW Python packaging-wise it's recommended to use `importlib.metadata` for extracting an installed package's version.

**Comment by webknjaz** [comment]
This is not to say that exposing a version via `__version__` is ultimately bad. But I've seen the setuptools maintainer actively discouraging it lately for the sake of decreased maintenance burden in the project's that tend to expose it.

**Comment by eqrx** [comment]
We are looking into adding a version flag to provide the version output via cli. Thank you for the issue :)

**Comment by Akasurde** [comment]
@mitchmahan We are using `pbr` and its [versioning](https://docs.openstack.org/pbr/latest/user/features.html#version) system. So for now I think we need to go ahead with 

```
VERSION = pkg_resources.require("ansible_runner")[0].version
```

Also, we have `--version` to get the version on the command-line. 

We can revisit this topic when we remove `pbr` dependency in the future. I will go ahead and close this for now. Thanks.
