### ISSUE TITLE
rsync version problem? (ansible.posix.synchronize fails with unknown  option)

### ISSUE THREAD

**Issue by jenwirth** [ansible/ansible-runner#1113]
I posted a question today on SE: https://serverfault.com/questions/1107760/ansible-posix-synchronize-fails-with-unknown-rsync-option

I build a custom executor (using ansible-builder). It only adds roles and collections. 

When running a Job in AWX, I get the following error on a task using `ansible.posix.synchronize`:

```
rsync: on remote machine: --sparse-block=1024: unknown option
rsync error: syntax or usage error (code 1) at main.c(1749) [server=3.2.3]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.3]

```

Versions:

- AWX: quay.io/ansible/awx:21.3
- remote target host: Ubuntu 22.04
- rsynch on remote host: version 3.2.3  protocol version 31 (i did also try with Ubuntu 20.04, that was running 3.1.3)
- custom executor (build with ansible-builder)
- rsync in executor: 3.1.3  protocol version 31

It works when i run the playbook from my local machine. Could this be a problem with the rsync version?

**Comment by jenwirth** [comment]
Someone commented on my Stack Exchange post with the following link https://bugzilla.redhat.com/show_bug.cgi?id=2043753

Adding `--sparse-block=0` to `rsync_opts` makes the playbook pass:


```yaml
- name: Yada Yada Yada
  ansible.posix.synchronize:
    src: ../foo/bar/
    dest: /home/tada/tokio
    rsync_opts: "--sparse-block=0"
```

**Comment by sigma2017** [comment]
I am using rsync to sync mysqldump from centos8 stream to centos7 and since 4 days ago I had the same errors. This is due to a recent rsync update rsync-3.1.3-16.el8.x86_64
--sparse-block=0 solved the issue, thanks!

**Comment by Akasurde** [comment]
Closing this as per above.
