### ISSUE TITLE
Fix unclosed file warnings

### ISSUE THREAD

**Issue by Shrews** [ansible/ansible-runner#1124]
Using the `-Werror` flag to `pytest` in our unit tests reveals that there are places in the code where we do not properly close open file handles (.e.g., `ResourceWarning: unclosed file ...`). We should investigate and fix those.

See PR #1123 as an example fix.

**Comment by Akasurde** [comment]
PR #1123 merged. Closing this issue.

**Comment by Shrews** [comment]
Reopening this. Referenced PR #1123 only fixes one code path producing this warning. Turning on `-Werror` for all unit tests will reveal similar warnings that we need to investigate.

**Comment by Akasurde** [comment]
@Shrews my bad.

**Comment by Akasurde** [comment]
resolved_by_pr #1228
