### ISSUE TITLE
How to get the response of run_command method as a dict ?

### ISSUE THREAD

**Issue by joaopfg** [ansible/ansible-runner#1130]
When running commands like:

`out, err, rc = ansible_runner.run_command(executable_cmd="ansible-playbook", ...)`

The response comes as a string in `out` instead of a dictionnary and the string is very far from a json. So, it can't be loaded directly into a dict without a heavy parsing work.

Is the parsing supposed to be done by the package user ? If so, why this choice ?

**Comment by sivel** [comment]
You want to use the events functionality:

* https://ansible-runner.readthedocs.io/en/stable/python_interface/#runner-events
* https://ansible-runner.readthedocs.io/en/stable/intro/#artifactevents

**Comment by Akasurde** [comment]
Closing this as per @sivel comment.
