### ISSUE TITLE
How to set tags in the run method ?

### ISSUE THREAD

**Issue by joaopfg** [ansible/ansible-runner#1131]
When running commands like:

`output = ansible_runner.run(private_data_dir=package_dir, playbook='docker_compose.yml', extravars={'hosts': hosts, 'dirs': dirs})`

it seems there is no parameter to filter playbook tasks by tags. This is an important feature for my use case, otherwise I will have to create tons of playbooks to do related tasks.

**Comment by sivel** [comment]
`tags` are handled by `RunnerConfig`.  In the end, you can directly instantiate `RunenrConfig` or just pass `tags` through the `run` function, which are passed on to `RunenrConfig` for you.

https://ansible-runner.readthedocs.io/en/stable/ansible_runner.config/

**Comment by joaopfg** [comment]
@sivel  Thanks! While looking at the docstring of the `run` method in the source code I couldn't find the `tags` parameter. Good to know it's possible to pass it directly to the run method.

**Comment by Akasurde** [comment]
resolved_by_pr #1134
