### ISSUE TITLE
How to use a module in the run method ?

### ISSUE THREAD

**Issue by joaopfg** [ansible/ansible-runner#1132]
When running commands like:

`output = ansible_runner.run(private_data_dir=package_dir, module='ansible.builtin.script', module_args=..., extravars={'hosts': hosts, 'dirs': dirs})`

what am I supposed to use in `module_args` parameter ? I can't find any examples in the docs and by looking at the source code it seems this parameter is never used ? Does it mean it's still not supported by this package ?

**Comment by sivel** [comment]
There is an example at https://github.com/ansible/ansible-runner/blob/devel/docs/python_interface.rst#usage-examples

Effectively it is equivalent to `-a` for the `ansible` adhoc CLI.

**Comment by joaopfg** [comment]
@sivel Thanks for reply ! I had saw that one. But how to proceed in cases where the `module_args` needs a variable provided by `extra_args` ? 

For example, one of my use cases is to call the `ansible.builtin.script` module to run a bash script that receives an argument. Is it possible somehow without writing a playbook ?

**Comment by sivel** [comment]
The same way it works on the adhoc CLI:

```
ansible localhost -m script -a "script.sh {{ foo }}" -e foo=bar
```

`module_args` is directly fed into `ansible` via `-a`

So `module_args="script.sh {{ foo }}"`

**Comment by Akasurde** [comment]
Closing as per above.
