### ISSUE TITLE
How to supress the artifacts, inventory and project directories automatically generated by run method ?

### ISSUE THREAD

**Issue by joaopfg** [ansible/ansible-runner#1135]
Whenever I call the `run` method, these directories `artifacts`, `inventory` and `project` are generated. I saw there is a flag `suppress_env_files`, which I'm already using to suppress the `env` directory. However, I can't find a flag to suppress these other directories. In my use case, I build the inventory and playbooks at runtime (as python objects) for security reasons. So, I have no need for these directories.

**Comment by eqrx** [comment]
Those directories are required for running runner. We would suggest manually removing them if needed. The `suppress_env_files` is there to omit potentially sensitive info.

**Comment by joaopfg** [comment]
@eqrx Yes, for now I implemented a logic that removes these directories right after an Ansible command is executed via `ansible-runner` as a work around. But there is still the possibility that an attacker gets these directories while a command is being executed.

Would it be feasible that the `ansible-runner` architecture is modified to let the possibility of not depending on these directories ?

**Comment by zhangguanzhang** [comment]
ref doc https://ansible.readthedocs.io/projects/runner/en/latest/python_interface/#usage-examples
```python
import ansible_runner

def my_artifacts_handler(artifacts_dir):
    # Do something here
    print(artifacts_dir)

# Do something with artifact directory after the run is complete
r = ansible_runner.run(private_data_dir='/tmp/demo', playbook='test.yml', artifacts_handler=my_artifacts_handler)
```

handler code https://github.com/ansible/ansible-runner/blob/e818a42d4fb5790f392a3218f816929bf8e23de6/src/ansible_runner/runner.py#L391-L395

the final code:
```python
import ansible_runner
import shutil

def my_artifacts_handler(artifacts_dir):
    shutil.rmtree(artifacts_dir.split("artifacts/")[0], ignore_errors=True)

r = ansible_runner.run(private_data_dir='/tmp/demo', playbook='test.yml', artifacts_handler=my_artifacts_handler)
```
