### ISSUE TITLE
passing inventory.ini in ansible_runner.run()

### ISSUE THREAD

**Issue by renithas** [ansible/ansible-runner#1144]
I am new to ansible_runner. Understanding the basic usage of ansible runner from https://ansible-runner.readthedocs.io/en/stable/python_interface/
In my project I have a python script which is used to execute ansible playbook.
```
 r = ansible_runner.run(
               private_data_dir='/home/ubuntu/ansible/deployment',
               playbook=playbook_file,
              inventory='inventory.ini', 
             extravars=extra_vars, 
            skip_tags="vm")
```

In this, 
inventory.ini has the content:
```
[deployment_host]
192.168.101.222 ansible_user=ubuntu
```

after calling run() method, I am getting error:

```
PLAY [Setting up resources] ****************************************************

TASK [Gathering Facts] *********************************************************
fatal: [192.168.101.222]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ubuntu@192.168.101.222: Permission denied (publickey,password).", "unreachable": true}

PLAY RECAP *********************************************************************
192.168.101.222            : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0

```

I have 2 qns:
1. How can I give inventory file to get rid of this error message? 
2. what is the best method to give extravars? I tried to pass  a dictionary object in the script. when the script is executed, It is writing to env/extravars . Hope it is the correct method. 
3. Also how to give --skip_tags in run() method?

**Comment by Akasurde** [comment]
> How can I give inventory file to get rid of this error message?

You can specify the inventory file as - 

```
import ansible_runner
import os

extra_vars = {
    "a": 1
}
r = ansible_runner.run(
    private_data_dir="./project",
    playbook='main.yml',
    inventory='%s/inventory.ini' % os.getcwd(),
    extravars=extra_vars,
)
```

```
$ tree .
.
|-- inventory.ini
|-- main.py
`-- project
    |-- env
    |   |-- cmdline
    |   `-- extravars
    |-- inventory
    |   `-- hosts
    `-- main.yml

3 directories, 6 files
```
> what is the best method to give extravars? I tried to pass a dictionary object in the script. when the script is executed, It is writing to env/extravars . Hope it is the correct method.

See the above example.

> Also how to give --skip_tags in run() method?

You need to provide command line parameters in `project\env\cmdline` like - refer to the above directory structure for the same.

```
$ cat project/env/cmdline
--skip-tags="vm"
```
