### ISSUE TITLE
Error in loading key, ssh_key_data

### ISSUE THREAD

**Issue by renithas** [ansible/ansible-runner#1147]
I am trying to use ansible_runner.run() in python script to execute playbook.
Tried this code:
```
 kwargs = {
         'playbook': playbook_file,
        'inventory': my_inventory,
        'extravars': extra_vars,
        'skip_tags': "vm",
        'ssh_key': "/home/ubuntu/.ssh/id_rsa"
    }
```
calling run method:
 `result = ansible_runner.run(**kwargs)`

But I am getting an error :
`Error loading key "/tmp/tmp7lqqjohk/artifacts/dbe41cad-89e3-4bad-b572-72124f9b50c8/ssh_key_data": invalid format
`
Can anyone point out what I am doing wrong ?

**Comment by Shrews** [comment]
This error is not from `runner` itself. It indicates an issue with the SSH key you have provided. I suggest trying to use the key you are providing outside the context of `runner` to attempt to identify the issue.
