### ISSUE TITLE
Publish CentOS stream 9 ansible-runner container image

### ISSUE THREAD

**Issue by raukadah** [ansible/ansible-runner#1152]
The OpenStack TripleO team is working on producing [tripleo-ansible-ee](https://quay.io/repository/tripleomastercentos9/openstack-tripleo-ansible-ee) container image to drive the standalone compute deployment
from Zed and master release on wards.

[tripleo-ansible-ee](https://opendev.org/openstack/tripleo-common/src/branch/master/container-images/tcib/tripleo-ansible-ee/tripleo-ansible-ee.yaml) container image contains cs9 based tripleo-ansible rpm (containing tripleo specific roles, collections, plugins and playbooks) and openstack specific files.

We need to tripleo-ansible-ee image from quay.io/ansible/ansible-runner:latest as a base container.

The current [ansible-runner EE image](https://quay.io/repository/ansible/ansible-runner/manifest/sha256:001a4bde411be863d54c1d293f3d2e7b0ff0e67ef5d7b2f9f7fb56b61694f4e8) is based on CentOS Stream 8.
But OpenStack Zed and master release works on CentOS Stream 9. 

In order to fast track our work, we have built the [CentOS Stream 9 ansible-runner image ](https://quay.io/organization/tripleoansible)
and pushed it on quay.io.

[cs9-ansible-runner-ee](https://github.com/raukadah/cs9-ansible-runner-ee) contains all the required patches to build the ansible-runner image on cs9.

We do not want to diverge from upstream and drop our image when CentOS stream 9 ansible-runner container image will be available.

Do let us know anything we can help to produce the same.

**Comment by ryanmerolle** [comment]
For anyone that needs it, I updated the runner and builder images to stream9 and got everything working.

An example of how to use them can be found [here](https://github.com/ryanmerolle/awx-network-ee)

**Comment by Akasurde** [comment]
cc @nitzmahone

**Comment by omenos** [comment]
I am also wondering if it'll be possible to publish a new image stack based on EL9. I took a shot at making some of my own based on CentOS Stream 9 after realizing I'd have to modify the assembly scripts if using a different EL distribution before knowing about this ticket.

Additionally, a newer version of Ansible would be nice as it seems like the latest runner images are still using 2.12, whereas 2.13 and 2.14 are the currently available version in RHEL and CentOS Stream 8/9. Unless I misunderstood how these images are being built and the `ansible-core` comes from PyPI.

**Comment by sivel** [comment]
We have decided to no longer maintain, support, or create container images for ansible-runner going forward.

Please see https://github.com/ansible/ansible-runner/issues/1199 for more information.
