### ISSUE TITLE
envvars not being treated correctly if they are not characters

### ISSUE THREAD

**Issue by jkugler** [ansible/ansible-runner#1159]
This is half bug report, half support request. I don't know if I hit a bug in ansible-runner (or ansible) or if I hit a nice corner case in the way Python handles environmental variables.

Today I spent the afternoon fighting with Ansible and ansible-runner. I tried to implement ANSIBLE_SSH_RETRIES in some of our code. Well, a test started timing out, even though I had set ANSIBLE_SSH_RETRIES to 0 for testing.  My kwargs passed to `.run()` looked like this:
```
{'ident': 'tmp-r3mqw3c6', 'private_data_dir': '/tmp/tmp-r3mqw3c6',
'event_handler': <function run_ansible_playbook.<locals>.<lambda> at 0x7f3084060378>,
'process_isolation': True, 'envvars': {'ANSIBLE_SSH_RETRIES': 0},
'process_isolation_executable': 'podman', 'cli_execenv_cmd': 'playbook',
'cmdline': ['/tmp/tmp-r3mqw3c6/playbook.yml', '-i', '/tmp/tmp-r3mqw3c6/inventory', '-e', 'my_name=human'],
'quiet': True}
```
Notice that the value for `ANSIBLE_SSH_RETRIES` is zero (the integer).  I'm not sure what this was converted to in the background, but it was apparent that Ansible was retrying, even though it shouldn't, because the test was timing out. When I changed the value to `'0'`:
```
'envvars': {'ANSIBLE_SSH_RETRIES': '0'}
```
The test no longer timed out, so it was obvious Ansible was not retrying.

What weird corner case did I uncover?

If it matters, I was using Ansible Runner 2.0.0-alpha4. Back story: inherited a project, got some dependencies that need to be updated; I'm in the process of doing so.

**Comment by Shrews** [comment]
I don't it should matter if the value is an `int` or a `str` for that env variable. There really isn't enough information here to guide you on what could be going on with your test, but I'd suggest the following things:

- Enable more logging from `ansible-runner` by adding the following arguments to `run()`: `verbosity=2, debug=True, ignore_logging=False`
- Enable more logging from `ansible-playbook` by adding the following arguments to `run()`: `cmdline='-vvv'`

You seem to be assuming it is SSH that's timing out, but check the logs to verify. Keep in mind that `ANSIBLE_SSH_RETRIES` does not affect local connections.

If you find something in your logs that you can pin down to a bug with `ansible-runner`, please report back and we'll be happy to take a look further.

**Comment by Akasurde** [comment]
@jkugler I mark this as done as per the above solution. Please feel free to re-open the issue if the problem persists. Thanks,
