### ISSUE TITLE
unlimited generating new ssh session

### ISSUE THREAD

**Issue by heizie** [ansible/ansible-runner#1167]
basically, the script is using `ansible_runner.run()` inside a loop with `time.sleep(120).` after a while, you'll find out a lots of ssh sessions are generated ` ps -ef| grep ssh| wc -l`
I've tried to delete the object, which contains the `ansible_runner.run()`, but was not helpful.
I can only stop the ssh session when i kill the python script

**Comment by Akasurde** [comment]
@heizie Thanks for reporting this issue. Could you please provide additional details and logs so that we can try to reproduce this issue on our end? Thanks,

**Comment by Shrews** [comment]
No further info provided, so closing this issue.
