### ISSUE TITLE
ansible_runner.run gets hung

### ISSUE THREAD

**Issue by NikhileshNanduri** [ansible/ansible-runner#1177]
I have converted the python code to make ansible_runner.run call into an API using FASTAPI and have hosted the API on PCF.

```
        runner_results= ansible_runner.run(inventory = dynamic_inventory ,
                                            playbook =  <playbookname> ,
                                            extravars= <extravars dictionary>,
                                            forks=forks_count,
                                            rotate_artifacts = 1,
                                            artifact_dir='/tmp/PN' + str(os.getpid())
                                          )
```

The above is run call I am making.

I am facing 2 issues - 
1. The ansible playbook gets hung at times and simply exits in the middle of a task execution.
2. The SSH Connections to the target servers are retained even after the playbook finishes execution and I have to manually kill the connections.

Please note: The playbook doesn't have an issue as I have run it from a Linux machine directly without ansible-runner and it executes perfectly fine. Every now and then the playbook gets hung midst of a task and eventually my API Call returns a 502 bad gateway error.

**Comment by Akasurde** [comment]
@NikhileshNanduri Thanks for reporting this issue. Could you please try to reproduce this issue without FastAPI and with a normal Python Script and let us know?

**Comment by Akasurde** [comment]
@NikhileshNanduri Any updates?

**Comment by Akasurde** [comment]
@NikhileshNanduri Any news?

**Comment by NikhileshNanduri** [comment]
I'm unable to reproduce the issue without FAST API at the moment. I'll reopen the issue once I have any updates on this item
