### ISSUE TITLE
ERROR! playbook entries must be either valid plays or 'import_playbook' statements

### ISSUE THREAD

**Issue by jefflaifu** [ansible/ansible-runner#1188]
runner == 2.3.1
ansible core == 2.12.4

I passed two ansible playbook path to runner,
/home/jeff/ansible-test/playbook/test-playbook.yml /home/jeff/ansible-test/playbook/test-playbook1.yml,
return error message "ERROR! playbook entries must be either valid plays or 'import_playbook' statements".
in private data dir, I found project/main.json, it shows
```json
["/home/jeff/ansible-test/playbook/test-playbook.yml", "/home/jeff/ansible-test/playbook/test-playbook1.yml"]
```
i wonder if ansible support json playbook? how can i make it work?

**Comment by Shrews** [comment]
This is not an error from `ansible-runner`. This is coming from ansible itself. It indicates an error while loading your playbook data, and it is most likely a YAML formatting error. For debugging purposes, I would try running your playbook directly using `ansible-playbook`, instead of runner, and using the verbosity option (`-v`, see [docs here](https://docs.ansible.com/ansible/latest/cli/ansible-playbook.html#cmdoption-ansible-playbook-v)) to get more information.

If you need more guidance, the Ansible community offers several ways to seek additional assistance. See [here for how to communicate with them.](https://docs.ansible.com/ansible/latest/community/communication.html#communication)

Since we don't believe this to be a runner problem specifically, I'm going to close this issue. Feel free to open another issue with us if you determine otherwise.

**Comment by jefflaifu** [comment]
> 

I have test my playbook with ansible-playbook CLI, it goes fine.
***My question is, why ansible-runner supply a main.json as a playbook to ansible***
I give two normal YAML playbook path to ansible-runner, it produced a file named main.json, 
```json
["/home/jeff/ansible-test/playbook/test-playbook.yml", "/home/jeff/ansible-test/playbook/test-playbook1.yml"]
```
And I found the command that ansible-runner produced:
```json
{
  "command": [
    "ansible-playbook",
    "-i",
    "/home/jeff/ansible-test/playbook/all.yml",
    "-vvvvv",
    "/tmp/demo2/077369d4-2507-4fca-8a68-041da477a596/project/main.json"
  ],
  ...
}

```
I wonder why. ***Why pass a json to ansible-playbook***
I think ansible-runner shoud pass my playbooks to ansible-playbook directly, not json. 
Just like:
```shell
ansible-playbook -i /home/jeff/ansible-test/playbook/all.yml /home/jeff/ansible-test/playbook/test-playbook.yml /home/jeff/ansible-test/playbook/test-playbook1.yml
```

**Comment by jefflaifu** [comment]
> > 
> 
> I have test my playbook with ansible-playbook CLI, it goes fine. _**My question is, why ansible-runner supply a main.json as a playbook to ansible**_ I give two normal YAML playbook path to ansible-runner, it produced a file named main.json,
> 
> ```json
> ["/home/jeff/ansible-test/playbook/test-playbook.yml", "/home/jeff/ansible-test/playbook/test-playbook1.yml"]
> ```
> 
> And I found the command that ansible-runner produced:
> 
> ```json
> {
>   "command": [
>     "ansible-playbook",
>     "-i",
>     "/home/jeff/ansible-test/playbook/all.yml",
>     "-vvvvv",
>     "/tmp/demo2/077369d4-2507-4fca-8a68-041da477a596/project/main.json"
>   ],
>   ...
> }
> ```
> 
> I wonder why. _**Why pass a json to ansible-playbook**_ I think ansible-runner shoud pass my playbooks to ansible-playbook directly, not json. Just like:
> 
> ```shell
> ansible-playbook -i /home/jeff/ansible-test/playbook/all.yml /home/jeff/ansible-test/playbook/test-playbook.yml /home/jeff/ansible-test/playbook/test-playbook1.yml
> ```



> This is not an error from `ansible-runner`. This is coming from ansible itself. It indicates an error while loading your playbook data, and it is most likely a YAML formatting error. For debugging purposes, I would try running your playbook directly using `ansible-playbook`, instead of runner, and using the verbosity option (`-v`, see [docs here](https://docs.ansible.com/ansible/latest/cli/ansible-playbook.html#cmdoption-ansible-playbook-v)) to get more information.
> 
> If you need more guidance, the Ansible community offers several ways to seek additional assistance. See [here for how to communicate with them.](https://docs.ansible.com/ansible/latest/community/communication.html#communication)
> 
> Since we don't believe this to be a runner problem specifically, I'm going to close this issue. Feel free to open another issue with us if you determine otherwise.


I have test my playbook with ansible-playbook CLI, it goes fine.
***My question is, why ansible-runner supply a main.json as a playbook to ansible***
I give two normal YAML playbook path to ansible-runner, it produced a file named main.json, 
```json
["/home/jeff/ansible-test/playbook/test-playbook.yml", "/home/jeff/ansible-test/playbook/test-playbook1.yml"]
```
And I found the command that ansible-runner produced:
```json
{
  "command": [
    "ansible-playbook",
    "-i",
    "/home/jeff/ansible-test/playbook/all.yml",
    "-vvvvv",
    "/tmp/demo2/077369d4-2507-4fca-8a68-041da477a596/project/main.json"
  ],
  ...
}

```
I wonder why. ***Why pass a json to ansible-playbook***
I think ansible-runner shoud pass my playbooks to ansible-playbook directly, not json. 
Just like:
```shell
ansible-playbook -i /home/jeff/ansible-test/playbook/all.yml /home/jeff/ansible-test/playbook/test-playbook.yml /home/jeff/ansible-test/playbook/test-playbook1.yml
```
