### ISSUE TITLE
How to execute ansible_runner as different user

### ISSUE THREAD

**Issue by kemeris2000** [ansible/ansible-runner#1193]
I am new to ansible_runner. I need to execute ansible_runner process from python script as different user.
Equivalent in bash script is like this:
`runuser -u user1 -- ansible_runner`

here is part of my pythoon script:

```
kwargs = {
            'playbook': playbook_path +'/'+ playbook,
            'limit': hosts_limit,
            'envvars': envvars,
            'private_data_dir': '/tmp',
            'verbosity': verbosity,
            'quiet': 'true'
}
result = ansible_runner.run(**kwargs)

```

I would appreciate for help.

**Comment by Shrews** [comment]
There is no mechanism built into `ansible-runner` for directly executing as a different user. You would need to execute your Python script as that user, either directly, or via a [subprocess](https://docs.python.org/3.8/library/subprocess.html) call. How to do that is beyond any discussion specific to `ansible-runner`.

**Comment by Shrews** [comment]
Just as an FYI, if what you _actually_ want is to run Ansible as a different user, you can read up on how Ansible handles [privilege escalation in these documents](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_privilege_escalation.html).  Runner can deal with Ansible password prompts (for escalation) using `env/passwords` ([see here for documentation on that](https://ansible-runner.readthedocs.io/en/stable/intro/#env-passwords)).
