### ISSUE TITLE
How ansible-runner reads the ansible configuration file?

### ISSUE THREAD

**Issue by Runbacktoo** [ansible/ansible-runner#1197]
I use ansible-runner in django, I want to configure some parameters for it, but I found that no matter how I configure it, it reads the parameters in /etc/ansible/ansible.cfg.
I installed using pip, these are the version information
ansible               6.3.0
ansible-core          2.13.4
ansible-runner        2.3.1
For example, the parameter allow_world_readable_tmpfiles, I tried to specify additional configuration files through the parameter envvars={'ANSIBLE_CONFIG':cfg_file}, and also tried to set 'ANSIBLE_ALLOW_WORLD_READABLE_TMPFILES': True directly in envvars, but none of them took effect. Ansible-runner still seems to be from / etc/ansible/ansible.cfg read allow_world_readable_tmpfiles, but I defined other parameters, it can be read normally, who can tell me the logic of ansible-runner to read the configuration file?

**Comment by Shrews** [comment]
Hi,

`ansible-runner` does not actually use the ansible configuration file. That file is used by the Ansible commands. Runner simply sets the environment variables before making the call to `ansible-playbook`. If the configuration file is not valid or missing, it seems ansible will silently ignore it and fall back to any other configs that it finds.

You can set `verbosity=2` in your call to `interface.run()` to get more output from the ansible command. Setting `verbosity=2, debug=True, ignore_logging=False` gets you even more debug output, and you can see the environment variables that get set. If I were debugging this, I would attempt to eliminate the `ansible-runner` portion and just call `ansible-playbook` with your config and see what happens.

In any case, this isn't a runner issue, but seems to be more on the Ansible side. As such, I'll close this.
