### ISSUE TITLE
Use vanilla base container for tests

### ISSUE THREAD

**Issue by nitzmahone** [ansible/ansible-runner#1204]
The python builder container the tests are currently based on is unlikely to be maintained in the future; bake tests on a vanilla container image (possibly with a build context initially generated by ansible-builder 2.0?).

**Comment by sivel** [comment]
This is potentially covered by https://github.com/ansible/ansible-runner/pull/1232

I included a stripped down `Dockerfile` just for test use.

**Comment by sivel** [comment]
Closing per above
