### ISSUE TITLE
v2.3.2 is not Compatible with Python <= 3.7

### ISSUE THREAD

**Issue by hswong3i** [ansible/ansible-runner#1205]
See https://github.com/ansible/ansible-runner/pull/1191#issuecomment-1451605346

**Comment by Shrews** [comment]
Python 3.8 has been the minimum supported python version since early in the 2.0 releases. The documentation lagged slightly, but it is documented [here in the installation section](https://ansible-runner.readthedocs.io/en/2.3.2/install/#installing-ansible-runner).

**Comment by hswong3i** [comment]
@Shrews so how could our documentation changes affect the behavior of pip? With https://ansible-runner.readthedocs.io/en/2.3.2/install/#using-pip instruction and running on top of Ubuntu 18.04 we will automatically get the 2.y.z version.

Ideally we should also add `python_requires='>=3.8'` to `setup.py`, for all version >= 2.y.z? Create a new release for 2.3.3, and yarn else legacy 2.y.z release from pypi.org?
