### ISSUE TITLE
Ansible Runner contains code which is incompatible with its license

### ISSUE THREAD

**Issue by jkugler** [ansible/ansible-runner#1217]
While debugging an issue today, I came across this file:

https://github.com/ansible/ansible-runner/blob/devel/ansible_runner/display_callback/callback/awx_display.py

At the top of this file is a header indicating this file is GPL licensed, and owned by Redhat.

However https://github.com/ansible/ansible-runner/blob/devel/LICENSE.md says Ansible Runner is under the Apache License. However, these two licenses are not compatible when it comes to requirements for source redistribution of modifications and derivative products.

I realize these files are all owned by Redhat, but if Redhat has chosen to relicense aws_display.py to Apache for this project, that needs to be called out. If this file has *not* been relicensed, then this file (and any other similar files) needs to be called out in the LICENSE file so developers are aware they could be ingesting GPL code into their project.

**Comment by sivel** [comment]
Thank you very much for your submission.  This response is primarily to inform you that we have seen this report, and we will be working on this with our internal counsel.  This effort may take a while, and once we have this information, we will update this issue.

**Comment by jkugler** [comment]
Thank you, @sivel! I appreciate it.

**Comment by sivel** [comment]
Thank you for your patience on this issue.  We have brought this issue to the attention of our internal counsel, and have worked with them to get a response to this concern.

After reviewing the project, the code and licensing, ultimately our counsel has determined that there is no problem with how the project is licensed, distributed, or documented. Per their response these 2 licenses are not incompatible when it comes to requirements for source redistribution of modifications and derivative products in the conventional sense in FOSS.

A global, or root, `LICENSE` file does not dictate that all files contained within a project are licensed per that file. It is common convention within the industry to only include a single `LICENSE` file that describes the overall license of the project, and then use license headers per file to describe any files that do not share this license.

As the file in question, `awx_display.py`, is not utilized from a code perspective in this project, it is what is considered an aggregate in the terms of GPLv3, and as the GPL is not scoped by repository boundaries, there is no issue with an Apache licensed project containing a GPLv3 file within. Additionally, there should be no concern from a licensing perspective including this GPLv3 file in a proprietary fork of ansible-runner.

If you have further questions about how these licenses apply to your project, it is recommend that you consult legal counsel for your organization to ensure you are following their guidance.

**Comment by jkugler** [comment]
I don't see how this can be, since ansible-runner imports and uses aws_display...but OK. I'll take your counsel's word on this. Thanks for updating this!
