### ISSUE TITLE
License Information not Displaying in PyPi Metadata

### ISSUE THREAD

**Issue by buckeye43210** [ansible/ansible-runner#1219]
The license information is missing from PyPi metatdata. This is blocking an automated process to pull ansible-navigator into our internal repo.

    Dependency: PYPI - ansible-builder==1.2.0
      RejectReasons (1)
        RejectReason:   ########-####-####-####-############
          Type:   NO_LICENSES_FOUND
    Dependency: PYPI - ansible-runner==2.3.2
      RejectReasons (1)
        RejectReason:   ########-####-####-####-############
          Type:   NO_LICENSES_FOUND

**Comment by Akasurde** [comment]
@buckeye43210 Thanks for reporting this issue. 

- For Ansible runner - https://github.com/ansible/ansible-runner/pull/1213 - merged.
- For Ansible builder - https://github.com/ansible/ansible-builder/pull/449 - merged.

This will reflect once we have PyPi release for the respective packages.

**Comment by buckeye43210** [comment]
Thank you for resolving this issue. Looking forward to the PyPi release.

**Comment by Akasurde** [comment]
resolved_by_pr https://github.com/ansible/ansible-runner/pull/1213
