### ISSUE TITLE
Running roles directly from python module interface does not work

### ISSUE THREAD

**Issue by kvorhu** [ansible/ansible-runner#1220]
I'm unsure if this is a bug or if I'm doing something wrong. According to the doc, the following should work:
```
# run the role named 'myrole' contained in the '<private_data_dir>/project/roles' directory
r = ansible_runner.run(private_data_dir='/tmp/demo', role='myrole')
```

But as I was testing this, I get 
`ERROR! the playbook: ../playbooks/project/main.json could not be found`
when I run
`r = ansible_runner.run(private_data_dir='../playbooks', role='test')`

The role is within the project dir of my "private_data_dir" (i.e playbooks/project/roles/test).

When I run the python code, a file named main.json is created within the project directory. It has the following contents.
`[{"hosts": "all", "roles": [{"name": "test"}]}]`

Inside artifacts, I see - 
```
"command": ["ansible-playbook", "-i", "/Users/as/git-workspace/patch-manager/Gotopatch/playbooks/inventory", "../playbooks/project/main.json"]
```
I'm not super familiar with this, but can we run an ansible-playbook command with a json file as input ? Is that the cause of this issue ?

**Comment by Akasurde** [comment]
@kvorhu Thanks for reporting this issue. Could you please provide information about the directory structure you are using?

**Comment by kvorhu** [comment]
@Akasurde Sure. This is how my dir structure looks like
```
% tree
.
├── RunnerTest
│   ├── __init__.py
│   ├── __main__.py
│   ├── app.py
│   ├── patcher
│   │   ├── __init__.py
│   │   ├── patcher.py
│   │   └── test.py
│   ├── playbooks
│   │   ├── artifacts
│   │   ├── env
│   │   │   └── envvars
│   │   ├── inventory
│   │   │   └── hosts
│   │   └── project
│   │       ├── main.json
│   │       ├── roles
│   │       │   └── test
│   │       │       ├── README.md
│   │       │       ├── defaults
│   │       │       │   └── main.yml
│   │       │       ├── files
│   │       │       ├── handlers
│   │       │       │   └── main.yml
│   │       │       ├── meta
│   │       │       │   └── main.yml
│   │       │       ├── tasks
│   │       │       │   └── main.yml
│   │       │       ├── templates
│   │       │       ├── tests
│   │       │       │   ├── inventory
│   │       │       │   └── test.yml
│   │       │       └── vars
│   │       │           └── main.yml
│   │       └── test.yml
│   └── tests
│       └── __init__.py
├── Makefile
```

I ran from `test.py ` and the private_data_dir is `playbooks`

**Comment by kvorhu** [comment]
^ accidentally clicked on close while commenting. Re-opened.

**Comment by sivel** [comment]
The problem is with relative pathing.

What you probably want is:

```
private_data_dir=os.path.abspath('../playbooks')
```

That way the path is absolute, instead of a relative path.  What happens is the cwd gets changed to `../playbooks/project` and then the playbook file is set to `../playbooks/project/main.json`, which results in an invalid path to the playbook (`../playbooks/playbooks/project/main.json`)

**Comment by kvorhu** [comment]
Yes, that works!
Thanks a ton. I'll close the issue.
