### ISSUE TITLE
`pkg_resources` is deprecated as an API

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-runner#1223]
https://github.com/pypa/setuptools/blob/main/pkg_resources/__init__.py#L121

Found it was throwing some warnings in navigator's tests.

**Comment by nitzmahone** [comment]
@cidrblock is devtools actually using the runner plugins features, or are you mostly just concerned about the noise from the busted pkg_resources enumeration? I'm definitely +1 for switching over to something else, but I'm also looking for people that are using those features at all...

**Comment by ssbarnea** [comment]
@nitzmahone Can we please get a fix *released* for this issue. For good reasons we aim to run with warnings as errors and this bug is a big PITA for us.

The fix was merged two months ago but no patch release was out since, so we cannot make use of it.

**Comment by nitzmahone** [comment]
@ssbarnea Sure- didn't know it was causing any ongoing grief... We generally don't do releases until there's a bugfix backport deemed "big enough" to be worth kicking one off, then all the other minor fixes like this just come along for the ride.

The fix has already been backported to runner 2.3, so I'll see if someone on the team can do a release within the next few days, or try to do it during a lull at Summit. I assume you're just running from PyPI or something else upstream, and not waiting on p12n for downstream bits?

**Comment by ssbarnea** [comment]
We implemented some workarounds so we will be fine until after the summit.
