### ISSUE TITLE
Some pytest checks failing when building a RPM package for openSUSE Leap / Tumbleweed

### ISSUE THREAD

**Issue by johanneskastl** [ansible/ansible-runner#1237]
When building a RPM package of the current release for openSUSE (using python3.10) I need to disable the following pytest checks, as they fail:

```
IGNORED_TESTS='test_resolved_actions[playbook0] or '                                                                                                                                         
IGNORED_TESTS+='test_worker_without_delete_no_dir or '                                                                                                                                       
IGNORED_TESTS+='test_worker_without_delete_dir_exists or '                                                                                                                                   
IGNORED_TESTS+='test_worker_delete_no_dir or '                                                                                                                                               
IGNORED_TESTS+='test_worker_delete_dir_exists or '                                                                                                                                           
IGNORED_TESTS+='test_process_with_custom_ident or '                                                                                                                                          
IGNORED_TESTS+='test_callback_plugin_task_args_leak[playbook0] or '                                                                                                                          
IGNORED_TESTS+='test_playbook_on_stats_summary_fields'                                                                                                                                       
%pytest -k "not ($IGNORED_TESTS)"
```

The package is being built for openSUSE Leap 15.4 and openSUSE Tumbleweed in the openbuildservice. As far as I can see the dependencies are all present.
Currently only x86_64 is being built.

Several tests are skipped, as podman/docker are not installed (I wanted to start without those first).

The build log is supposed to be attached, but Github could not upload.
Build log can be found here:
https://paste.opensuse.org/pastes/a6bd0c6a1f7c

**Comment by Shrews** [comment]
Our tests are designed to be run via `tox` which properly sets up the test environment. You do not appear to be using this, according to the output in your pastebin.

**Comment by johanneskastl** [comment]
> Our tests are designed to be run via `tox` which properly sets up the test environment. You do not appear to be using this, according to the output in your pastebin.

As this is being built in the Open Build Service, where the worker has no connectivity, all of the dependencies need to be prepared beforehand. In addition, I only care for a limited amount of tests, e.g. there is only one python version this package is intended for. And there is only one ansible-core version.

For the RPM package I would be fine if the pytest checks were fine.

This far I have found a way to tell tox to no initialize all of the ansible27/... things (which fails as it cannot install the dependencies...).

**Comment by Shrews** [comment]
You will have to manually duplicate the tox behavior (dependencies, dev installation of the runner repo, etc) accordingly to achieve what you want. Refer to the `tox.ini` file for the steps it takes. Installing the repo itself seems to be your current problem since it cannot find the executable:

```
stderr = '/bin/sh: ansible-runner: command not found\n'
```

Since this isn't an problem with `ansible-runner` itself, but rather with setting up your unique environment, I'm going to close this issue.

**Comment by johanneskastl** [comment]
Hi @Shrews ,

thanks for the reply. I could solve this by just adding the location in the buildroot to the PATH, and ansible-runner could be found.

There were some checks that still failed:

- one was missing the ssh command
- one failed due to missing network connectivity (test_callback_plugin_task_args_leak[playbook0])

I am currently down to three failing tests:

```
[  154s] ERROR test/integration/test_display_callback.py::test_resolved_actions[playbook0] - packaging.version.InvalidVersion: Invalid version: ''
[  154s] FAILED test/integration/test_display_callback.py::test_callback_plugin_task_args_leak[playbook0] - AssertionError: Unexpected playbook execution failure
[  154s] FAILED test/unit/test_runner.py::test_multiline_blank_write[pexpect] - AssertionError: assert '' == 'hello_world_marker\n\n\n\n'
[  154s] = 2 failed, 2072 passed, 45 skipped, 1 xpassed, 5 warnings, 1 error in 146.60s (0:02:26) =
```

I uploaded the log to https://paste.opensuse.org/pastes/259c3fd83675
