### ISSUE TITLE
Unable to list hosts

### ISSUE THREAD

**Issue by eleksis** [ansible/ansible-runner#1286]
I am trying to use ansible-runner as python module and would like to run a command to get a list of hosts before actually executing playbook. Looking at the code, it seems to me `run` function (And underlying RunnerConfig.__init__) does not accept '--list-hosts' argument. 
I would expect to be able to use all args that ansible-playbook executable accepts.

**Comment by Shrews** [comment]
The `cmdline` parameter to the `run()` function allows for passing abitrary command line options (or the `env/cmdline` file, if you prefer).

**Comment by eleksis** [comment]
Thanks. Closing.
