### ISSUE TITLE
ansible_runner cannot execute the synchronize module smoothly

### ISSUE THREAD

**Issue by Runbacktoo** [ansible/ansible-runner#1298]
I try to use ansible_runner to execute the synchronize module, it has been stuck at the following output while executing, and it has not finished for a long time. When I execute it using ansible, it completes almost instantaneously, what's wrong?
```
TASK [syncAwrFiles] ************************************************************
task path: /home/xx/xx/data/scripts/awr.yml:39
Tuesday 22 August 2023  15:26:02 +0800 (0:00:00.044)       0:00:00.063 ******** 
redirecting (type: modules) ansible.builtin.synchronize to ansible.posix.synchronize
redirecting (type: action) ansible.builtin.synchronize to ansible.posix.synchronize
redirecting (type: action) ansible.builtin.synchronize to ansible.posix.synchronize
```
Version Information:
ansible Version: 6.7.0
ansible runner Version: 2.2.0
OS Version: CentOS Linux release 7.9.2009 (Core)

**Comment by Shrews** [comment]
Without more information here, we'd only be guessing as to what may be happening.

It would help us if you included a demonstration of how you are executing ansible-runner, hopefully with enough info that we could try to recreate the error, and the error logs from runner.

**Comment by Shrews** [comment]
No feedback for a month, so closing this issue.
