### ISSUE TITLE
Docker failed to start containers

### ISSUE THREAD

**Issue by Fan1906** [ansible/ansible-runner#1300]
I can't start containers.
When i delete old Docker and installed new docker.But didn't delete /var/lib/docker dir.
The issue occurred when i started the previous container.
If i want to use the old container.What should i do?

And old version is docker 18

### new Version   
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-209.git7d71120.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7d71120/1.13.1
 Built:           Wed Mar  2 15:25:43 2022
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-209.git7d71120.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7d71120/1.13.1
 Built:           Wed Mar  2 15:25:43 2022
 OS/Arch:         linux/amd64
 Experimental:    false

**Comment by Fan1906** [comment]
sorry,bro.
I didn't get the name of project.I jsut noticed a docker problem

**Comment by Shrews** [comment]
We don't provide support for Docker related issues. I suggest you try https://www.docker.com/support/.
