### ISSUE TITLE
dict provided inventory not read in containerized mode due to incorrect path set

### ISSUE THREAD

**Issue by christophert** [ansible/ansible-runner#1303]
When inventory is provided via a Python `dict`, the output is not written to the correct path in the directory structure. This snippet: https://github.com/ansible/ansible-runner/blob/58b7ff5414d386e266af5e33ba16123ec2ed8f22/src/ansible_runner/utils/__init__.py#L234 writes the content to `inventory/hosts.json` while the runner looks for the inventory in `inventory/hosts` which is set (for containerized mode) in https://github.com/ansible/ansible-runner/blob/58b7ff5414d386e266af5e33ba16123ec2ed8f22/src/ansible_runner/config/runner.py#L163

**Comment by Shrews** [comment]
I've been digging in to the inventory related code recently and can confirm this is definitely a thing that has been broken for a while.

**Comment by Shrews** [comment]
Fixed by #1304
