### ISSUE TITLE
Remove runner tests from ansible-core, and re-implement +/- 1 core testing here

### ISSUE THREAD

**Issue by sivel** [ansible/ansible-runner#1323]
The runner tests in core are pinned to some really old runner version, and don't really assert much of use, except that a very broad shape of data meets expectations.

Remove these tests from core, and re-implement better testing, hopefully against core devel/milestone, stable, and stable-1 at a minimum.

**Comment by Shrews** [comment]
https://github.com/ansible/ansible/tree/devel/test/integration/targets/ansible-runner
