### ISSUE TITLE
passing inventory in the form of python dict obj to `interface.run()` results in broken inventory path

### ISSUE THREAD

**Issue by filip-komarzyniec** [ansible/ansible-runner#1326]
Shortly speaking, the following invocation of `run()` method: 
```

# `inventories` is a list of str denoting paths to a couple of inventories
config = get_inventory(action='list', inventories=inventories, response_format='json', quiet=True)
...
runner = run(private_data_dir="ansible_runner", playbook=playbook_path, inventory=self.config)
```
results in the following errors:
```
WARNING]: Unable to parse
/workspaces/ansible_runner/ansible_runner/inventory/hosts.json
as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'
```

It seems that `private_data_dir` component of the inventory path is doubled:
Instead of _/workspaces/**ansible_runner**/inventory/hosts.json_ it's _/workspaces/**ansible_runner/ansible_runner**/inventory/hosts.json_

After more debugging, it seems that whenever an inventory is specified as a python dict, its content is dumped to the disk in `private_data_dir/inventory/hosts.json` file (`interface.init_runner()` -> `utils.dump_artifacts()` methods). 
Then (in `RunnerConfig.prepare_inventory()` call) a reference to this file is saved as `self.inventory = os.path.join(self.private_data_dir, "inventory")`.
 Finally, all `Runner.run()` calls are executed from `self.cwd`, which is a `private_data_dir` directory. That creates a corrupted path (`self.cwd` + `self.inventory`). 

### Possible solution
With reference to the docs, `inventory` argument to the `run()` method should be either an absolute path or relative with regard to the `private_data_dir` directory. 

In order to be consistent, a `RunnerConfig.inventory` should be held as a path relative to `private_data_dir` or an absolute path. I am opting for the former.

**Comment by Shrews** [comment]
This should be fixed with https://github.com/ansible/ansible-runner/pull/1316

**Comment by Shrews** [comment]
Closing as the referenced PR is merged and should fix this. Next release should contain this fix.
