### ISSUE TITLE
Contenerized ansible-playbook inventory path

### ISSUE THREAD

**Issue by alexandrtru** [ansible/ansible-runner#1347]
Hello, team! 

I've been faced an issue when i passed my inventory as python dictionary to ansible-runner. I see the solution of issue was accepted at PR #1304. It's works as expected, and run playbook in container correctly.

But this fix missing at last release 2.3.6 (https://github.com/ansible/ansible-runner/blob/709cdfc7c595d6fc24b0549eefa99c487cb0e402/ansible_runner/config/runner.py#L164). 

Can you tell me please when this fix will be in release? Or i'm doing something wrong?

Thanks!

**Comment by ktkd** [comment]
looks interested, could you  please provide a more information?

**Comment by Shrews** [comment]
I believe there are a couple of inventory related fixes we should backport to 2.3. I'll put those on my list for the next release (no timeframe as of yet).

**Comment by alexandrtru** [comment]
@Shrews thanks a lot!

**Comment by Shrews** [comment]
You should find this fix now in the latest release (2.4).

**Comment by alexandrtru** [comment]
Yeah! Thanks @Shrews !
