### ISSUE TITLE
`ansible-runner run` does nothing on my Macbook Pro (Apple M3 Pro)

### ISSUE THREAD

**Issue by ryeleo** [ansible/ansible-runner#1354]
When I try to use ansible-runner on my new Macbook Pro, it blocks, but appears to do nothing:

```
❯ ansible-runner -vvvv run -vvvvv . --container-image docker.io/ntsjenkins/junos-ansible-ansible-execution-env:latest --process-isolation --process-isolation-executable docker --limit cc_ah_ldr -p site.yml
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

When I look at Docker Desktop to see what's going on, it shows that the container seems to be sitting idle:

<img width="1026" alt="image" src="https://github.com/ansible/ansible-runner/assets/2552438/20b0dfe3-e094-474c-9785-827e41664c58">

Thanks for this project! It works great in my CICD environment (redhat)!

**Comment by Shrews** [comment]
`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8)`

The answer is right there in your description. That's a warning from docker itself, not runner. Your container image platform (amd64) must match the host (Mac) platform (arm64). That image doesn't appear to have been built with arm64 support.

https://docs.docker.com/build/building/multi-platform/
