### ISSUE TITLE
unix listener too long for Unix domain socket

### ISSUE THREAD

**Issue by Daniel-Pivonka** [ansible/ansible-runner#136]
when running a playbook and the path of environment is too long the playbook will fail to run resulting in the error below placed in the stdout of the run

`unix_listener: path "/home/dpivonka/Documents/paul/ansible-runner-service/samples/artifacts/78a310a2-b118-11e8-975a-54e1ada8887a/ssh_auth.sock" too long for Unix domain socket`

moving the environment to a shorter path resolves the issue.

**Comment by matburt** [comment]
interesting, this may need to go into a tmpdir then: https://github.com/ansible/ansible-runner/blob/master/ansible_runner/runner_config.py#L114

In which case, we'll need to generate a name that won't conflict with other invocations.

**Comment by matburt** [comment]
Fixed in #138
