### ISSUE TITLE
Strange deadlocks due to pexpect.spawn()?

### ISSUE THREAD

**Issue by TheTechromancer** [ansible/ansible-runner#1380]
Hi, first off thanks for making this library, it's very useful. 

Recently I've been running into some [strange deadlocks](https://github.com/blacklanternsecurity/bbot/issues/1571) which appear to be caused by ansible runner. The following warnings are displayed:

```
  /usr/lib/python3.12/pty.py:95: DeprecationWarning: This process (pid=994509) is multi-threaded, use of forkpty() may lead to deadlocks in the child.
    pid, fd = os.forkpty()
```

This warning is due to the use of `pexpect.spawn()` in [`runner.py`](https://github.com/ansible/ansible-runner/blob/c3e8cdb24f784a70328f1bfb54eb9c886148acef/src/ansible_runner/runner.py#L286). I noticed that `pexpect.spawn()` is only called when the config value `runner_mode` is equal to `pexpect` rather than `subprocess`. However, I'm not sure how to set this.

Any help is appreciated. Thanks!

**Comment by Shrews** [comment]
It looks like you are using the runner API in a threaded environment. The `ansible-runner` code is not thread-safe, and this is not recommended.

**Comment by TheTechromancer** [comment]
Ah. In that case I guess we can close the issue.
