### ISSUE TITLE
Reasoning why subprocess is not available over pexpect

### ISSUE THREAD

**Issue by evanraalte** [ansible/ansible-runner#1399]
Hi! 

First of all thank you for providing this library! 

`.venv/lib/python3.12/site-packages/ansible_runner/config/runner.py` line 74 sets `self.runner_mode = "pexpect"`, without an apparent option to override it. What is the reason for doing it like this? In some of the other interface calls I do see the option to set `subprocess` instead.

The reason that I am asking this, is that in Python 3.12, I am getting Deprecation warnings on unit tests that use the ansible-runner:
`DeprecationWarning: This process (pid=xxxx) is multi-threaded, use of forkpty() may lead to deadlocks in the child.`

I isolated this to this minimal example, that shows that this is due to `pexpect` calls: 

```python
def test_pexpect_spawn_process():
    child = pexpect.spawn("python3")
```

I was able to "overwrite" the `running_mode`  to use `subprocess` with this ugly hack:

```python
        from ansible_runner import Runner
        from ansible_runner.utils import dump_artifacts

        def run_wrapper(**kwargs) -> Runner:  # type: ignore[no-untyped-def]  # noqa: ANN003
            dump_artifacts(kwargs)
            runner_config = ansible_runner.RunnerConfig(**kwargs)
            runner_config.prepare()
            runner_config.runner_mode = "subprocess"
            runner = Runner(runner_config)
            runner.run()
            return runner
```

And now my unit tests work as expected without the warning. However, I am not going to use this, as it seems like I am misusing the lib :). Can you perhaps clarify why it is that way? I searched through the latest docs, as well as for 2.4.0 (the version I am using), but could not find anything. Thank you in advance!

**Comment by Shrews** [comment]
None of the original developers for runner are currently working on the project, so I can only speculate, but I would speculate that subprocess is not available as it doesn't provide a way to handle sending passwords when prompted from Ansible. Of course, if you aren't using Ansible in a way that it would prompt for passwords, subprocess would be usable, but it appears that option was not considered in the design.
