### ISSUE TITLE
SSH Issue connecting

### ISSUE THREAD

**Issue by drdouglasghd** [ansible/ansible-runner#145]
I am trying to test the runner locally, and I can't seem to get it to work. 

bind: File name too long
unix_listener: cannot bind to path: /projects/projectx/artifacts/e55fccad-d16d-4738-906f-f6bcc51b49e1/ssh_auth.sock

This looks a lot like https://github.com/ansible/ansible/issues/11536
But my changes to the ansible.cfg don't seem to helping or taking. 

Anyone else had this issue?

**Comment by matburt** [comment]
What version of runner are you using? This looks like it would be solved by https://github.com/ansible/ansible-runner/pull/138

Which is in 1.1.1, can you give that a try and let me know if it's sorted out?

**Comment by matburt** [comment]
It's actually in 1.1.2 which hasn't been released yet... so you'll need to try using the HEAD of this repo.

**Comment by drdouglasghd** [comment]
Thanks @matburt checking out master works.
