### ISSUE TITLE
Ansible Runner Image Vulnerabilities 

### ISSUE THREAD

**Issue by shawn-hurley** [ansible/ansible-runner#148]
https://quay.io/repository/water-hole/ansible-operator/manifest/sha256:dc695d41c91495fac944657ce51c0449b8aa56e274514e9e59476f00e168b281?tab=vulnerabilities

You can see that all of them come from the line:
> file:6340c690b08865d7eb84a36050a0ab0e8effc2b010a4ccb20b810153a97a9228 in /

**Comment by matburt** [comment]
The link doesn't seem to go anywhere? I'm not sure what the action item is on our side? Reopen with more details.

**Comment by shawn-hurley** [comment]
Well, here is the updated manifest: https://quay.io/repository/water-hole/ansible-operator/manifest/sha256:113d773f24f82deafa9428d0bab527738be2e18122b8d43f478f607fa61ca7a0?tab=vulnerabilities

For future reference, you can find it here: https://quay.io/repository/water-hole/ansible-operator?tab=tags and click on the vulnerabilities.

This shows the vulnerability in the ansible-runner base image, and I believe should be updated here. You may be able to fix this by adding an update to the packages installed.

**Comment by shawn-hurley** [comment]
Note: 
I was able to fix the issues by running `yum update -y`.
I think it would be helpful if you guys could do this at the base image layer. If not I can keep it in our Dockerfile.

**Comment by matburt** [comment]
Sounds like I probably just need to respin the images. We'll probably need to do that for our official images also.
