### ISSUE TITLE
ansible-runner is buffering output

### ISSUE THREAD

**Issue by jmontleon** [ansible/ansible-runner#154]
ansible-runner is buffering output. Inside containers I see task output coming in huge chunks, rather than as they occur. Often they never return and the container just hangs forever.

Preceding the ansible-runner command with  `export PYTHONUNBUFFERED=True` causes output to come normally.

We can obviously workaround this in our entrypoint script, but thought it might be beneficial to bring it up so that it can maybe be dealt with inside ansible-runner.

**Comment by matburt** [comment]
@jmontleon can you give #155 a try and see if that works for you?

**Comment by dch** [comment]
@matburt are you able to do a tagged release with #155 in it? I'm porting this to FreeBSD and it's a very useful fix, as well as the other commits since 1.1.1.

**Comment by matburt** [comment]
Fixed in #155

**Comment by matburt** [comment]
@dch I've got one more change I need to get in in order to make a new release: https://github.com/ansible/ansible-runner/pull/157
