### ISSUE TITLE
Event Handler does not work in Docker

### ISSUE THREAD

**Issue by bpereto** [ansible/ansible-runner#166]
Hi,

Awesome work.

### Problem:
Ansible Playbook in a docker container executes, but does not call the event handler.

### Description:
I want the ansible runner to execute ansible in a docker container.  For that I define a custom binary to execute:

`docker-ansible-playbook`
```
#!/bin/bash

docker run -t  -v $(pwd):/ansible/playbooks  ansible-2.6 -vv $@
```

Example script of ansible-runner usage:
```
import ansible_runner
import os

def cancel_callback():
    print('** cancel_callback **')
    return False

def status_handler(status):
    print('** status_handler **')
    print(status)

def event_handler(event):
    print('** event_handler **')
    print(event)

binary = './docker-ansible-playbook'
#binary = 'ansible-playbook'
r = ansible_runner.run(private_data_dir='./',
                       playbook='test.yml',
                       status_handler=status_handler,
                       event_handler=event_handler,
                       cancel_callback=cancel_callback,
                       binary=binary)

print("{}: {}".format(r.status, r.rc))
print(r.stats)
output = r.stdout.read()
```

### Actual Result:
* no event data is printed / event-handler is not executed
* Ansible Runner raises an Exception "no event data found"

### Fazit
As far I can tell the issue is that the regex pattern for event handling does not match:
https://github.com/ansible/ansible-runner/blob/master/ansible_runner/utils.py#L188

Event Bytes with `ansible-playbook`:
`\x1b[KeyJ1dWlkIjogImU0Y2EwMWExLWRjMDMtNDczOC05ZWU0LTNlYjgzY2FmZThhNSJ9\x1b[64D\x1b[K\x1b[Ke30=\x1b[4D\x1b[K ...`

Event Bytes with `docker-ansible-playbook`:
`\x1b[0m\r\n\x1b[0;32m  ... `

Docker seems to not give back the ansi clear line code, so the base64 encoded event uuid is missing.

Any idea?

**Comment by matburt** [comment]
it looks like you've modified the private_data_dir to a place where it probably can't find the test.yml from the demo environment... the private_data_dir needs to be the location where it can find the projects (either the directory that you've mapped in or the default `/runner` location where test.yml is located. It might also not be able to locate the `docker-ansible-playbook` utility that you've created. Can you switch to using absolute paths and give a valid `private_data_dir` ?

**Comment by bpereto** [comment]
Yup you are right.

The `private_data_dir` path must be the same in the container as outside to get it work.

For the sake of completness, here my working "wrapper":
```
#!/bin/bash

docker run -w "$(pwd)" -v $(pwd):$(pwd) myregistry/ansible:2.7 "/usr/bin/ansible-playbook" "$@"
