### ISSUE TITLE
passing in extravars python dict to runner should not require round-tripping via filesystem

### ISSUE THREAD

**Issue by dch** [ansible/ansible-runner#167]
When using `ansible_runner.run()` as a function, the supplied dict should not need to be written out to the filesystem as `/extravars` but should be passed through cleanly and safely to  the runner.

```py
def exec_ansible_runner(project, play, vars):
    # vars must be namespaced within ansible
    r = ansible_runner.run(
        private_data_dir= project,
        playbook= play,
        extravars={'very_secret':vars})
```

I can't follow through https://github.com/ansible/ansible-runner/blob/master/ansible_runner/runner_config.py#L173-L175 where the self object's `extra_vars` dict ends up getting written back out to disk but it presumably is avoidable. Where does this happen?

My read of the docs is that direct inputs to the function would not require the Runner Input Directory Hierarchy (viz "or"):

```
run() helper function

ansible_runner.interface.run()

When called, this function will take the inputs (either provided as direct inputs to the function or from the Runner Input Directory Hierarchy), and execute Ansible. It will run in the foreground and return the Runner object when finished.
```

This was discussed in https://github.com/ansible/ansible-runner/issues/46 and agreed to raise separately.

**Comment by matburt** [comment]
I think we've taken care of this one here: https://github.com/ansible/ansible-runner/pull/203
