### ISSUE TITLE
then env/extravars are overwritten

### ISSUE THREAD

**Issue by hudecof** [ansible/ansible-runner#172]
Take code from the  docs and add extraverts variable

```
import ansible_runner
extravars = {
    'ansible_connection': 'local',
    'test': 'extra'
}

r = ansible_runner.run(private_data_dir='/tmp/demo', playbook='test.yml', extravars=extravars)
print("{}: {}".format(r.status, r.rc))
# successful: 0
for each_host_event in r.events:
    print(each_host_event['event'])
print("Final status:")
print(r.stats)
```

take the demo directory from the repository, where `env/extravars` is

```
---
ansible_connection: local
test: val
```

run the ansible runner and check the `env/extravars`

```
{"test": "extra", "ansible_connection": "local"}
```

According the docs in the code **https://ansible-runner.readthedocs.io/en/latest/_modules/ansible_runner/interface.html#run**

```
 :param extravars: Extra variables to be passed to Ansible at runtime using ``-e``. Extra vars will also be
                      read from ``env/extravars`` in ``private_data_dir``.
```

This not true, they are not read at all and are overwritten.

**Comment by hudecof** [comment]
the version of the ansible and ansible runner

```
(env) [root@centot7 ansible_runner]# pip freeze | grep ans
ansible==2.7.1
ansible-runner==1.1.2
```

**Comment by hudecof** [comment]
I found it here https://github.com/ansible/ansible-runner/blob/master/ansible_runner/utils.py#L168

Why are you dumping it back ?

**Comment by hudecof** [comment]
no feedback, this bug is show stopper in my project

**Comment by matburt** [comment]
Should be fixed up now, will land in the next release
