### ISSUE TITLE
Ansible Runner dump_artifacts() orphans ".artifact_write_lock' file descriptor

### ISSUE THREAD

**Issue by rtproven** [ansible/ansible-runner#177]
The dump_artifacts() in the module ansible_runner/utils.py orphans the ".artifact_write_lock' file descriptor.  Depending on the Ansible module, role, or playbook being run, multiple lock file descriptors may be orphaned per execution. When using Ansible Runner as a python module interface to Ansible within a server/daemon, the server process will eventually hit its open file descriptor limit and get an exception.  The server will then be unable to execute any modules, roles, or playbooks until it is manually restarted.

Below is a snippet of the code in question that includes a one-line modification that has been tested and shown to fix the problem.

if not os.path.exists(fn) or p_sha1.hexdigest() != c_sha1.hexdigest():
        lock_fp = os.path.join(path, '.artifact_write_lock')
        lock_fd = os.open(lock_fp, os.O_RDWR | os.O_CREAT, stat.S_IRUSR | stat.S_IWUSR)
        fcntl.lockf(lock_fd, fcntl.LOCK_EX)

        try:
            with open(fn, 'w') as f:
                f.write(str(obj))
        finally:
            fcntl.lockf(lock_fd, fcntl.LOCK_UN)
            # Close file descriptor before removing file to avoid orphaning descriptor.
            os.close(lock_fd)     <===== Add this line to close descriptor
            os.remove(lock_fp)

    return fn

**Comment by matburt** [comment]
This seems to be fixed by #178
