### ISSUE TITLE
No option to use multiple inventory files (and thus constructed inventories)

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible-runner#179]
a singular parameter:

https://github.com/ansible/ansible-runner/blob/94f58c7c3667102dbafbf3b2349322c594deeccc/ansible_runner/runner_config.py#L249-L250

To be consistent with how Ansible core has operated since 2.4, it needs some way to process a list of inventory sources. The use case of constructed inventories need multiple `-i` flags in order to be usable. See the full documentation here:

https://docs.ansible.com/ansible/latest/plugins/inventory.html

A faster example here:

https://gist.github.com/halberom/e7791aa22c7dd1ef3f1ece3c815b4af8

```
ansible host5 -i hosts -i dynamic.config -m debug -a 'var=groups'
```

Any software that integrates Ansible via runner will be blocked from using any of these features unless runner changes its API to take multiple inventories somehow.

**Comment by matburt** [comment]
To be clear, the reason this isn't *that* big of a deal is because of the default inventory location: https://ansible-runner.readthedocs.io/en/latest/intro.html#runner-input-directory-hierarchy

The override of inventory *does* need to support a list though.

**Comment by matburt** [comment]
Likewise, Runner apparently can't take a directory for sourcing inventory:

`Is a directory: '/opt/ansible/inventory`

**Comment by willthames** [comment]
Is there a reason ansible-runner ignores ansible.cfg's inventory setting?

**Comment by matburt** [comment]
There's nothing that specifically overrides ansible.cfg settings in Runner. If it's not picking it up then we'll need to debug why.

**Comment by AlanCoding** [comment]
@willthames a common question we have with AWX is why some config options aren't respected. Runner will automatically set some Ansible settings via env vars.

https://github.com/ansible/ansible-runner/blob/d1c664f4f122b3b44c53a4f7c74f45102b9eb7b2/ansible_runner/runner_config.py#L141-L147

Env vars take precedence over the config file's value, so if you tried to set one of these, that's your answer. If it's another setting, then you've got some other problem.

**Comment by willthames** [comment]
@alancoding This is literally just using `ansible-runner -p runner_test.yml`

If I have inventory in my working directory, it works fine. But if I point ansible.cfg to say runner_test/inventory, then the above command does not work

**Comment by matburt** [comment]
@willthames likely we are trying to locate the inventory in the private data dir and that's overriding your desired location. I guess it doesn't work there due to the error I displayed above?

**Comment by willthames** [comment]
It doesn't work there because ansible-runner doesn't cope with inventory directories, correct. 

It is somewhat confusing that the only ansible.cfg directive that isn't honoured by ansible-runner is the `inventory` directive, and we'd definitely want to have an override capability.

**Comment by fabianvf** [comment]
I would guess the reason it doesn't respect the inventory setting is probably that the `-i` option is always set https://github.com/ansible/ansible-runner/blob/master/ansible_runner/runner_config.py#L252
