### ISSUE TITLE
Sensitive information sometimes is writen to artifacts, sometimes not. 

### ISSUE THREAD

**Issue by sarasonparas** [ansible/ansible-runner#191]
I run a very simple playbook via `ansible_runner.interface.run` : 

     - name: Manage new IAM groups
     iam_group:  
        aws_access_key: "{{ aws_access_key | replace('\n', '')}}"
        aws_secret_key: "{{ aws_secret_key | replace('\n', '')}}"
        region: "eu-west-2" 
        name: "{{ item.name }}"
        state: "{{ item.state }}"
     loop: "{{ iam_groups }}"

My aws_secret_key (which is encrypted in the vault) is replaced by "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER" in some  of files in artifacts/job_events/:  

`{ ... "module_args": {"aws_access_key": "A....", "aws_secret_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "region": "eu-west-2", "name": "blah_test", "state": "absent", "validate_certs": true, "managed_policy": [], "users": [], "purge_users": false, "purge_policy": false, "ec2_url": null, "security_token": null, "profile": null}}, "_ansible_parsed": true, "_ansible_no_log": false, "item": {"name": "blah__test", "state": "absent"}, "_ansible_item_result": true, "_ansible_ignore_errors": null, "_ansible_item_label": {"name": "blah_test", "state": "absent"}}, "pid": 38314}, "pid": 38314, "created": "2019-01-22T23:36:13.199740"}` (the expected result)

But it some files  the aws_secret key is displayed in clear text:

`{"uuid": "238b74a7-d567-418c-8b5b-27470bdca61b", "counter": 4, "stdout": "ok: [localhost] => (item={'name': 'blah_test', 'state': 'absent'})", "start_line": 4, "end_line": 5, "runner_ident": "2af585c5-95c8-4cdb-8da6-fed353ebb7be", "event": "runner_item_on_ok", "event_data": {"playbook": "ansible_iam/iam_users.yaml", "playbook_uuid": "23116bc0-0dc7-40cd-a335-7540f26af3a0", "play": "local", "play_uuid": "3c15c2cb-0d08-f12c-24d6-000000000006", "play_pattern": "local", "task": "Manage new IAM groups", "task_uuid": "3c15c2cb-0d08-f12c-24d6-00000000000b", "task_action": "iam_group", "task_path": "ansible_iam/roles/iam_groups_new/tasks/main.yml:4", "task_args": "aws_access_key=A...., aws_secret_key=***** (THE SECRET KEY IN CLEAR TEXT) ... }`.  (The unexpected result)

The `job_events` dir is in my `private_data_dir`- does it mean that it's supposed to keep sensitive information? 

Is there any way to get the full output into the log files, but keep the `aws_secret_key` hidden? Ansible's `no_log` at the task level hiddes everything - not a good option for debug.

**Comment by matburt** [comment]
This information comes back to Runner directly through Ansible itself, hiding this information is the goal of `no_log`.
