### ISSUE TITLE
Document the difference between stdout_callback and stats

### ISSUE THREAD

**Issue by kkirsche** [ansible/ansible-runner#196]
Currently, the status output of `ansible-runner` differs from that of `ansible-playbook` which can confuse new users.

The `ansible-playbook` output when using the JSON stdout callback looks like so:

```
    "stats": {
        "redacted.domain.com": {
            "changed": 1,
            "failures": 0,
            "ok": 6,
            "skipped": 0,
            "unreachable": 0
        }
    }
```

on macOS with the following version(s):

```
$ ansible-playbook --version
ansible-playbook 2.7.6
  config file = /Users/kkirsche/git/ansible/playbooks/hashicorp/ansible.cfg
  configured module search path = ['/Users/kkirsche/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.7.2 (default, Jan 13 2019, 12:50:01) [Clang 10.0.0 (clang-1000.11.45.5)]
```

While the stats output by `ansible-runner` instead use `dark`:

```
{
  'dark': {},
  'failures': {},
  'skipped': {},
  'ok': {
    u'localhost': 2
  },
  'processed': {
    u'localhost': 1
  }
}
```

Because of the additional stat `processed` and the use of `dark` instead of `unreachable`, it would be useful to document what each status means and the difference between the status shown by `ansible-playbook` and `ansible-runner` or at a minimum the meaning and coverage of each status within the tool itself.

**Comment by varac** [comment]
How do you configure a `stdout_callback` anyhow ? How can I reproduce your issue, can you give me an example how you invoked ansible-runner with a non-default `stdout_callback` please ?

**Comment by kkirsche** [comment]
It’s not about the use within ansible-runner but explaining how someone who began working with ansible-playbook’s callback runners directly would know what this differing terminology means. 

The goal here would be to explain what the terms mean since it is not consistent with the core ansible-playbook to. As such, I can’t provide an example as requested because such an example isn’t what this issue is mentioning

**Comment by kkirsche** [comment]
https://docs.ansible.com/ansible/latest/plugins/callback/json.html

Is the callback plugin mentioned

**Comment by AlanCoding** [comment]
replying to

> How do you configure a `stdout_callback` in ansible-runner anyhow ? How can I reproduce your issue, can you give me an example how you invoked ansible-runner with a non-default `stdout_callback` please ?

I had https://github.com/ansible/ansible-runner/pull/412 up, which is a direct solution to this issue.

But I have gotten cold feet about it, since Ansible itself is imposing increasingly strict rules for collection content (via `ansible-test`), and I am very hesitant about re-writing the `DOCUMENTATION` string, because it is very clearly meant to be a static block of text. Doing this would be required for dynamically subclassing the callback that the user gives.

Instead, I would be interested to involve https://github.com/ansible/ansible to get a somewhat supported best practice for this. You could write your own collection and add the `ansible-runner` collection (with its callback plugin) as a dependency. Then all you have to do is add a callback plugin that subclasses both the JSON callback and the `ansible-runner` integration callback, and does nothing else.

Beyond that, a trivial means of customizing would need to be added to runner, like https://github.com/ansible/ansible-runner/pull/400

**Comment by matburt** [comment]
I think what ended up happening here is a normalization of event data that we expected to get in a future ansible version. I would expect these to all have normalized at this point.

**Comment by AlanCoding** [comment]
I ran my host status testing playbook with Ansible devel:

### from runner status event

```json
  "changed": {
    "3_changed": 1
  },
  "dark": {
    "7_unreachable": 1
  },
  "failures": {
    "4_failed": 1
  },
  "ignored": {
    "5_ignored": 1
  },
  "ok": {
    "1_ok": 1,
    "3_changed": 2,
    "4_failed": 1,
    "5_ignored": 2,
    "6_rescued": 2,
    "7_unreachable": 2
  },
  "processed": {
    "1_ok": 1,
    "2_skipped": 1,
    "3_changed": 1,
    "4_failed": 1,
    "5_ignored": 1,
    "6_rescued": 1,
    "7_unreachable": 1
  },
  "rescued": {
    "6_rescued": 1
  },
  "skipped": {
    "2_skipped": 7,
    "1_ok": 6,
    "4_failed": 1,
    "5_ignored": 5,
    "6_rescued": 5,
    "7_unreachable": 4,
    "3_changed": 5
  }
```

### from Ansible with JSON callback

```json
        "1_ok": {
            "changed": 0,
            "failures": 0,
            "ignored": 0,
            "ok": 1,
            "rescued": 0,
            "skipped": 6,
            "unreachable": 0
        },
        "2_skipped": {
            "changed": 0,
            "failures": 0,
            "ignored": 0,
            "ok": 0,
            "rescued": 0,
            "skipped": 7,
            "unreachable": 0
        },
        "3_changed": {
            "changed": 1,
            "failures": 0,
            "ignored": 0,
            "ok": 2,
            "rescued": 0,
            "skipped": 5,
            "unreachable": 0
        },
        "4_failed": {
            "changed": 0,
            "failures": 1,
            "ignored": 0,
            "ok": 1,
            "rescued": 0,
            "skipped": 1,
            "unreachable": 0
        },
        "5_ignored": {
            "changed": 0,
            "failures": 0,
            "ignored": 1,
            "ok": 2,
            "rescued": 0,
            "skipped": 5,
            "unreachable": 0
        },
        "6_rescued": {
            "changed": 0,
            "failures": 0,
            "ignored": 0,
            "ok": 2,
            "rescued": 1,
            "skipped": 5,
            "unreachable": 0
        },
        "7_unreachable": {
            "changed": 0,
            "failures": 0,
            "ignored": 0,
            "ok": 2,
            "rescued": 0,
            "skipped": 4,
            "unreachable": 1
        }
```

**Comment by AlanCoding** [comment]
Link fix https://github.com/ansible/ansible-runner/pull/536

This is not addressing, in any way, the disparity between the Ansible internal field names sent to the playbook_on_stats callback method and the reported event types from the JSON callback / playbook display generally. This just found a minor omission that's completely inarguable in terms of expectations.
