### ISSUE TITLE
sharing project between runners.

### ISSUE THREAD

**Issue by tuxknight** [ansible/ansible-runner#201]
It may be a common pattern that organizing many playbooks/roles in one repo.  Three roles and playbooks [tomcat/nginx/zabbix] for example are in project folder. Each playbook needs different env/extravars env/envvars .

One solution is that every runner keep its independent private_data_dir but using soft link to share on common project directory.

The other solution is making runner running with options of [env_dir, inventory_dir, project_dir] other than private_data_dir.

So, any suggestions or discussions on this ?

**Comment by matburt** [comment]
I'm not seeing a large compelling use case here. This would seem to overlap with the purpose of roles/defaults or roles/vars
