### ISSUE TITLE
missing reference in Dockerfile

### ISSUE THREAD

**Issue by magick93** [ansible/ansible-runner#208]
Hello

I'm trying to build the Dockerfile, using `docker build`, but am unable to as it is referencing a local directory that doesnt exist in this repo.

Specifically, https://github.com/ansible/ansible-runner/blob/master/Dockerfile#L29 - there is no `dist` directory in this repo.

**Comment by matburt** [comment]
Please don't open issues if you are just seeing help. Post to the mailing list or use the irc channel instead.

**Comment by matburt** [comment]
You need to `make dist` to build a dist first.
