### ISSUE TITLE
Document how to use the yaml stdout_callback plugin

### ISSUE THREAD

**Issue by varac** [ansible/ansible-runner#212]
The main issue I have with ansible-runner is that it is using the default ansible stdout_callback, which is horrible to parse (as human) when it comes to multi-line failures like:

```
Feb 14 13:15:51     "installTiller.stdout": "serviceaccount/tiller created\nclusterrolebinding.rbac.authorization.k8s.io/tiller-clusterrolebinding created\n$HELM_HOME has been configured at /root/.helm.\n\nTiller (the Helm server-side component) has been installed into your Kubernetes Cluster.\n\nPlease note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.\nTo prevent this, run `helm init` with the --tiller-tls-verify flag.\nFor more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation\nHappy Helming!\nWaiting for deployment \"tiller-deploy\" rollout to finish: 0 of 1 updated replicas are available...\ndeployment \"tiller-deploy\" successfully rolled out"
```

With ansible-playbook, using `stdout_callback = yaml` gives a much cleaner output. But I can't find a way of using this callback plugin in ansible-runner. Is there a way ?
Same question goes for `callback_whitelist = profile_tasks, timer` which are the other callbacks we'd like to use.

**Comment by matburt** [comment]
We *do* have a json output mode:

https://ansible-runner.readthedocs.io/en/latest/standalone.html#outputting-json-raw-event-data-to-the-console-instead-of-normal-output

Which is also available as on the module interface. I feel like we can probably add a yaml mode to that also.

Runner itself uses a callback to drive its event collections which can cause issues if it's removed *as* the callback plugin. You can probably add others without much issue but you'll need to do it from the environment variable or ansible.cfg.
