### ISSUE TITLE
Cannot run from python

### ISSUE THREAD

**Issue by cdvv7788** [ansible/ansible-runner#22]
I am trying to run some playbook. I created the directory structure, provided an ssh key, the playbook (it is in a subfolder of "project") and the inventory.
I am getting the following error:
![image](https://user-images.githubusercontent.com/5531776/39101357-2fe6e66a-465e-11e8-9e35-836744072cad.png)

I am running ansible 2.5.1 installed in system (the one I had installed in virtualenv did not work).

Any idea about what I am doing wrong?

**Comment by privateip** [comment]
@cdvv7788 The good news is you aren't doing anything wrong.  The bad news is that it's definitely a bug in the `runner_config` code.  Looking at at fix for this now.

**Comment by matburt** [comment]
Fixed in #26

**Comment by cdvv7788** [comment]
Thanks guys! Awesome project by the way :).
