### ISSUE TITLE
Inventory script copied not preserving permissions

### ISSUE THREAD

**Issue by andyshinn** [ansible/ansible-runner#224]
I'm using `--inventory` with a script (`gce.py`). It gets copied to `${private_data_dir}/inventory/hosts` but isn't executable:

```console
$ ls -al gce.py 
-rwxr-xr-x@ 1 andy  staff  18346 Aug  6  2018 gce.py
$ ls -al ~/Projects/temp/runner/inventory/hosts
-rw-rw-rw-  1 andy  staff  18346 Mar 18 21:59 /Users/andy/Projects/temp/runner/inventory/hosts
```

Once I added the executable bit it works fine. Not quite sure if this is a feature request or a bug. But I assume because it is copying the inventory file over it should preserve the bits.

I did some digging in code but can't even figure out where this is being copied. Versions:

```console
$ uname -a
Darwin Andys-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
$ ansible --version
ansible 2.7.8
  config file = /Users/andy/Projects/myproj/infrastructure/ansible.cfg
  configured module search path = ['/Users/andy/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.2 (default, Feb 12 2019, 08:15:36) [Clang 10.0.0 (clang-1000.11.45.5)]
$ ansible-runner --version
1.2.0
```

**Comment by matburt** [comment]
It probably should, though generally the idea is to have this *already* populated in the private data directory prior to execution. The inventory flag is the override for that.

**Comment by AlanCoding** [comment]
I can't replicate:

```
ansible-runner run test/data/debug/ --inventory ~/Documents/repos/jlaska-ansible-playbooks/inventories/dyn_inventory.py -p debug.yml
```

This correctly uses the inventory https://github.com/ansible/test-playbooks/blob/master/inventories/dyn_inventory.py, and I don't see any evidence that it is copied in the process.

Feel free to reopen or make a new issue if you can get us a CLI or python use that hits the issue.
