### ISSUE TITLE
git package missing from docker Image

### ISSUE THREAD

**Issue by cloudbree** [ansible/ansible-runner#232]
Even though the runner image contains the ansible-galaxy script, it seems to be missing the git binary, which would might be required to install role dependencies from a git repository. Is that intended behaviour ? I think in a cloud-native scenario, that could be a very useful addition to the image. What do you think ? Is that something that we could include within this image ?

P.S.: If it would not be a problem, we can open a PR.

Thanks!

**Comment by matburt** [comment]
Yep, I'd be amenable to that.

**Comment by cloudbree** [comment]
Hi @matburt ,

That's great mews!

Just submitted the PR.

Thanks!
