### ISSUE TITLE
Multi-line verbose events

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible-runner#242]
Moving https://github.com/ansible/awx/issues/2129 to here

> Ansible events can be multi-line, but any verbose events (which are not Ansible events) can be only 1 line each

> It would be more performant to save multiple lines to a single event, when write is called to the standard out buffer in that way.

This applies for both playbook and verbose events.

Doing this may also require enforcing some maximum event size threshold within the standard out wrapper class.

**Comment by matburt** [comment]
Figuring out where that boundary is is the tricky part that would need a solution. You can't just have an unbounded grouping of line events, and arbitrary groupings based on number of lines isn't any more meaningful than single-line event storage. It could also complicate line storage in that you aren't able to fundamentally separate the lines even if you did have a rubric.

**Comment by matburt** [comment]
Given that, I'm not sure that there is a valid solution or even a *need* to have something like this in the general case?

**Comment by AlanCoding** [comment]
> You can't just have an unbounded grouping of line events, and arbitrary groupings based on number of lines isn't any more meaningful than single-line event storage.

Sorry, let me give a specific case of my own.

https://github.com/ansible/ansible/blob/fbaa6c33caab85a0f71c39142d0ea7ed71e30515/lib/ansible/inventory/manager.py#L294

Ansible calls `display.vvv(to_text(fail['tb']))`. This prints a traceback, the playbook hasn't failed, it continues running and will probably be successful. For non-trivial cases, the output tends to be 10-ish lines.

```
  File "/venv/python2_ansibledevel/lib/python2.7/site-packages/ansible/inventory/manager.py", line 272, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/venv/python2_ansibledevel/lib/python2.7/site-packages/ansible/plugins/inventory/auto.py", line 50, in parse
    plugin = inventory_loader.get(plugin_name)
  File "/venv/python2_ansibledevel/lib/python2.7/site-packages/ansible/plugins/loader.py", line 554, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/venv/python2_ansibledevel/lib/python2.7/site-packages/ansible/plugins/loader.py", line 532, in _load_module_source
    module = imp.load_source(to_native(full_name), to_native(path), module_file)
  File "/venv/python2_ansibledevel/lib/python2.7/site-packages/ansible/plugins/inventory/linode.py", line 68, in <module>
    raise AnsibleError('the Linode dynamic inventory plugin requires linode_api4.')
```

That's a meaningful grouping. There might be more implementation details that make this more challenging to obtain, like if the tty split up some of this output already (I would hope not, but I'm not savvy enough to know). Even though tracebacks can be much longer if you have a recursion depth error, it seems obvious that the user would never prefer this split, setting aside implementation details.

A related issue is that the standard out wrapper [delays sending events](https://github.com/ansible/awx/issues/3485) until the complete end of a non-ansible-playbook run because it's waiting (in vein) for event data.

Speaking from the most simplistic of user expectations, both of these behaviors look undesirable.

**Comment by matburt** [comment]
I don't think we'd ever be able to properly detect groups of stdout without some form of help one way or another.

It would be super nice to be able to have this context, I just can't think of anything that we could get and the value would be minimal.
