### ISSUE TITLE
RFE: if pip installed from git, emit version number that shows git hash

### ISSUE THREAD

**Issue by kdelee** [ansible/ansible-runner#253]
Right now the version emitted by `ansible-runner --version` appears to be hard coded. This can lead to some doubt when attempting to determine what changeset is installed on a machine.

Ideally, only released versions of `ansible-runner` would show the version number like `1.3.1` and other installed changesets would show a version like `657fc6d75b32844aa0d240604f138f0e8baf5335`.

`ansible` does something like this

**Comment by shanemcd** [comment]
This should be addressed when we move to PBR.

**Comment by Akasurde** [comment]
[`pbr`](https://docs.openstack.org/pbr/latest/) is implemented. Closing this issue.
