### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by cdvv7788** [ansible/ansible-runner#29]
I am running the demo on this project. Cloned the repo, copied it to /tmp and ran the following commands:

![image](https://user-images.githubusercontent.com/5531776/39412022-ff8e4a80-4bda-11e8-9810-41f717e3d1da.png)
Nothing outputs.
r.status is 'failed' but there is no clue about what is failing.

**Comment by matburt** [comment]
What do you see in the artifacts directory under the listed in the private data dir?

**Comment by cdvv7788** [comment]
I see the following:
![image](https://user-images.githubusercontent.com/5531776/39437247-e82ffd12-4c65-11e8-8f77-e886ed868101.png)
Inside each folder, there are 3 files:
rc: 250
status: failed
stdout:

**Comment by matburt** [comment]
I know it's been a couple of weeks, I'm sorry it's taken me a while to get back to you... can you try this with the latest HEAD?

**Comment by cdvv7788** [comment]
Thanks for checking this. After using the latest version, I get the following:
![image](https://user-images.githubusercontent.com/5531776/40189524-49b19cc6-59c2-11e8-8aff-5a7a246768bf.png)

**Comment by matburt** [comment]
Fixed in #34
