### ISSUE TITLE
Ansible-playbook runs correcrtly, but no changes made in slaves hosts

### ISSUE THREAD

**Issue by NahaliY** [ansible/ansible-runner#299]
I have an issue with ansible-runner, I'm using docker-compose to run the ansible-runner, configured SSH for nodes access. When running the docker-compose, the output shown is correct. But when accessing slaves, there is no changes made.
Anyone have an idea about this ?
PS: the log don't show any error

`root@master:~/Docker-compose# docker-compose up
Starting docker-compose_ansible-deployment_1 ... done
Attaching to docker-compose_ansible-deployment_1
ansible-deployment_1  |
ansible-deployment_1  | PLAY [all] *********************************************************************
ansible-deployment_1  |
ansible-deployment_1  | TASK [Gathering Facts] *********************************************************
ansible-deployment_1  | ok: [Slave]
ansible-deployment_1  | ok: [Local]
ansible-deployment_1  |
ansible-deployment_1  | TASK [Ansible create file if it doesn't exist example] *************************
ansible-deployment_1  | changed: [Slave]
ansible-deployment_1  | changed: [Local]
ansible-deployment_1  |
ansible-deployment_1  | PLAY RECAP *********************************************************************
ansible-deployment_1  | Local                      : ok=2    changed=1    unreachable=0    failed=0
ansible-deployment_1  | Slave                      : ok=2    changed=1    unreachable=0    failed=0
ansible-deployment_1  |
docker-compose_ansible-deployment_1 exited with code 0
`

**Comment by matburt** [comment]
I dunno? hard to know without more information... make sure you aren't doing something like setting `ansible_connection: local` in the vars or properties.

**Comment by NahaliY** [comment]
The task is executed in the container only. I specified in the inventory my hosts, but ansible-runner don't consider that 

[all]
Local  ansible_host=192.168.56.130 ansible_user=root  ansible_port=22   ansible_python_interpreter=/usr/bin/python3  ansible_ssh_private_key_file=~/.ssh/id_rsa
Slave  ansible_host=192.168.56.131 ansible_user=root  ansible_port=22   ansible_python_interpreter=/usr/bin/python3  ansible_ssh_private_key_file=~/.ssh/id_rsa
``

**Comment by matburt** [comment]
There is a separate vars config file, for example in the demo directory.... check that and make sure you aren't setting ansible_connection there.
