### ISSUE TITLE
When a file is not loaded, a reason should be present

### ISSUE THREAD

**Issue by cdvv7788** [ansible/ansible-runner#30]
I noticed the following behaviour (test.py just contains the 2 lines in the readme for running from python):
![image](https://user-images.githubusercontent.com/5531776/39442058-9ac657a0-4c75-11e8-83ac-544081007160.png)

The file could fail to load for several reasons. I guess that those are mainly:
- File does not exist
- File is not well formatted

With the current message, the user has no idea if the system is not loading it correctly (because there is some issue with the naming convention) or is not able to parse (syntax issue in the image).

Should that be validated to improve the messages?

**Comment by privateip** [comment]
@cdvv7788 Agreed with your comment.  I'm working on a major refactor of runner_config that will address this issue (among some others) but its still a couple of weeks out before its ready.  Will make a note and try to remember to reference this issue once the PR is up.

**Comment by privateip** [comment]
@cdvv7788 can you confirm #32 addresses your use case?

**Comment by cdvv7788** [comment]
With the proposed fix at https://github.com/ansible/ansible-runner/pull/66 the messages for ssh_key should improve.

**Comment by matburt** [comment]
I think this is taken care of?

```
ERROR! Invalid extra vars data supplied. '@emo/env/extravars' could not be made into a dictionary
```

Let me know and we can re-open and include an example that shows the error.
