### ISSUE TITLE
Publish ansible-runner image for Power (ppc64le)

### ISSUE THREAD

**Issue by snehlatamohite** [ansible/ansible-runner#322]
Hi ,

We could able to build ansible-runner package & image on Power by doing minor change in Dockerfile. tini version 0.18.0 is available for Power so, only change for power in the dockerfile will be "ADD https://github.com/krallin/tini/releases/download/v0.18.0/tini-ppc64el /tini". 
Just want to check , would it be possible to get that ansible runner image published for Power?  

Any pointers will help to proceed further. Thanks!

Thanks,
Snehlata Mohite.

**Comment by matburt** [comment]
We can't actually change that dockerfile in-place because it would break non-ppc architecture. I'm all for adding another dockerfile that does this but I don't have any ppc systems to verify it.

**Comment by snehlatamohite** [comment]
Hi Matthew,

Please do fill in OSU form - http://osuosl.org/services/powerdev/request_hosting/ for getting a power VM access. Please enter Gerrit’s email ID as IBM advocate( gerrit@us.ibm.com) while filling the form.

Please do let me know if you have any queries. 

Thanks,
Snehlata Mohite.

**Comment by matburt** [comment]
Snehlata, I don't really have the bandwidth to do this right now. So if you want to get it set up, write up the Dockerfile, and test it out before submitting a PR then go for it.

**Comment by snehlatamohite** [comment]
Thanks Mathhew.
Sure I will do the needful. 
Should I change existing docker file to build ansible-runner image for amd64 and ppc64le both architecture?
OR 
Add new dockerfile for ppc64le?

Please suggest.

**Comment by matburt** [comment]
Probably a new one, I'd still like to use the existing one to build upstream images.  It'd be helpful to add some other tooling around it to build and tag all of them.

**Comment by snehlatamohite** [comment]
Hi Mathhew , 

I have raised PR (https://github.com/ansible/ansible-runner/pull/334) having dockerfile for Power. 

I have tested build on Power.  Please review. 

Thanks,
Snehlata Mohite.

**Comment by AlanCoding** [comment]
I'm looking into options to make it easier to users to customize the build process. Recently, for instance, we added a build arg for the base image.

Right now I'm in the middle of adding a new build arg for the Ansible version (or install method).

Looking closely at what you're doing, it seems like what you need is:

```diff
diff --git a/Dockerfile b/Dockerfile
index 0b36d7f..efb7853 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -11,7 +11,7 @@ ADD demo/inventory /runner/inventory
 #ADD https://releases.ansible.com/ansible-runner/ansible-runner.el8.repo /etc/yum.repos.d/ansible-runner.repo
 #RUN dnf install -y ansible-runner
 RUN dnf install -y python3-pip rsync openssh-clients sshpass glibc-langpack-en git \
-    https://github.com/krallin/tini/releases/download/v0.19.0/tini_0.19.0-amd64.rpm && \
+    https://github.com/krallin/tini/releases/download/v0.18.0/tini-ppc64el && \
     rm -rf /var/cache/dnf
 
 RUN dnf install -y gcc python3-devel
```

Maybe I don't have that quite right, but it probably gets the important thing as far as we're concerned. We may not be concerned with changing the tini release either (18 vs 19), so it's just the trailing part with the architecture in it that needs to be customizable.

This still seems dicey, but we could add a build arg for it, in principal.

**Comment by shanemcd** [comment]
There's a (stale) PR open that does this: https://github.com/ansible/ansible-runner/pull/426

I dont think we have the capacity or resources to properly support and distribute this, but I'm fine with leaving this issue open if and until that changes.

**Comment by sivel** [comment]
We have decided to no longer maintain, support, or create container images for ansible-runner going forward.

Please see https://github.com/ansible/ansible-runner/issues/1199 for more information.
