### ISSUE TITLE
Importing yaml files in ansible-playbook

### ISSUE THREAD

**Issue by pranavbarve125** [ansible/ansible-runner#329]
I am running ansilbe-playbooks using the ansible-runner in python.

I have a configuration yaml file. I want my playbooks to import that configuration file in order to use the variables from that file.

I am using jinja2 templating to use the variables for that yaml files.

Is there any way in the ansible_runner module to import a yaml config file?

Is there any way I can do this?

**Comment by privateip** [comment]
Can you expand on the description of what you are trying to do here?  Do you want the playbook to import the config file as a set of variables?  If that is the case then you should use the appropriate ansible playbook directive and put your vars file in the corresponding right place (typically in `project/vars`)

**Comment by matburt** [comment]
I'm also unclear on if you are talking about an `ansible.cfg` or some normal vars file. It sounds like you may want this: https://docs.ansible.com/ansible/latest/modules/include_vars_module.html

**Comment by jiridanek** [comment]
I've been looking for equivalent to https://docs.ansible.com/ansible/latest/cli/ansible-playbook.html#cmdoption-ansible-playbook-e

> -e, --extra-vars
> set additional variables as key=value or YAML/JSON, if filename prepend with @

edit:

and the answer seems to be to use the `extravars` parameter of `ansible_runner.run()` if I have one file, and either `cmdline` parameter or `include_vars` module from the previous comment, in case I have multiple files.

```python
        if self.extra_vars:
            if isinstance(self.extra_vars, dict) and self.extra_vars:
                extra_vars_list = []
                for k in self.extra_vars:
                    extra_vars_list.append("\"{}\":{}".format(k, json.dumps(self.extra_vars[k])))

                exec_list.extend(
                    [
                        '-e',
                        '{%s}' % ','.join(extra_vars_list)
                    ]
                )
            elif self.loader.isfile(self.extra_vars):
                exec_list.extend(['-e', '@{}'.format(self.loader.abspath(self.extra_vars))])
```
