### ISSUE TITLE
Publish ansible/ansible-runner image v1.3.5

### ISSUE THREAD

**Issue by drubitsa** [ansible/ansible-runner#338]
I can't find related Docker image tag for version 1.3.5 on hub.docker.com.
It would be useful, with Ansible 2.8.

**Comment by supersmo** [comment]
Wow! I also need this and you beat me by 30 seconds. :-)

**Comment by matburt** [comment]
1.3.5 was pulled due to some issues. Next release will be 1.3.6 and hasn't happened yet, but it'll pick up the changes that were originally targeted at 1.3.5

**Comment by prometheanfire** [comment]
when is 1.3.6 going to come out?  I'd like to get it into openstack before we freeze our libraries.
