### ISSUE TITLE
stats not correct

### ISSUE THREAD

**Issue by lonelyword** [ansible/ansible-runner#349]
Hi

I use ansible_runner to run playbook, and the result is 
PLAY RECAP *********************************************************************
TestCiscoN6K               : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

However, when I use r.stats, the result is 
>>> r.stats
{'skipped': {}, 'ok': {}, 'dark': {}, 'failures': {'TestCiscoN6K': 1}, 'processed': {'TestCiscoN6K': 1}}

Ansible version is 2.8.4 and ansible_runner version is 1.3.4.

**Comment by AlanCoding** [comment]
I would like to see a private data dir with a playbook that gives concrete reproduction steps.
