### ISSUE TITLE
Inventory variable in runner incorrectly parsed

### ISSUE THREAD

**Issue by rdarbha** [ansible/ansible-runner#351]
I used the following syntax to execute the ansible runner:

```
r = ansible_runner.run(private_data_dir='/home/cumulus/ansible-runner-api/tmp/', playbook='GetDeviceList.yml', limit=r_limit, inventory="SITE1")
```

When doing this, Ansible runner would create a file called `/home/cumulus/ansible-runner-api/tmp/inventory/hosts` rather than looking for a file named `SITE1` to read in. Based on the documentation within the code, the `inventory=` function should do the following:

```
    :param inventory: Overridees the inventory directory/file (supplied at *private_data_dir/inventory*) with
                      a specific host or list of hosts. This can take the form of
      - Path to the inventory file in the *private_data_dir*
      - Native python dict supporting the YAML/json inventory structure
      - A text INI formatted string
      - A list of inventory sources, or an empty list to disable passing inventory
```

The behaviour of the function is in direct conflict with the first bullet point:
```
      - Path to the inventory file in the *private_data_dir*
```

The expected behaviour should be that the string passed to the variable `inventory=` should be the location of the inventories files within the `private_data_dir`. Instead, what happens is that the string passed into the variable `inventory=` gets written to the file named `hosts`.

The problem is in the following code snippet:
```
ansible-runner/utils.py [185..192]
...
    obj = kwargs.get('inventory')
    if obj and isinventory(obj):
        path = os.path.join(private_data_dir, 'inventory')
        if isinstance(obj, Mapping):
            kwargs['inventory'] = dump_artifact(json.dumps(obj), path, 'hosts.json')
        elif isinstance(obj, string_types):
            if not os.path.exists(obj):
                kwargs['inventory'] = dump_artifact(obj, path, 'hosts')
...
```

The problem code is the last two conditionals. First, the `inventory=` variable is validated as a stringtype. This will succeed. Then, the entire variable input, which is only the string for the relative path of the inventory starting from `private_data_dir` is validated on whether the path exists. This will always fail. As such, to fix this code, the following fix is required:

```
    obj = kwargs.get('inventory')
    if obj and isinventory(obj):
        path = os.path.join(private_data_dir, 'inventory')
        if isinstance(obj, Mapping):
            kwargs['inventory'] = dump_artifact(json.dumps(obj), path, 'hosts.json')
        elif isinstance(obj, string_types):
            if not os.path.exists(os.path.join(path,obj)):
                kwargs['inventory'] = dump_artifact(obj, path, 'hosts')
            else:
                kwargs['inventory'] = os.path.join(path,obj)
```

Even this code is clunky because it assumes that the `inventory/` directory will be the only place where inventories can reside. Withing grossly rewriting the expectations of where the file will be located (and potentially affecting the first conditional action), the simple fix is an adjustment of the path check.

**Comment by Akasurde** [comment]
resolved_by_pr #1065

**Comment by JSchneidler** [comment]
Any update or temporary workaround for this?

EDIT: For anyone else, a good workaround is using an absolute path
