### ISSUE TITLE
Supporting resource profiling (perf stats) w/ ad hoc commands

### ISSUE THREAD

**Issue by jladdjr** [ansible/ansible-runner#356]
Requested here:
https://github.com/ansible/ansible-runner/pull/346#discussion_r326607874

**Comment by jladdjr** [comment]
@wenottingham - any thoughts on this? I remember (but can't find any reference to) some discussion about perf stats being limited to playbooks. Should there be support for perf stats w/ ad hoc commands in awx?

Even if this didn't get added to awx, don't see why we couldn't add this to runner. I _think_ the plugin should handle ad hoc commands just fine (but haven't looked into this yet).

**Comment by wenottingham** [comment]
I don't think it's needed for AWX (doesn't mean it can't be done, but I wouldn't prioritize it).

**Comment by matburt** [comment]
Merged
