### ISSUE TITLE
Update container image to use Python3 ahead of Python2 EOL

### ISSUE THREAD

**Issue by andyfeller** [ansible/ansible-runner#359]
With [Python 2 EOL preordained as Jan 1st, 2010](https://www.python.org/dev/peps/pep-0373/), the `ansible-runner` container image should be updated to default to Python 3.7 or newer in order to account for updates and security fixes.

```
 $ docker run -it ansible/ansible-runner /bin/bash
Unable to find image 'ansible/ansible-runner:latest' locally
latest: Pulling from ansible/ansible-runner
8ba884070f61: Pull complete 
1bdeea372afe: Pull complete 
6e8f41c17037: Pull complete 
b8e8e7e65ad4: Pull complete 
12b32c9014cb: Pull complete 
0fce3f600e4d: Pull complete 
1dbf32d34079: Pull complete 
1fe25d6ec836: Pull complete 
9ce71a28d1b2: Pull complete 
Digest: sha256:32881c17806f0ed0f5841414ec37cb0017dd94d4399423888a1b8adde7e1b0af
Status: Downloaded newer image for ansible/ansible-runner:latest

[root@6fb03e52b228 /]# python --version
Python 2.7.5
```

**Comment by matburt** [comment]
Ansible Runner version 2, which is the next major Runner release up on deck will drop python 2 support entirely so this will get taken care of with that.

**Comment by troowala** [comment]
Thanks , btw when is Ansible Runner version 2 expected ?

**Comment by kdelee** [comment]
@andyfeller devel is now future 2.0 and will be python3 only

**Comment by AlanCoding** [comment]
closing as resolved
