### ISSUE TITLE
Configurable Timeout?

### ISSUE THREAD

**Issue by MrMEEE** [ansible/ansible-runner#366]
Hi

I'm the maintainer of the AWX-RPM project, and we are seeing issues where the cleanup of ansible_runner doesn't work.. 

As a user mentions here: https://github.com/MrMEEE/awx-build/issues/163, this can be fixed by extending the wait in the _delete function..

Is this something that we could change to a configurable option?

Regards

Martin

**Comment by matburt** [comment]
sure!

**Comment by matburt** [comment]
I left this comment on #377:

We don't see this problem on the official AWX builds, so I'm wondering if it's something specific to their implementation.

I'd like to see more root cause done on it.

**Comment by matburt** [comment]
#374 seems like a dup? Since there is more information over there I'm going to close this one.
