### ISSUE TITLE
Does ansible_runner's playbook support string type?

### ISSUE THREAD

**Issue by yanyixing** [ansible/ansible-runner#369]
```
_inventory = """
[hello]
root@172.16.143.181
"""


_playbook = """
---
- hosts: hello
  gather_facts: false
  tasks:
  - name: "hello world"
    command: "echo 'hello world!'"
"""

r = ansible_runner.run(inventory=_inventory, playbook=_playbook)
```

Dose playbook support string type and playbook's content like above code？

**Comment by matburt** [comment]
Yes, see: https://ansible-runner.readthedocs.io/en/latest/source/ansible_runner.html#ansible_runner.interface.run

We can take a path, a string, or a dict representing the content.

**Comment by yanyixing** [comment]
@matburt but, as my demo code , it's not working, the ansible_runner says can't found the playbooks

**Comment by DarlingRoy** [comment]
I had the same trouble

**Comment by Peco602** [comment]
Did you find an alternative approach to this issue?

**Comment by gotounix** [comment]
> Yes, see: https://ansible-runner.readthedocs.io/en/latest/source/ansible_runner.html#ansible_runner.interface.run
> 
> We can take a path, a string, or a dict representing the content.

I test failed, it must be a file path, can't set to a string.
