### ISSUE TITLE
RPM signing key?

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible-runner#393]
From `#ansible-runner`
> is the repo for debian based distribs at releases.ansible.com/ansible-runner is still valid ? the public key is not verified on my part
> ive tried with the keys from releases.ansible.com/keys but that did not work either

Doesn't appear to be mentioned on https://ansible-runner.readthedocs.io/en/latest/install.html either

**Comment by shanemcd** [comment]
Issue title says RPM, description says Debian. Which is it?

**Comment by gundalow** [comment]
Debian, my mistake with title.
