### ISSUE TITLE
Unable to supply vault password via python interface

### ISSUE THREAD

**Issue by mjcramer** [ansible/ansible-runner#397]
I am writing a wrapper script to simplify ansible playbook execution for developers who need to do quick deployments. I thought I would use ansible-runner as it purports to be stable interface to ansible execution, however, I'm having some difficulties with some seemingly very simple things. First off, I have retrofitted my project to conform to the [Runner Input Directory Hierarchy](https://ansible-runner.readthedocs.io/en/latest/intro.html#inputdir). The location of this directory is what I pass as the `private_data_dir` to ansible runner and am trying to run a playbook that would normally look like this:

```bash
ansible-playbook project/monkify.yml -e '{"environment":"dev"}' --ask-vault-pass -i inventory/hosts
```

This invocation works; it prompts me for my vault password (included from said playbook) and happily executes its tasks. Now, when I programmatically invoke this from my Python wrapper, which looks like this:

```python
my_vars = {
  'environment': args.environment             ### args.environment = dev ###
}
r = ansible_runner.run(
        private_data_dir=f"{dirname(__file__)}", 
        playbook=f"{args.playbook}.yml",      ### args.playbook = monkify.yml
        extravars=my_vars
    )
```

and in my <private_data_dir>/env/cmdline I have
```
--ask-vault-pass
```

The process just hangs, presumably waiting for input. Nothing I type has any effect I have to ctl-c myself outta there. Any insight?

**Comment by matburt** [comment]
Runner specifically will not take input from stdin like this. You're probably looking for this: https://ansible-runner.readthedocs.io/en/latest/intro.html#env-passwords

**Comment by mjcramer** [comment]
Yep, I actually just figured this out earlier today. I had a bad regex for my prompt string and that's why it was not working. Thanks for the response!
