### ISSUE TITLE
How to supply an ansible.cfg to ansible runner?

### ISSUE THREAD

**Issue by mjcramer** [ansible/ansible-runner#398]
I would like to control some things like stdout plugins and other ansible playbook configurations but the documentation does not mention any way to provide an ansible.cfg to the invoked process. It definitely does not pick up the one I have in the <private_data_dir> and when I add 
```
ANSIBLE_CONFIG=./ansible.cfg
``` 
to `<private_data_dir>/env/envvars` it has no effect. Is there a documented way to do this?

**Comment by matburt** [comment]
Runner *should* ... probably start by making sure the env var is making it down to the Ansible process and that ansible is doing the right thing with the path given it's CWD.

**Comment by eskultety** [comment]
> Runner _should_ ... probably start by making sure the env var is making it down to the Ansible process and that ansible is doing the right thing with the path given it's CWD.

@matburt, you say the runner _should_ propagate the environment variable, but 1.5 years later, this still doesn't work and it's undocumented how `ansible.cfg` is supposed to work with ansible-runner. Just to demonstrate the problem, I have a VM to which I can SSH as both _root_ and _test_ (_test_ being the default). Now, this is what my environment looks like:

ansible.cfg
```
[defaults]
host_key_checking = False
remote_user = root
become = False
```

private_data_dir:
```
ansible-runner-tmp/
├── ansible.cfg
├── env
│   └── envvars
├── inventory
│   └── inventory
└── project
    └── test.yml
```
envvars
```
---
ANSIBLE_CONFIG:/home/eskultety/ansible-runner-tmp/ansible.cfg
```

test.yml
```
---
- hosts: all
  tasks:
    - command: whoami
      register: username

    - debug:
        msg: "{{ username.stdout }}"
```

When I invoke ansible-playbook as `ANSIBLE_CONFIG=ansible.cfg ansible-playbook -i inventory project/test.yml` from private_data_dir, this is the output:
```
TASK [debug] **********************************************************************************
ok: [centos-7] => {
    "msg": "root"
}
```

However, if I try to do the same with ansible-runner, it won't pick up the config - `ansible-runner -p test.yml run .`:
```
TASK [debug] *******************************************************************
ok: [centos-7] => {
    "msg": "test"
}
```

For the record, even if I added `ANSIBLE_CONFIG` to the runner command line just like I did with `ansible-playbook`, nothing would change in the output, so my question is, **how** is ansible-runner supposed to work with `ansible.cfg`?

**Comment by eskultety** [comment]
> envvars
> 
> ```
> ---
> ANSIBLE_CONFIG:/home/eskultety/ansible-runner-tmp/ansible.cfg
> ```

All good now, I found the problem - there must be a space after the colon, otherwise it's interpreted as a scalar rather than a key:value pair by YAML

**Comment by Nomanpour** [comment]
Hi,
I have same problem, I tried anything without any success
my envvars:
```
---
ANSIBLE_CONFIG: /home/veria/ansible-runner/ansible.cfg
```

ansible.cfg:
```
[defaults]
stdout_callback = community.general.unixy
````

**Comment by mwhahaha** [comment]
So it should be noted that some configuration items are actually overwritten by ansible runner's config. stdout callback is one of those.  Fact caching path is another as the env vars seem to take priority over the ansible.cfg when being run.

You can work around this by setting the runner config env var prior to invoking run.

```
          env = {}
          env["ANSIBLE_CONFIG"] = cfg_path 
          runner_opts = {
              "private_data_dir": working_dir,
              "project_dir": working_dir,
              "playbook": playbook_path,
              "envvars": env,
          }                                                                       
          if inventory_path:                                                      
              runner_opts["inventory"] = inventory_path
          runner_config = ansible_runner.runner_config.RunnerConfig(**runner_opts)
          runner_config.prepare()
          runner_config.env["ANSIBLE_STDOUT_CALLBACK"] = "dense"
          # By default ansible-runner forces a per-execution fact cache but we 
          # want to share fact caches between our tasks.
          runner_config.env["ANSIBLE_CACHE_PLUGIN_CONNECTION"] = "~/.ansible/fact_cache"
          runner = ansible_runner.Runner(config=runner_config)
          status, rc = runner.run()
```

**Comment by gm0neyl0ve** [comment]
@mwhahaha  Thanks for this!

**Comment by ashpool37** [comment]
Another thing to mention since this issue pops up when searching for "ansible-runner ansible.cfg".

`ansible-runner` changes the working directory before launching `ansible`, setting it to the `project` directory inside the input directory hierarchy by default. Put `ansible.cfg` inside `project`, not in the root of the hierarchy, and you shouldn't need to set any extra variables: `ansible` will just pick it up.
