### ISSUE TITLE
Expand logging so data can be useful as direct container console output

### ISSUE THREAD

**Issue by matburt** [ansible/ansible-runner#4]

**Comment by matburt** [comment]
for example, setting a flag to output json instead of the standard console output.

**Comment by Ladas** [comment]
@matburt so this would respect ```stdout_callback = json```, I have in my ```~/.ansible.cfg``` ?

**Comment by matburt** [comment]
in this case ideally you wouldn't need that... our callback wrapper will emit our events to json without you needing to invoke the json output callback at all.

**Comment by matburt** [comment]
Added support in #76

**Comment by Ladas** [comment]
@matburt looks like there are few stdout prints breaking the json, e.g. I am now getting

```
*** JSON::ParserError Exception: 765: unexpected token at 'Not loading passwords
Not loading settings
Not loading ssh key
```

**Comment by Ladas** [comment]
tracking the new issue in https://github.com/ansible/ansible-runner/issues/89
