### ISSUE TITLE
Error loading key - invalid format

### ISSUE THREAD

**Issue by jfmrm** [ansible/ansible-runner#408]
on first execution of ansible_runner.run() it raises this error:
`Error loading key "{PATH_TO_PRIVATE_DATA_DIR}/artifacts/4957aac2-2bb5-4188-b02c-717da5cbf043/ssh_key_data": invalid format`

on following executions everything works ok.

**Comment by AlanCoding** [comment]
Could you give more details about your private data dir so someone can try to reproduce? thanks

**Comment by jfmrm** [comment]
Hi Alan, there is so long that I don't touch this that I really can't remember any more details anymore. I exited the company that I was working on this. Sorry I can't give further details

**Comment by AlanCoding** [comment]
Our bad for leaving it hanging, I'm just trying to clean house.
