### ISSUE TITLE
How to control verbosity from python

### ISSUE THREAD

**Issue by cdvv7788** [ansible/ansible-runner#41]
I tried the latest HEAD and I am getting the following with the demo (with the python commands in the readme):

![image](https://user-images.githubusercontent.com/5531776/40620923-4bfebb52-6260-11e8-887e-70e021140be3.png)

I would like to see the full traceback.
As a sidenote, I have psutil installed:
![image](https://user-images.githubusercontent.com/5531776/40621024-be520b96-6260-11e8-8df2-f81c1460ae6b.png)
And can even run commands with it:
![image](https://user-images.githubusercontent.com/5531776/40621039-d99bc6e4-6260-11e8-9da1-45d50250f506.png)

**Comment by privateip** [comment]
@cdvv7788 this is similar to #40   Now that we have #32 and #35 merged I'm going to expose the logging capability to `ansible-runner` via command line options so you can control how verbose you want logging to be.

/cc @matburt

**Comment by privateip** [comment]
I was thinking some about how to best cover the use cases here and wanted to get feedback on a proposal.  Essentially we need to control two things: 1) the verbosity output of Ansible and 2) the verbosity output of ansible-runner.

I have come up with the following command line options for ansible-runner and wanted to solicit feedback before I implemented them.  All arguments would also be configurable via RunnerConfig such that they are exposed at an API layer as well.

```
-vvvvv (up to 5 Vs) 
will control the verbosity of output from ansible-runner and also pass the same switch to ansible-playbook.  this effectively mirros ansible into ansible-runner.  Also configurable as env var RUNNER_VERBOSITY 1..5

--logfile <path> 
will specify the log file to generate from the run. If the path argument is relative, it will relative to the ansible-runner data dir. Also configurable as RUNNER_LOGFILE <path>

--quiet
Suppress all output coming from ansible-runner or ansible-playbook   Also configurable as RUNNER_QUIET=[0 or 1]

```

Default implementation would be as it exists today.  This proposal ignores being able to enable ansible-playbook debug and logging from the command line and assumes if those features are needed, they could be  enabled via envvars using `ANSIBLE_DEBUG` and `ANSIBLE_LOG_PATH`

Looking for thoughts, ideas, agreement, disagreement, alternatives with the proposed implementation.

/cc @matburt 
/cc @cdvv7788 
/cc @rcarrillocruz 
/cc @radez 




```
