### ISSUE TITLE
Stdout hidden when using `env/passwords`

### ISSUE THREAD

**Issue by glothriel** [ansible/ansible-runner#421]
Ansible runner seems to:
* stop displaying stdout
* stop sending events except status events

When there is `env/passwords` file present.

#### Ansible:
```
ansible 2.7.12
  config file = None
  configured module search path = ['/runner/.ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /venv/lib/python3.7/site-packages/ansible
  executable location = /venv/bin/ansible
  python version = 3.7.5 (default, Oct 17 2019, 12:25:15) [GCC 8.3.0]

```
#### Runner: 
`1.4.4`

I'm using ansible inside docker image, alpine 3.10.

**Comment by AlanCoding** [comment]
I think I need a more concrete test case for this, what prompts flags did you send (like `--ask-pass`) to `ansible-playbook` and what regex dictionary do you have in env/passwords?

**Comment by shanemcd** [comment]
Closing due to lack of response.
