### ISSUE TITLE
Install python-netaddr in docker

### ISSUE THREAD

**Issue by jamielennox** [ansible/ansible-runner#427]
Hi, 

I know there's a neverending list of dependencies for different modules out there, however it'd be good to ship a few basic dependencies for common modules, particularly that are required for core modules. 

In my case I need netaddr for any of the IP manipulation filters, but there are probably others i haven't hit yet. 

An easy fix, but i'll leave it as a ticket for now as i'm not sure what you want in yum vs pip. 

Thanks.

**Comment by jamielennox** [comment]
For completeness the things I ended up needing were `netaddr`, `pywinrm` and `requests`. I get that this could be never ending but these seem pretty core.

**Comment by matburt** [comment]
For what's it worth, you can (and it's expected) to layer anything extra that you need on top of this image.

**Comment by matburt** [comment]
See https://github.com/ansible/ansible-runner/pull/428
