### ISSUE TITLE
callback plugin broken for older versions of anisble

### ISSUE THREAD

**Issue by kdelee** [ansible/ansible-runner#435]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Running jobs w/ virtual environments in awx using older ansible versions is broken.
Symptom that tests are picking up is no `runner_on_*` events.

If you look at the stdout of the jobs run in environments using ansible 2.7.15, 2.6.1, 2.5.6, 2.4.6, or 2.3.3 (probably others), you see

```
[WARNING]: Failure using method (v2_runner_on_ok) in callback plugin
(<ansible.plugins.callback.awx_display.CallbackModule 
```

![image](https://user-images.githubusercontent.com/29239279/77662115-d6807b80-6f51-11ea-9d84-bc91f5891175.png)

**Comment by ryanpetrello** [comment]
Looking at this now, was introduced by: https://github.com/ansible/ansible-runner/pull/405

**Comment by ryanpetrello** [comment]
This is why it's broken in older Ansible versions: https://github.com/ansible/ansible-runner/pull/405/files#r398654057
