### ISSUE TITLE
Can run() be configured to use absolute path such as  "/usr/local/bin/ansible"?

### ISSUE THREAD

**Issue by Fierozen** [ansible/ansible-runner#439]
Can such I pass in an absolute executable location in "binary=/usr/local/bin/ansible" or do the same thing any other way?

**Comment by S1lverhead** [comment]
Hi,
I set PATH:
      os.environ["PATH"] = "%s/venv/bin" % cwd + os.pathsep + os.environ["PATH"]
and check if there is ansible:
        self.ansible = shutil.which(ansible_name)
        if self.ansible is None:
            raise exception(self.logger)
you can improve my check if path contains "/usr/local"
with this approach, correct (version) of ansible is executed, in my case ansible in venv.

hope it helps, Jan

**Comment by AlanCoding** [comment]
The binary option was implemented some time ago https://github.com/ansible/ansible-runner/pull/124

There's another report about issues with using that https://github.com/ansible/ansible-runner/issues/464, but I don't see anything that this contributes which isn't covered elsewhere so I will go ahead and close.
