### ISSUE TITLE
Hard coding the version of pexpect causes issues with co-installability

### ISSUE THREAD

**Issue by prometheanfire** [ansible/ansible-runner#44]
pexpect is hard coded to only work with 4.5.0 in setup.py  This causes issues with co-installability.

**Comment by prometheanfire** [comment]
see http://logs.openstack.org/85/571385/3/check/requirements-tox-py27-check-uc/0e22b87/job-output.txt.gz#_2018-06-02_06_45_29_000244 for more details

**Comment by matburt** [comment]
That is an interesting detail, I do think I'd like to remove that overall requirement.

**Comment by matburt** [comment]
Fixed: https://github.com/ansible/ansible-runner/commit/29c09c501103124765c18140b58ada9e1a05c2cf

**Comment by prometheanfire** [comment]
thanks, when do you think the next release will be?

**Comment by matburt** [comment]
I need to try to wrap up some feature development from cards listed in the issue queue. Possibly within a week or two.

**Comment by prometheanfire** [comment]
here's your two week reminder :P

**Comment by matburt** [comment]
Thanks!  Still waiting on a handful of PRs to wrap up. I'm thinking release mon-tues of next week.
