### ISSUE TITLE
Ansible-runner + ansible-runner-http 

### ISSUE THREAD

**Issue by dcasasok** [ansible/ansible-runner#442]
Hi, i'm trying integrate both ansible-runner and ansible-runner-http plugin.

First of all,  In my main code i use the event_handler function because i want to get all events data. This works only using ansible-runner without plugin configure.

Then i downloaded ansible-runner-http plugin to send events data to a URL with post requests. But when i configure it (on the env/settings) and test it, ansible-runner only send the post request and in the event handler i can't see/use that event. In fact, when ansible-runner execute the test playbook it creates the identifier directory of the invocation, but that file is empty. 

The URL isn't an endpoint, it doesn't respond any requests.

So, what's happening with the events data? Should i use another URL?

**Comment by matburt** [comment]
> The URL isn't an endpoint, it doesn't respond any requests.

I'm not sure I understand what you mean by this? RUNNER_HTTP_URL should equal some full url to the resource you want to post to.

**Comment by dcasasok** [comment]
Hi! Yes, that's ok.  But the problem is the event handler function.Ansible runner doesn't call it when i configure the ansible-runner-http.

Example of event handler function usage:

def event_handler(event):
     print('**event handler**')
     print(event)

r = ansible_runner.run(json_mode=True,private_data_dir= 'xxxxxx', playbook ='test.yaml', event_handler=event_handler)

No event data is printed, so i suppose event_handler function is not executed.
