### ISSUE TITLE
Please update the release on Docker Hub

### ISSUE THREAD

**Issue by svenstaro** [ansible/ansible-runner#449]
Hey, the current release on Docker Hub is still based on CentOS 7 which uses Python 2 and is therefore EOL. A CentOS 8 based build would be nice since it uses Python 3. Current master would do nicely.

**Comment by DjangoCalendar** [comment]
@matburt
Would you be able to help ?

**Comment by Throckmortra** [comment]
is this project dead?

**Comment by matburt** [comment]
I've updated those images... this was just an oversight on my part.
