### ISSUE TITLE
Add ansible-lint ?

### ISSUE THREAD

**Issue by bufferoverflow** [ansible/ansible-runner#456]
Would be very nice to have [ansible-lint](https://github.com/ansible/ansible-lint) also within the ansible-runner docker image.

**Comment by AlanCoding** [comment]
The image should be lightweight and I don't really agree. Starting with Ansible 2.10, the container will use `ansible-base` by default which ships without the content. So in any realistic case, users will be building execution environments _on top of_ that image, in which case you should add Ansible testing and debugging packages in your own layers.

See https://ansible-builder.readthedocs.io/en/latest/ for some more about what's in the works.
