### ISSUE TITLE
Allow setting extra vars as a direct input

### ISSUE THREAD

**Issue by matburt** [ansible/ansible-runner#46]

**Comment by Ladas** [comment]
@matburt this is probably a last blocker for us, anything I can do to help?

**Comment by djzager** [comment]
@Ladas https://github.com/ansible/ansible-runner/pull/70 seems related to this

**Comment by djzager** [comment]
To add a little more context to that comment, I was able to make use of `env/cmdline` to supply the extra-vars in our entrypoint script -- https://github.com/djzager/apb-base/blob/runner3/files/usr/bin/entrypoint.sh#L55

**Comment by Ladas** [comment]
@djzager thank you that could theoretically work. This issue was about that we want to pass extra vars as an argument, so we don't have to store it into the filesystem.

**Comment by matburt** [comment]
This is high on my list of items to tackle for the next release as a direct argument to `ansible-runner` for the next release. In the meantime will `--cmdline` work for you for adding extra vars?

**Comment by Ladas** [comment]
@matburt I am gonna try it today/early next week and let you know. We have a public holiday this Thursday and Friday.

**Comment by Ladas** [comment]
@matburt ok, it seems like the --cmdline is usable, I can do ```--cmdline "--extra-vars '{...}'"```

Thought calling this, the ```private_data_dir/env/cmdline``` is being created for me. I suppose that is ok for now. Or how hard is to not dropping it into the filesystem?

**Comment by matburt** [comment]
I might not be understanding what you are asking... are you asking of whether to use the file-system based extra vars vs the `cmdline` override?

Both will be supported... the filesystem implementation will probably be more preferrable and will be stable long term.

**Comment by Ladas** [comment]
@matburt ah, what I am saying is that I have it working now. :-)

The note meant, that when I use --cmdline override, it actually writes the passed content into the filesystem. So it's probably the same code path, right? And it modifies existing env/cmdline file. For me it's not an issue (I create unique private_data_dir for every run), but I guess it can be confusing for some people? Should I start another issue for it, or is that expected?

**Comment by dch** [comment]
> This issue was about that we want to pass extra vars as an argument, so we don't have to store it into the filesystem.

Was the intent that extra vars never touch the filesystem? In my use case I have some sensitive stuff that I'd like to pass in, already in python dict format, and its not necessary (nor desired) to re-serialise it out to disk.

I can open a new issue if this one isn't appropriate.

**Comment by Ladas** [comment]
@dch yeah, ideally it would not touch filesystem, so new issue might be good. 

Btw. we use env vars for the secrets, since that is the safest option anyway.

**Comment by MrHant** [comment]
Latest version of ansible-runner now supports passing argument `extravars`.

**Comment by matburt** [comment]
ah indeed, I'll close this

**Comment by christmoore** [comment]
Is extravars available from the command-line? Or are we expected to use --cmdline?
