### ISSUE TITLE
Ansible Runner in Docker container can't process mounted password file

### ISSUE THREAD

**Issue by OptiMous28** [ansible/ansible-runner#460]
I'm currently using the ansible-runner docker image to run a container which will mount a directory, use ansible-vault to encrypt some files then terminate the container. Inside the volume mount is the ansible-vault password file.

Docker compose file:
`version: "3.3"
services:
  ansible:
    image: ansible/ansible-runner:1.4.6
    container_name: ansible
    restart: "no"
    volumes:
      - ../.:/runner/app/
    working_dir: /runner/app/`

Docker command:
`docker-compose -f docker/ansible/docker-compose.ansible.yaml run --rm ansible bash -c "ansible-vault encrypt --vault-password-file PATH_TO_PASSWORD FILENAME"`

When i run the above command to encrypt a file, the error i get is:
`Processing dev/env.dev...
[WARNING]: Error in vault password file loading (default): Problem running vault password script /runner/app/ansible/ansible-vault-password.txt ([Errno 8] Exec format error: '/runner/app/ansible/ansible-vault-password.txt'). If this is not a script, remove the executable bit from the file.       
ERROR! Problem running vault password script /runner/app/ansible/ansible-vault-password.txt ([Errno 8] Exec format error: '/runner/app/ansible/ansible-vault-password.txt'). If this is not a script, remove the executable bit from the file.`

Ansible Vault Password File Details:
`-rwxr-xr-x 1 root root 20 Jun  3 16:38 /runner/app/ansible/ansible-vault-password.txt`

I tried changing the file to no longer being executable but it just wouldn't change. I used chmod 600 FILENAME.

**Comment by OptiMous28** [comment]
Just to add, the password file on my local machine has the permission:
`-rw-r--r-- 1 Mous 197121  20 Jun  3 17:38 ansible-vault-password.txt`

**Comment by OptiMous28** [comment]
I just tested this on my Macbook Pro and it worked fine, no issues. Issue seems to only happen when using Docker on Windows 10.

**Comment by matburt** [comment]
Maybe this is just a limitation of the shell for win10? Ansible bases a lot of what it does around certain file types and the executable bit... if it's set then it will treat it a different way.
