### ISSUE TITLE
Remove Dependency on psutil

### ISSUE THREAD

**Issue by matburt** [ansible/ansible-runner#466]
We depend on psutil for one reason, to handle ansible termination:

https://github.com/ansible/ansible-runner/blob/2505afdcc152fab54d416144b9d0a05d083e8256/ansible_runner/runner.py#L394

This is a pretty heavy dependency and I'd like to remove it either by investigating a more reliable way to signal Ansible to exit or finding a lighter weight mechanism that doesn't have a direct C library dependency. Whatever replacement strategy is found needs to support the same sort of behavior we have today which is aggressive.

**Comment by ryanpetrello** [comment]
<img src="https://media1.tenor.com/images/a4d18ffe91a44757e8da9dd73330f4a8/tenor.gif?itemid=7633730" />

**Comment by AlanCoding** [comment]
This is also used in the callback plugin.

https://github.com/ansible/ansible-runner/blob/983f2fa66f612757975e48467d05b90b11e09851/ansible_runner/display_callback/cleanup.py#L35

I'm not entirely clear on the reasons why.

**Comment by AlanCoding** [comment]
Also should document:

https://github.com/ansible/ansible-runner/blob/49d4c9b68f62a006ff43f58c97ab455c15356b43/Dockerfile#L8

It seems that psutil is the reason that the _system_ package `python3-devel` is needed. So if someone removes psutil, remove this too.

**Comment by AlanCoding** [comment]
Also link https://github.com/ansible/ansible/pull/70667

**Comment by wenottingham** [comment]
See: https://github.com/ansible/ansible-runner/pull/555
