### ISSUE TITLE
Need stable 1.4.x branch and convert devel into future 2.0

### ISSUE THREAD

**Issue by kdelee** [ansible/ansible-runner#468]
The 1.4.z line has been out for a while and plenty of people use it.
There is allready a stable-1.3 branch https://github.com/ansible/ansible-runner/tree/stable/1.3.x

We should have  a stable branch for releasing bug fix release versions of 1.4.z

Then we should make devel version read as 2.0.0

@maxamillion @matburt @shanemcd any objection.

I would do it but not 100% sure where to branch off stable-1.4. Guess I could just go back to when it was released

**Comment by maxamillion** [comment]
No objection here. :+1:

**Comment by kdelee** [comment]
ok followed pattern of existing `stable/1.3.x` branch and made https://github.com/ansible/ansible-runner/tree/stable/1.4.x

**Comment by kdelee** [comment]
made PR to bump devel version https://github.com/ansible/ansible-runner/pull/471

**Comment by kdelee** [comment]
this is now done
