### ISSUE TITLE
take second look at zuul preperation steps

### ISSUE THREAD

**Issue by kdelee** [ansible/ansible-runner#469]
It takes ~ 8 min for zuul to get ready to start thinking about running the tests.

For total runtime of ~15 min only 5 min are in tests.

Is there anything we can do to cut that down? Can we build a test runner image to then re-use so we don't have to do things every time like installl pip3?

https://b1544500d9b6b1c86d6d-1f0fc8612f477b73e943c6b5fc30775f.ssl.cf2.rackcdn.com/467/aeabfda410998c033ea005833949a18bcca1f52b/check/ansible-tox-py37/8e3a53d/job-output.txt

@Spredzy if you can provide guidance where we can review the zuul set up and if we can optimize what pre and post steps are performed, would be much appreciated

@jladdjr and I were looking at this

**Comment by Akasurde** [comment]
Closing this as we no longer use zuul. Thanks.
