### ISSUE TITLE
module (command) is missing interpreter line

### ISSUE THREAD

**Issue by S1lverhead** [ansible/ansible-runner#474]
Hi,
I try to use shell or command in my playbooks, simplified version:
---
  - hosts: localhost
    tasks:
      - name: get script
        get_url:
          url: "https://bootstrap.pypa.io/get-pip.py"
          dest: "/tmp/get-pip.py"
          mode: "755"

      - name: "BUGFIX update pip3"
        shell:  "python3 /tmp/get-pip.py --root=/ --force-reinstall"

It fails with error:
    "msg": "module (command) is missing interpreter line"
few lines above in the output I see:
Using module file /Users/janmalanik/build/vps_manager/artifacts/8126776a-ad1a-467a-bdfa-5863c8d9437b/command
which contains common things:
_{"command": ["ansible-playbook", "-i", "/Users/janmalanik/build/vps_manager/inventory/hosts", "-e", "@/Users/janmalanik/build/vps_manager/env/extravars", "-e", "{\"runtime\":{'remove_volumes': 'no', 'remove_orphans': 'no', 'deployment_domain': 'xxx', 'ansible_connection': 'ssh', 'ansible_user': 'root', 'ansible_python_interpreter': <truncated>_....

I tested it with ansible-runner 1.4.6 as same as git 601649d

ansible-playbook --version: 2.8.12
Flavor: Centos 7 && MacOS Catallyna

Here is ansible configuration:

ansible-playbook 2.8.12
  config file = /Users/janmalanik/build/vps_manager/project/ansible.cfg
  configured module search path = ['/Users/janmalanik/build/vps_manager']
  ansible python module location = /Users/janmalanik/build/vps_manager/venv/lib/python3.7/site-packages/ansible
  executable location = /Users/janmalanik/build/vps_manager/venv/bin/ansible-playbook
  python version = 3.7.3 (default, Mar  6 2020, 22:34:30) [Clang 11.0.3 (clang-1103.0.32.29)]
Using /Users/janmalanik/build/vps_manager/project/ansible.cfg as config file

if you need more info, please let me know

thank you, Jan

**Comment by S1lverhead** [comment]
I found this bug:
https://github.com/ansible/ansible/issues/40561
comment "bcoca commented on 28 Feb 2019" seems to be confirmation that for some reason it tries to use command file as a "command"

**Comment by AlanCoding** [comment]
This looks like an issue with Ansible itself, and I see you have linked an issue in their issue queue. Given that this is related to how parameters are passed to the module, it seems safe to close it in the ansible-runner issue queue.
