### ISSUE TITLE
Multiple playbooks

### ISSUE THREAD

**Issue by Zempashi** [ansible/ansible-runner#475]
We can read in the documentation that we can pass playbooks as a list or as a string: https://ansible-runner.readthedocs.io/en/latest/source/ansible_runner.html#ansible_runner.interface.run  (playbook argument)

but passing a list results in 
```
ERROR! playbook entries must be either a valid play or an include statement
```
Passing two playbooks in the same string (with space separator: 'playbook-01.yml playbook-02.yml' will result in
```
 ERROR! the playbook: playbook-01.yml playbook-02.yml could not be found
```

Is there a special way to pass multiple playbooks ?

Ansible runner v1.4.6

**Comment by AlanCoding** [comment]
See usage in this test:

https://github.com/ansible/ansible-runner/blob/ccbc3af7d3b1d7c99a2f5fbb0def0ffc365d3066/test/integration/test___main__.py#L74

It is murky to me if `ansible-playbook` will take a list of playbooks:

```
usage: ansible-playbook [-h] [--version] [-v] [-k]
                        [--private-key PRIVATE_KEY_FILE] [-u REMOTE_USER]
                        [-c CONNECTION] [-T TIMEOUT]
                        [--ssh-common-args SSH_COMMON_ARGS]
                        [--sftp-extra-args SFTP_EXTRA_ARGS]
                        [--scp-extra-args SCP_EXTRA_ARGS]
                        [--ssh-extra-args SSH_EXTRA_ARGS] [--force-handlers]
                        [--flush-cache] [-b] [--become-method BECOME_METHOD]
                        [--become-user BECOME_USER] [-K] [-t TAGS]
                        [--skip-tags SKIP_TAGS] [-C] [--syntax-check] [-D]
                        [-i INVENTORY] [--list-hosts] [-l SUBSET]
                        [-e EXTRA_VARS] [--vault-id VAULT_IDS]
                        [--ask-vault-password | --vault-password-file VAULT_PASSWORD_FILES]
                        [-f FORKS] [-M MODULE_PATH] [--list-tasks]
                        [--list-tags] [--step] [--start-at-task START_AT_TASK]
                        playbook [playbook ...]
```

But if it does take multiple playbooks, it seems like that may be a problem with this "interface" use case of passing a dictionary to be interpreted as playbooks.

For now, I'm closing as won't-fix.

**Comment by chilicheech** [comment]
it would be really awesome for the runner to accept a list of playbook paths, just like `ansible-playbook` does.
