### ISSUE TITLE
Pass through ansible return code

### ISSUE THREAD

**Issue by matburt** [ansible/ansible-runner#48]
Currently we store the ansible return code as the `rc` file in the artifacts dir. We should extend this for the `run` command in a similar way to what we do for the role executor here: https://github.com/ansible/ansible-runner/blob/master/ansible_runner/__main__.py#L161

**Comment by AlanCoding** [comment]
I think we do?

https://github.com/ansible/ansible-runner/blob/b21d3a12269cfcbbbbcc6f3e8821ad723678ad02/test/integration/test_interface.py#L90

the python use pattern is

```python
res = run(...)
print(res.rc)
```
