### ISSUE TITLE
Add docker, podman deps to test instances

### ISSUE THREAD

**Issue by jladdjr** [ansible/ansible-runner#480]
c.f. https://github.com/ansible/ansible-runner/pull/470

The PR that adds support for running ansible tasks inside of a container includes some [sanity checks](https://github.com/ansible/ansible-runner/pull/470/files#diff-c03f28564fbfeef64bd1f920fc8c49b1R26-R35) to ensure that container-based execution is successful. In order to run these tests, the test instance will need to be updated to include podman and docker.

While the podman / docker deps are required, we won't need to actually build the container image as part of the test runs, assuming that we contain to have an `ansible/ansible-runner` available in dockerhub; when podman / docker `run`'s, it pulls the container image.

cc @kdelee @shanemcd @matburt 

---

I'm not actually sure where our instances are located, if they're containerized, etc. Here's what I was able to find out by looking through our zuul config:

ansible-runner's [zuul project](https://github.com/ansible/project-config/blob/master/zuul.d/projects.yaml#L681)
.. uses the ansible-python3-jobs [template](https://github.com/ansible/project-config/blob/master/zuul.d/projects.yaml#L686)
.. which in turn calls [two jobs](https://github.com/ansible/ansible-zuul-jobs/blob/master/zuul.d/project-templates.yaml#L27-L32), `ansible-tox-py36` and `ansible-tox-py36`
.. based on the [definitions for those jobs](https://github.com/ansible/ansible-zuul-jobs/blob/master/zuul.d/jobs.yaml#L64-L72),
 .. `ansible-tox-py36` uses the `centos-8-1vcpu` nodeset
.. while `ansible-tox-py37` uses the `fedora-latest-1vcpu` nodeset
.. the definitions for those nodesets, respectively, are [here](https://github.com/ansible/ansible-zuul-jobs/blob/master/zuul.d/nodesets.yaml#L14-L18) and [here](https://github.com/ansible/ansible-zuul-jobs/blob/master/zuul.d/nodesets.yaml#L20-L24)

Here's what the nodesets look like:
![image](https://user-images.githubusercontent.com/4440360/86986047-89629700-c147-11ea-9462-5f47f834c1ea.png)

The nodeset definitions are kind of the end-of-the-line for me; I'm not actually sure where `centos-8-1vcpu` and `fedora-latest-1vcpu` live or how we'd go about updating them.

**Comment by jladdjr** [comment]
@pabelanger - would you be able to help us with this? @shanemcd mentioned that we may need to add docker and podman to https://github.com/ansible/ansible-zuul-jobs/blob/master/bindep.txt.

**Comment by AlanCoding** [comment]
^ Oh, I already did that. Integration tests are running, but a lot of stuff is broken.

> While the podman / docker deps are required, we won't need to actually build the container image as part of the test runs, assuming that we contain to have an ansible/ansible-runner available in dockerhub; when podman / docker run's, it pulls the container image.

Yeah, if the image was maintained separately, but it's not. To change the definition for the image, you have to make commits to ansible-runner source. A lot of stuff didn't work together because, but no one knew that because the dockerhub image wasn't being built.

**Comment by AlanCoding** [comment]
going to close because I think the main objective has been accomplished
