### ISSUE TITLE
Add git in Dockerfile (it was removed by mistake IMO)

### ISSUE THREAD

**Issue by otodorov** [ansible/ansible-runner#483]
Hello guys,
can you please add `git` into Dockerfile, so `ansible-galaxy` can work properly. 

Adding `git` to Dockerfile was introduced in version [1.3.1](https://ansible-runner.readthedocs.io/en/latest/install.html?highlight=git#id10), but a couple of versions after that you made [Refactor Dockerfile](https://github.com/ansible/ansible-runner/commit/56f14a3ee15826147809d219b1090d1017776d06) where you remove it.

**Comment by AlanCoding** [comment]
https://github.com/ansible/ansible-runner/blob/2133743a8dfaef23440d3de6b8fc629decc246f4/Dockerfile#L13
