### ISSUE TITLE
Support SSH key certs

### ISSUE THREAD

**Issue by jkohen** [ansible/ansible-runner#488]
SSH cert pairs require passing both the private key and the public cert to `ssh-add`; the private key doesn't seem to be sufficient. `ssh-add` imposes an additional requirement that the public cert file name looks like `<private_key_filename>-cert.pub`.

Ansible-runner doesn't support this use case, even though it supports passing a private key to Ansible in the `env/ssh_key` file. Is it possible to add an `env/ssh_key-cert.pub` file as well?

Others have worked this around: https://github.com/ansible/awx/pull/4320

**Comment by AlanCoding** [comment]
closing as duplicate as https://github.com/ansible/ansible-runner/issues/51, correct me if there's any nuance that needs another issue to track
