### ISSUE TITLE
ansible-runner 1.4.6 版本是否不支持centos6？

### ISSUE THREAD

**Issue by cuiliang0302** [ansible/ansible-runner#500]
运行报错信息：ERROR! Unexpected Exception, this is probably a bug: No module named psutil
to see the full traceback, use -vvv
failed: 250
verbose
verbose
Final status:
None

os版本：CentOS release 6.10 (Final)
python版本：Python 2.7.18和Python 3.6.12测试同样报错
ansible-runner 1.4.6  
psutil         5.7.2 

使用centos7就可以正常运行

**Comment by cuiliang0302** [comment]
运行的是实例程序
import ansible_runner
r = ansible_runner.run(private_data_dir='/tmp/demo', host_pattern='localhost', module='shell', module_args='whoami')
print("{}: {}".format(r.status, r.rc))
# successful: 0
for each_host_event in r.events:
    print(each_host_event['event'])
print("Final status:")
print(r.stats)

**Comment by matburt** [comment]
This usually happens when you don't have psutil installed into the outer environment where it's needed in order to track the ansible process.

**Comment by ctrlxx** [comment]
这个需要看你的ansible是通过python2还是python3安装的，如果跨版本调用的话，两个Python版本都需要装上psutil
