### ISSUE TITLE
RunnerConfig did not generate 'command' property correctly

### ISSUE THREAD

**Issue by xtay573269555** [ansible/ansible-runner#515]
I executed the following code and got a error:  AttributeError: 'RunnerConfig' object has no attribute 'command'

```
#!/usr/local/bin/python3
# -*- coding: utf-8 -*-

import os
import ansible_runner

def collect():
    os.environ["PATH"] = os.environ["PATH"] + ":/usr/local/python3/bin"
    print(os.environ["PATH"])
    rc = ansible_runner.RunnerConfig(
                 private_data_dir='/root/.ansible',
                 inventory='/tmp',
                 project_dir=None,
                 artifact_dir=None,
                 roles_path=None,
                 playbook='monitor.yml',
                 binary=None,
                 tags=None,
                 skip_tags=None,
                 ssh_key=None,
                 forks=None,
                 cmdline=None,
                 envvars=None)
    runner = ansible_runner.Runner(config=rc)
    r = runner.run()
    print("{}: {}".format(r.status, r.rc))
    print("Final status:")
    print(r.stats)
    pass

if __name__ == '__main__':
    collect()
```

The detail error  : 
```
Traceback (most recent call last):
  File "/opt/jupyter_notedir/parse_datafile/demo.py", line 35, in <module>
    collect()
  File "/opt/jupyter_notedir/parse_datafile/demo.py", line 28, in collect
    r = runner.run()
  File "/usr/local/python3/lib/python3.6/site-packages/ansible_runner/runner.py", line 114, in run
    command = self.config.command
AttributeError: 'RunnerConfig' object has no attribute 'command'

Process finished with exit code 1
```

My env:
```
[root@localhost tmp]# pip3 -V
pip 20.2.2 from /usr/local/python3/lib/python3.6/site-packages/pip (python 3.6)
[root@localhost tmp]# pip3 list | grep -i ansible
ansible           2.8.0
ansible-runner    1.4.6
[root@localhost tmp]# ll /tmp/monitor.yml 
-rw-r--r-- 1 root root 1860 2020-09-07 11:10 /tmp/monitor.yml
[root@localhost tmp]# 
```

I have read the code in '/usr/local/python3/lib/python3.6/site-packages/ansible_runner/runner_config.py',  and didnt know how to fix it.

**Comment by xtay573269555** [comment]
It seems like that the RunnerConfig did not init the command property in \_init\_ function.

I print the method and property of RunnerConfig 
```
<class 'ansible_runner.runner_config.RunnerConfig'>
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'artifact_dir', 'binary', 'build_process_isolation_temp_dir', 'cmdline_args', 'directory_isolation_path', 'envvars', 'execution_mode', 'extra_vars', 'fact_cache', 'fact_cache_type', 'forks', 'generate_ansible_command', 'host_pattern', 'ident', 'inventory', 'json_mode', 'limit', 'loader', 'module', 'module_args', 'omit_event_data', 'only_failed_event_data', 'playbook', 'prepare', 'prepare_command', 'prepare_env', 'prepare_inventory', 'private_data_dir', 'process_isolation', 'process_isolation_executable', 'process_isolation_hide_paths', 'process_isolation_path', 'process_isolation_path_actual', 'process_isolation_ro_paths', 'process_isolation_show_paths', 'project_dir', 'quiet', 'resource_profiling', 'resource_profiling_base_cgroup', 'resource_profiling_cpu_poll_interval', 'resource_profiling_memory_poll_interval', 'resource_profiling_pid_poll_interval', 'resource_profiling_results_dir', 'roles_path', 'rotate_artifacts', 'skip_tags', 'ssh_key_data', 'suppress_ansible_output', 'tags', 'verbosity', 'wrap_args_with_cgexec', 'wrap_args_with_process_isolation', 'wrap_args_with_ssh_agent']

Traceback (most recent call last):
  File "/opt/jupyter_notedir/parse_datafile/demo.py", line 35, in <module>
    collect()
  File "/opt/jupyter_notedir/parse_datafile/demo.py", line 28, in collect
    r = runner.run()
  File "/usr/local/python3/lib/python3.6/site-packages/ansible_runner/runner.py", line 116, in run
    command = self.config.command
AttributeError: 'RunnerConfig' object has no attribute 'command'
```

**Comment by xtay573269555** [comment]
I add a line and it works.
The full code is following.

```
#!/usr/local/bin/python3
# -*- coding: utf-8 -*-

import os
import ansible_runner

def collect():
    os.environ["PATH"] = os.environ["PATH"] + ":/usr/local/python3/bin"
    print(os.environ["PATH"])
    rc = ansible_runner.RunnerConfig(
                 private_data_dir='/tmp',
                 inventory='/root/.ansible/hosts',
                 project_dir=None,
                 artifact_dir=None,
                 roles_path=None,
                 playbook='monitor.yml',
                 binary=None,
                 tags=None,
                 skip_tags=None,
                 ssh_key=None,
                 forks=None,
                 cmdline=None,
                 envvars=None)
    rc.prepare()                # <==     This is the most import line
    runner = ansible_runner.Runner(config=rc)
    (status, return_code) = runner.run()
    print("status: {}".format(status))
    print("return_code: {}".format(return_code))
    pass

if __name__ == '__main__':
    collect()
```

**Comment by xtay573269555** [comment]
The following guide on  [https://ansible-runner.readthedocs.io/en/latest/ansible_runner.html](https://ansible-runner.readthedocs.io/en/latest/ansible_runner.html) and  [https://ansible-runner.readthedocs.io/en/stable/_modules/ansible_runner/runner_config.html](https://ansible-runner.readthedocs.io/en/stable/_modules/ansible_runner/runner_config.html)  need a update.
```
Example: 
>>> rc = RunnerConfig(...)
>>> r = Runner(config=rc)
>>> r.run()
```

**Comment by matburt** [comment]
Are you just using the HEAD of the devel branch? This is in a pretty constant state of flux right now. The latest stable release is 1.4.6... which version are you using?

**Comment by AlanCoding** [comment]
```python
                 private_data_dir='/root/.ansible',
                 inventory='/tmp',
```

What are the contents of `/root/.ansible` before you run this? And this inventory doesn't make sense to me. What is the inventory you are trying to use?

**Comment by xtay573269555** [comment]
> 
> 
> Are you just using the HEAD of the devel branch? This is in a pretty constant state of flux right now. The latest stable release is 1.4.6... which version are you using?

I am using the latest stable release as below :

[root@localhost tmp]# pip3 list | grep -i ansible
ansible           2.8.0
ansible-runner    1.4.6
[root@localhost tmp]#

**Comment by xtay573269555** [comment]
> 
> 
> ```python
>                  private_data_dir='/root/.ansible',
>                  inventory='/tmp',
> ```
> 
> What are the contents of `/root/.ansible` before you run this? And this inventory doesn't make sense to me. What is the inventory you are trying to use?

Inventory and ansible config are in /root/.ansible . 

[root@localhost .ansible]# ls -l
total 348
-rw-r--r--  1 root root    209 Jul 23  2019 add_sshkey.yml
-rw-------  1 root root   1917 Sep  7 16:31 ansible.cfg
-rw-------  1 root root 302330 Sep  9 18:35 ansible.log
drw-------  2 root root   4096 Aug 17 11:06 cache
drw-------  2 root root   4096 Sep 14 12:05 cp
drw-------  2 root root   4096 Jul 25  2019 example
-rw-------  1 root root    847 Aug 20 11:25 hosts
drwxr-xr-x  8 root root   4096 Sep  7 16:30 mitogen
drwxr-xr-x  3 root root   4096 Jul 30  2019 roles
-rw-r--r--  1 root root    328 Aug 20 15:05 test.yml
drw------- 11 root root   4096 Sep 14 12:04 tmp
[root@localhost .ansible]#

**Comment by AlanCoding** [comment]
I expect the private data directory to resemble the demo in the docs:

https://ansible-runner.readthedocs.io/en/latest/intro.html#runner-input-directory-hierarchy

The reason I ask about your inventory is because I expect that `/tmp` will reference the absolute file path `/tmp`, as opposed to `tmp` relative within the private data directory. I'm unclear if referencing an inventory via a relative path to the private data directory is expected to work.

However, I do know that the playbook is normally expected to be a relative path within the `project` directory in the private data directory. You referenced `monitor.yml`, but there is no project folder. So I wouldn't expect that would work either.

**Comment by matburt** [comment]
It definitely looks like we've gone off the rails, I'd recommend reading through this: https://ansible-runner.readthedocs.io/en/stable/intro.htm

If we could get a solid reproducer that trips up on generating the command (without bailing out in some other way) then that would at least let build out a reasonable error message here.

**Comment by xtay573269555** [comment]
> 
> 
> I expect the private data directory to resemble the demo in the docs:
> 
> https://ansible-runner.readthedocs.io/en/latest/intro.html#runner-input-directory-hierarchy
> 
> The reason I ask about your inventory is because I expect that `/tmp` will reference the absolute file path `/tmp`, as opposed to `tmp` relative within the private data directory. I'm unclear if referencing an inventory via a relative path to the private data directory is expected to work.
> 
> However, I do know that the playbook is normally expected to be a relative path within the `project` directory in the private data directory. You referenced `monitor.yml`, but there is no project folder. So I wouldn't expect that would work either.

Any absolute directory path for `private_data_dir` and `inventory`  (I know the inventory should be a file), and any content in the yml file did not make a difference. 

You can simply reprodurce the error using the code i posted at the beginning.

**Comment by xtay573269555** [comment]
> 
> 
> It definitely looks like we've gone off the rails, I'd recommend reading through this: https://ansible-runner.readthedocs.io/en/stable/intro.htm
> 
> If we could get a solid reproducer that trips up on generating the command (without bailing out in some other way) then that would at least let build out a reasonable error message here.

The page [https://ansible-runner.readthedocs.io/en/stable/intro.htm](https://ansible-runner.readthedocs.io/en/stable/intro.htm)  does not exist.
![pic_20200915091618](https://user-images.githubusercontent.com/5844466/93153598-35ba8e00-f734-11ea-901c-55bfd48248ff.png)

And i had read the doc on  [https://ansible-runner.readthedocs.io/en/latest/ansible_runner.html](https://ansible-runner.readthedocs.io/en/latest/ansible_runner.html) as i mentioned at [https://github.com/ansible/ansible-runner/issues/515#issuecomment-688103880](https://github.com/ansible/ansible-runner/issues/515#issuecomment-688103880) .

**Comment by matburt** [comment]
After digging into this a bit, it looks like you aren't using the helper functions to actually start runner:

```
#!/usr/local/bin/python3
# -*- coding: utf-8 -*-

import os
import ansible_runner

def collect():
    print(os.environ["PATH"])
    runner = ansible_runner.run(
                 private_data_dir='/home/mjones/.ansible',
                 inventory='/tmp',
                 playbook='monitor.yml')
    r = runner.run()
    print("{}: {}".format(r.status, r.rc))
    print("Final status:")
    print(r.stats)
    pass

if __name__ == '__main__':
    collect()
```

That's similar but using the helper function, it still fails because you aren't adhering to the directory structure that's expected... let me fix the link I had yesterday: https://ansible-runner.readthedocs.io/en/stable/intro.html

You can see some more examples of how to start runner here: 
https://ansible-runner.readthedocs.io/en/stable/python_interface.html

**Comment by AlanCoding** [comment]
With this in the back of my mind, this bit jumped out at me:

https://github.com/ansible/ansible-runner/blob/548893c1b7a50c5f607d8269e1596ff15aab978b/ansible_runner/runner_config.py#L397-L402

After addition of adhoc/ansible-playbook commands, this method is leaky, where there are several places that `if` and `elif` conditions will leave `command` undefined. In those cases, runner just can't figure out the intent. A lot of people have a hesitation to add clauses where the program intentionally fails, but in these cases that is exactly what I'd want.

ansible-runner has a huge number configurable knobs, and there are a mind-boggling number of ways to set these in a mutually-inconsistent way. If you do, it'll fail in an unpredictable way. I don't want to attack that problem, because I don't people will agree on how to self-document through intentional failures.
