### ISSUE TITLE
If passwords file exists, passing in passwords dictionary to interface.run does not work

### ISSUE THREAD

**Issue by clickthisnick** [ansible/ansible-runner#517]
If there is already a serialized passwords file, then passing passwords into the interface.run fails.

To reproduce, run this twice. On first run it works fine (And serializes the /runner/env/passwords file)
On second run it fails, since that file exists.
```python3
import ansible_runner.interface

kwargs = {}
kwargs['playbook'] = 'test.yml'
kwargs['private_data_dir'] = '/runner'
kwargs['passwords'] = {"SSH [pP]assword:": "password"}

stdout = ansible_runner.interface.run(**kwargs)
```

Error:
```
Traceback (most recent call last):
  File "runner.py", line 11, in <module>
    stdout = ansible_runner.interface.run(**kwargs)
  File "/opt/ansible/3.6.5/lib64/python3.6/site-packages/ansible_runner/interface.py", line 210, in run
    r = init_runner(**kwargs)
  File "/opt/ansible/3.6.5/lib64/python3.6/site-packages/ansible_runner/interface.py", line 74, in init_runner
    rc = RunnerConfig(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'passwords'
```

At this point if I `rm -rf /runner/env/passwords` then run again, it will work.

I'm not sure the expected outcome, but I would have thought passwords would have merged into or overridden the serialized passwords file.

**Comment by AlanCoding** [comment]
this is a duplicate of https://github.com/ansible/ansible-runner/issues/493

**Comment by clickthisnick** [comment]
Ah, didn't see that, will close. Thanks!
