### ISSUE TITLE
Password prompt expect responses pulled by wrong index

### ISSUE THREAD

**Issue by slaffer-au** [ansible/ansible-runner#548]
Code from runner.py, Runner.run
```
            result_id = child.expect(password_patterns,
                                     timeout=self.config.pexpect_timeout,
                                     searchwindowsize=100)
            password = password_values[result_id]
            if password is not None:
                child.sendline(password)
                self.last_stdout_update = time.time()
```
The result_id returns a value 1 greater than the index of the matching password value.

Below is an example for matching the BECOME password, debugged using ipdb.

```
In[1]: password_patterns
Out[1]: 
[re.compile(r'^SSH [pP]assword:$', re.MULTILINE|re.UNICODE),
 re.compile(r'^BECOME [pP]assword:$', re.MULTILINE|re.UNICODE),
 pexpect.exceptions.TIMEOUT,
 pexpect.exceptions.EOF]
In[2]: result_id
Out[2]: 2
In[3]: password_values
Out[3]: ['some_password', 'become_password', None, None]
In[4]: password_values[2]
Out[4]: 

```

The fix is a simple `password = password_values[result_id -1]`.

Versions:
ansible-runner 1.4.6
python 3.8.5 on MacOS.

**Comment by MFlossmann** [comment]
Are you sure that the pattern actually matched? 
It's also possible that the `r'^BECOME [pP]assword:$'` didn't match and that pexpect threw a timeout. 

I had the same problem, until I realized that the prompt actually had a whitespace after the colon. When I replaced the pattern with `r'^BECOME [pP]assword\s*$`, I got the correct index.

**Comment by shanemcd** [comment]
Closing due to lack of response.
