### ISSUE TITLE
Pinning psutil dependency

### ISSUE THREAD

**Issue by clickthisnick** [ansible/ansible-runner#549]
Is there any reason not to pin the psutil dependency here:
https://github.com/ansible/ansible-runner/blob/devel/setup.py#L21

A new version `5.7.3` [came out on October 24th](https://pypi.org/project/psutil/#history) which breaks our companies builds until we build the new wheel and/or fork ansible-runner and pin the dependency.

**Comment by ScottCho** [comment]
pip install --upgrade setuptools

**Comment by shanemcd** [comment]
Hi @clickthisnick - does the suggestion from @ScottCho resolve the issue for you?

**Comment by clickthisnick** [comment]
This might be a bit of a snowflake case, the company I work for doesn't use pypi (They have an internal mirror) and any python packages which depends on C extensions must be build for each os.

Not a big deal without the pin, as we can just pin it ourselves - More so just wondering if pins would be acceptable to make builds deterministic

**Comment by AlanCoding** [comment]
Also see https://github.com/ansible/ansible-runner/issues/466

**Comment by clickthisnick** [comment]
Gonna close as issue linked ^ will fix
