### ISSUE TITLE
add support to ansible_check_mode / --check

### ISSUE THREAD

**Issue by nesies** [ansible/ansible-runner#580]
It would be nice to have the ability to enable Ansible "check mode"

https://docs.ansible.com/ansible/latest/user_guide/playbooks_checkmode.html

**Comment by jhampson-dbre** [comment]
There is a `cmdline` parameter you can pass to the `run` or `run_async` interface to send arbitrary Ansible command line flags. We are using this to enable check mode. For example:

```
ansible-runner -m debug --cmdline "\--check" --hosts localhost -a "var=ansible_check_mode" run /tmp

localhost | SUCCESS => {
    "ansible_check_mode": true
}
```

I'm not sure why the `\` is required, but it will fail parameter validation without it. Using ansible-runner as a python interface, did not need the `\`.
