### ISSUE TITLE
Move container image to newer python before Ansible removes support for CentOS default

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible-runner#595]
If you use the current ansible-runner container image, you will get this warning:

```
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 
3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]. This feature will be removed from ansible-core 
in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

The 3.6.8 comes from the centos base image (from python-base).

Proposed fix at https://github.com/ansible/ansible-runner/pull/594

**Comment by pabelanger** [comment]
So this will be tricky, as it will force all python deps to now be python3.8. Is that something we want to enforce?  This means, we maybe have to roll a python3.8 version of runner and python3.6 version

**Comment by AlanCoding** [comment]
How so? The only python constraint I see explicitly set is `python = "~2.7 || >=3.6"`

And actually, we've already knowingly broken some things in python 2 (for runner 2.0), so the python 2.7 part shouldn't even be there.

**Comment by shanemcd** [comment]
Both core and Tower are planning to move to 3.8, so this aligns with that.

**Comment by pabelanger** [comment]
> How so? The only python constraint I see explicitly set is `python = "~2.7 || >=3.6"`
> 
> And actually, we've already knowingly broken some things in python 2 (for runner 2.0), so the python 2.7 part shouldn't even be there.

I was more thinking of an ansible module dependency, what may only be python36. But, you are right. that isn't really our issue now, if they want lower version, they could roll python36 themself

**Comment by AlanCoding** [comment]
It has already been moved to 3.8, still dealing with the fallout
