### ISSUE TITLE
Do not load private_data_dir into memory for receptor transmission

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible-runner#604]
This is a followup from the conversation in:

https://github.com/ansible/ansible-runner/pull/505#discussion_r500518372

As of today, this method still works with an in-memory buffer.

https://github.com/ansible/ansible-runner/blob/ae4cd96a2568d0e31695bf98f5a374e5efa660dc/ansible_runner/utils.py#L87

This is a non-starter for many users of AWX, because they have projects that run into the 20 GB territory and this will crash. This seems to me like a hard release blocker.

#### Fix option - send directly to standard out

I attempted a fix in the branch here:

https://github.com/ansible/ansible-runner/compare/devel...AlanCoding:direct_to_pipe

The idea here is that we completely do away with the in-memory buffer and write directly to the output stream. This means that we don't have the full length of the message before we send it. I don't know if that can be worked around. This also had problems grappling with the general way that the zipfile library worked, and it might not be workable.

#### Fix option - use a file on disk an intermediary

We know pretty well that this alternative will work - write the data to a file instead of a `BytesIO()` object. Then we can obtain the size of it without reading the entire contents, and we can write it to standard out line-by-line without storing the entire thing in memory.

**Comment by kdelee** [comment]
Using this in awx, sending a large project (8.something GB of data on a machine that only has 8GB of memory) to a container group, we saw the disk usage go up indicating the file was being staged and then watched the network traffic as the file got sent. Then in the job in the container group we saw  that the files were indeed present..


Keep in mind the tower node needs to have more than 2x of that the project consumes. So if the project is 20GB, they need to have at least 21GB of free disk or they will run out of disk.

![Screenshot from 2021-05-26 16-25-44](https://user-images.githubusercontent.com/29239279/119726816-8c3da780-be3f-11eb-81f6-804cc38b08b9.png)
