### ISSUE TITLE
Documentation: Password patterns lack a whitespace character

### ISSUE THREAD

**Issue by MFlossmann** [ansible/ansible-runner#608]
Hi!

In the [env/passwords section](https://github.com/ansible/ansible-runner/blob/37c87e006874606ccaf7d41a18a2b519ef0cda64/docs/intro.rst#envpasswords) of the documentation, the example shows the prompts as

``` yaml
---
"^SSH [pP]assword:$": "some_password"
"^BECOME [pP]assword:$": "become_password"
```

But the actual prompt has a whitespace character after the colon. It is correct in the examples, but not in this snippet of the documentation.

Sorry, if this is so minor that I should've made a pull request. Not sure what's the github etiquette on that. ;) 
... But that wrong pattern actually **has** cost me a few hours. :sweat_smile:

**Comment by SirUli** [comment]
Seems to be fixed in the meantime with this commit: https://github.com/ansible/ansible-runner/commit/568c1694372b7c341eca5ce36bceb4adc8e4d1d0

**Comment by Shrews** [comment]
This does seem to be fixed in the latest docs, so I'm going to close this. Thanks for the report and to @SirUli for mentioning the fix.
