### ISSUE TITLE
plugin: Invalid "children" entry for "all" group, requires a dictionary, found "<class 'list'>" instead.

### ISSUE THREAD

**Issue by liminghua999** [ansible/ansible-runner#610]
pip3 install  ansible-runner
I run ansible-runner like this:
`ansible_runner.run(artifact_dir=self.artifact_dir, project_dir=self.project_dir, inventory=self.inventory, host_pattern=hosts, module=module, module_args=cmd)`

I want self.inventory args likes this:
`
extravars like this:
{"ansible_user":tmpinfo.username, 
"ansible_port":tmpinfo.port,
"ansible_ssh_pass":tmpinfo.password
}

{
‘all’: {'children': ['hostname1','hostname2']},
 'hostname1': {'hosts': ['hostname1-IP'] ,'vars': extravars1 },
'hostname2': {'hosts': ['hostname2-IP'] ,'vars': extravars2 }
}`

and I only get this results:
`[WARNING]:  * Failed to parse /tmp/tmpgv7b52tv/inventory/hosts.json with yaml
plugin: Invalid "children" entry for "all" group, requires a dictionary, found
"<class 'list'>" instead.
[WARNING]:  * Failed to parse /tmp/tmpgv7b52tv/inventory/hosts.json with ini
plugin: Invalid host pattern '{all:' supplied, ending in ':' is not allowed,
this character is reserved to provide a port.
[WARNING]: Unable to parse /tmp/tmpgv7b52tv/inventory/hosts.json as an
inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'
[WARNING]: Could not match supplied host pattern, ignoring:`

where I wrong; 
ansible_runner.run(inventory)
this args show it's type: 
  Native python dict supporting the YAML/json inventory structure
  str or dict or list

**Comment by Akasurde** [comment]
@liminghua999 Thanks for reporting this issue. You need to modify the code something like - 

```python
import ansible_runner

extravars1 = {
    "ansible_user": 'username1', 
    "ansible_port": '8888',
    "ansible_ssh_pass": 'password1'
}

extravars2 = {
    "ansible_user": 'username2', 
    "ansible_port": '8889',
    "ansible_ssh_pass": 'password2'
}

inventory = {
    "all": {
        "children": {
            "hostname1": {
                "hosts": {
                    "hostname1-ip": None
                },
                "vars": extravars1
            },
            "hostname2": {
                "hosts": {
                    "hostname2-ip": None
                },
                "vars": extravars2
            }
        }
    }
}

r = ansible_runner.run(
    host_pattern="all",
    module="ping",
    inventory=inventory,
)

```

Please feel free to re-open the issue if the problem persists. Thanks.

**Comment by geek96boolean10** [comment]
I think the issue is not resolved because the documentation is incorrect:
https://docs.ansible.com/ansible/latest/dev_guide/developing_inventory.html#inventory-script-conventions
shows:
```
{
    "group001": {
        "hosts": ["host001", "host002"],
        "vars": {
            "var1": true
        },
        "children": ["group002"]
```
which obviously indicates the 'children' entry is a list.

**Comment by Akasurde** [comment]
@geek96boolean10 The documentation is correct since it shows the JSON object of inventory. We need to use "yaml" representation of inventory while using ansible-runner.
