### ISSUE TITLE
Run Execution Environments as non-root user, even in rootless containers

### ISSUE THREAD

**Issue by shanemcd** [ansible/ansible-runner#611]
@kdelee reached out and expressed some concerns after reading https://www.redhat.com/sysadmin/rootless-podman-makes-sense.

When running as root inside of a rootless container, if a user manages to break out of the container, they will be able to read things on the host owned by the user that started the container.

To prevent this, a non-root user can be used inside of the container:

```
FROM centos:8

RUN useradd -u 1000 runner

USER runner
```

The UID here must be predictable / known so that you can do:

```
$ mkdir -p test
$ podman unshare chown 1000:1000 $PWD/test
```

Once that is done, the host-side directory will be owned by the mapped UID:

```
$ ll
total 0
drwxr-xr-x. 2 100999 100999 6 Jan 13 13:45 test
```

Demonstrating of using that directory inside of container as non-root user:

```
$ podman run -ti -v $PWD/test/:/runner:Z test bash
[runner@31b9ad8dfe15 /]$ touch /runner/test
[runner@31b9ad8dfe15 /]$ ls -la /runner/
total 0
drwxr-xr-x.  2 runner runner 18 Jan 13 18:47 .
dr-xr-xr-x. 18 root   root   42 Jan 13 18:47 ..
-rw-rw-r--.  1 runner runner  0 Jan 13 18:47 test
[runner@31b9ad8dfe15 /]$ exit
shanemcd@fedora:~/podman
 $ ls -la test
total 0
drwxr-xr-x. 2   100999   100999 18 Jan 13 13:47 .
drwxr-xr-x. 3 shanemcd shanemcd 39 Jan 13 13:47 ..
-rw-rw-r--. 1   100999   100999  0 Jan 13 13:47 test
```

To get back to something you can delete as the host user:

```
$ podman unshare chown -R 0:0 $PWD/test
```

.... or just run:

```
$ podman unshare rm -rf $PWD/test
````

**Comment by shanemcd** [comment]
This will have several touch points:

This will need to go in the base `ansible-runner` image:

```
RUN useradd -u 1000 runner
```

This will need to be the final line of any `Containerfile` written by `ansible-builder`:

```
USER runner
```

In AWX, we currently clean up private data directories like this: https://github.com/ansible/awx/blob/74daa49e6f6ad97cbd57691a6ee41fd4709386fb/awx/main/tasks.py#L899

We will need to do something like `podman unshare rm -rf $private_data_dir` instead.

**Comment by kdelee** [comment]
Great! thanks for filing this.

For context, here are the group of articles I was reading regarding rootless containers

the one mentioned in the above issue: https://www.redhat.com/sysadmin/rootless-podman-makes-sense
another redhat blog that got me there: https://www.redhat.com/en/blog/understanding-root-inside-and-outside-container 

this one is not as related, but it explains why "running untrusted workloads in privileged containers is insane" which was helpful for me https://people.kernel.org/brauner/runtimes-and-the-curse-of-the-privileged-container

**Comment by shanemcd** [comment]
I am starting to have doubts about whether this is going to be possible.

On the host side, runner needs to be able to read files written by the display callback from within the container. When the files get created as the mapped uid, this happens:

```
Failed to open ansible stdout callback plugin partial data file /home/shanemcd/awx/ansible-runner/demo/artifacts/17d39d57-74a5-4b4c-b972-64730f840f58/job_events/5837a7b6-49e6-483f-947f-c874f9481bf7-partial.json
Failed writing event data: [Errno 13] Permission denied: '/home/shanemcd/awx/ansible-runner/demo/artifacts/17d39d57-74a5-4b4c-b972-64730f840f58/job_events/5-5837a7b6-49e6-483f-947f-c874f9481bf7.json'
Failed to open ansible stdout callback plugin partial data file /home/shanemcd/awx/ansible-runner/demo/artifacts/17d39d57-74a5-4b4c-b972-64730f840f58/job_events/ee0effba-f1bc-7d2b-8b9e-000000000006-partial.json
Failed writing event data: [Errno 13] Permission denied: '/home/shanemcd/awx/ansible-runner/demo/artifacts/17d39d57-74a5-4b4c-b972-64730f840f58/job_events/6-ee0effba-f1bc-7d2b-8b9e-000000000006.json'
```

**Comment by shanemcd** [comment]
From Dan Walsh over on a [podman issue](https://github.com/containers/podman/issues/4016#issuecomment-565409218): 

> SELinux would prevent a container from reading your .ssh keys if it was to escape.

In order for this to be a real threat to us, 2 layers of security (containers, selinux) would need to fail.

**Comment by shanemcd** [comment]
I dont think we are likely to do this anymore.
