### ISSUE TITLE
Allow ansible-runner transmit to specify worker private_data_dir

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible-runner#612]
Right now, `ansible-runner worker` will unpack things to either:

 - Folder given by `ansible-runner worker --private-data-dir=...`
 - A temporary folder

Due to [bugs] we want the worker command to use the same private data dir as the transmit command. This doesn't seem to give any problems with unpacking the contents, demo:

```
ansible-runner transmit demo -p test.yml > /tmp/output
ansible-runner worker --private-data-dir demo < /tmp/output > /tmp/output2
ansible-runner process demo < /tmp/output2
```

I believe this reuses the `demo` folder in all 3 cases, which is apparently okay.

We want to invoke `ansible-runner worker` by itself, and have it obtain the `demo` directory from the data sent by the transmit command.

**Comment by jbradberry** [comment]
I can't think of any reason why this shouldn't work.  However, in my opinion paths sent over the wire like this should always be absolute paths.

**Comment by AlanCoding** [comment]
Correct me if I'm wrong anywhere here. `job_kwargs` are those kwargs sent over the wire:

https://github.com/ansible/ansible-runner/blob/ae4cd96a2568d0e31695bf98f5a374e5efa660dc/ansible_runner/streaming.py#L68

But the worker private data dir is determined from `kwargs`, which comes from the CLI.

If those do not have private_data_dir in them, then it uses the temp dir.

https://github.com/ansible/ansible-runner/blob/ae4cd96a2568d0e31695bf98f5a374e5efa660dc/ansible_runner/streaming.py#L70-L73

So this would need to delay setting `self.private_data_dir` until after `.run` was called and the first message containing the job's kwargs is loaded.

**Comment by shanemcd** [comment]
I believe we just need to pass in `--private-data-dir` so that it's not `.None`. I'm working on this now in between meetings.

**Comment by jbradberry** [comment]
@AlanCoding I believe you are correct, we'll need to change it on the fly based on a json message after `.run()` is called.

**Comment by AlanCoding** [comment]
This doesn't appear to be needed by AWX anymore, and my interest has passed.
