### ISSUE TITLE
release 1.4.7 docker image

### ISSUE THREAD

**Issue by mkyc** [ansible/ansible-runner#635]
There is [1.4.7 tag](https://github.com/ansible/ansible-runner/releases/tag/1.4.7) released 8 days ago, but last numbered version in docker hub is still [version 1.4.6](https://hub.docker.com/r/ansible/ansible-runner/tags?page=1&ordering=last_updated) from 9 months ago.

**Comment by jandd** [comment]
`make image` from the 1.4.7 tag fails due to #636 currently

**Comment by shanemcd** [comment]
It's up now!
