### ISSUE TITLE
Ansible runner only follows configurations in 'env / extravars' dir and not any specific config mentioned in 'inventory / hosts' file corresponding to some host.

### ISSUE THREAD

**Issue by yadvendra20** [ansible/ansible-runner#639]
I've configured **'env / extravars'** as follows,
```
---
ansible_connection = ssh
```
and **'inventory / hosts'** as
```
---
[local]
localhost ansible_connection = local

[test]
test@some_ip
```
Here, I expected that ansible runner should try to connect to test servers using ssh connection but with localhost, it should use the local connection. 
But still, it tries to connect to the localhost with ssh only and fails to connect.

If I make `ansible_connection = local` in **'env / extravars'**, it won't connect to my remote test servers.

Feel free to correct me if I'm missing something here. Any suggestions are welcome.

**Comment by danielmendozapupo** [comment]
What if I want to access other hosts?

**Comment by samdoran** [comment]
You shouldn't need to define the `localhost` in inventory. Just use the [implicit localhost](https://docs.ansible.com/ansible/latest/inventory/implicit_localhost.html#implicit-localhost) provided by default, or add `delegate_to: localhost` on the task (after you remove that `localhost` entry from inventory). As defined in the above example, it's possible an unexpected Python interpreter could be used for tasks targeting the `localhost` defined in inventory.

Setting `ansible_connection: local` as an extra var will override it for _all_ hosts, so what you're seeing with this set is expected.

To discuss this further, please reach out on #ansible or #ansible-runner on irc.libera.chat.
