### ISSUE TITLE
Structure in docs does not correspond with functionality

### ISSUE THREAD

**Issue by cdvv7788** [ansible/ansible-runner#64]
According to https://ansible-runner.readthedocs.io/en/latest/intro.html#runner-input-directory-hierarchy

The roles directory is outside of project folder:
![image](https://user-images.githubusercontent.com/5531776/41500534-c6ed894a-7158-11e8-88cb-d1cff81fc44e.png)
When I set up my structure like that, I get:

    The role xxx was not found in /tmp/tmp2le4eyz0/project/roles:/home/ubuntu/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/tmp/tmp2le4eyz0/project

Obviously, moving roles to be inside the project folder fixes the issue.
Is this a bug or a documentation error? If the error is in the documentation, let me know and I can make the change.

**Comment by privateip** [comment]
@cdvv7788 I think this is a bug more than a docs issue as it should work.  For a work around you can also pass the `--roles-path` command line option to `ansible-runner`.  Will work on tracking it down and squashing it

**Comment by cdvv7788** [comment]
@privateip I am using the python interface:
`import ansible_runner
runner = ansible_runner.run(private_data_dir=temp_dir.name, `playbook='playbook.yml')`

**Comment by privateip** [comment]
That makes more sense, thanks for the clarification

**Comment by privateip** [comment]
I have a fix for this but am still testing it.  Hope to have it PR ready over the weekend
