### ISSUE TITLE
Inventory specified as a dictionary isn't actually supported

### ISSUE THREAD

**Issue by eskultety** [ansible/ansible-runner#642]
The documentation says the following about the `inventory` parameter:
>  Overridees the inventory directory/file (supplied at private_data_dir/inventory) with
>  a specific host or list of hosts. This can take the form of
> 
>  - Path to the inventory file in the private_data_dir
>  - **Native python dict supporting the YAML/json inventory structure**
>  - A text INI formatted string
>  - A list of inventory sources, or an empty list to disable passing inventory

And yet if one passes a dictionary, it is not stringified properly which results e.g. in the following cmdline:
```
['ansible', '-i', {'all': {'dev': {'hosts': ['localhost']}, 'ungrouped': {'hosts': ['my_machine1', 'my_machine2']}}}, '-m', 'setup', '*']
```
...which leads to the following exception:
```
  File "/usr/lib/python3.9/site-packages/ansible_runner/runner.py", line 171, in run
    child = pexpect.spawn(
  File "/usr/lib/python3.9/site-packages/pexpect/pty_spawn.py", line 205, in __init__
    self._spawn(command, args, preexec_fn, dimensions)
  File "/usr/lib/python3.9/site-packages/pexpect/pty_spawn.py", line 281, in _spawn
    self.name = '<' + ' '.join(self.args) + '>'
TypeError: sequence item 2: expected str instance, dict found
```

**Comment by eskultety** [comment]
Nevermind, Ansible only works on top of files in which case - how is the `inventory` parameter supposed to work with dictionaries then?

**Comment by matburt** [comment]
I think this *is* probably a valid issue given where we were when we were first putting this together. Runner should be able to generate an inventory file for ansible to read in this case.

**Comment by dabukalam** [comment]
I tried to do this same thing this morning, but ran into a different traceback:

```
  File "/home/danny/.local/lib/python3.7/site-packages/ansible_runner/interface.py", line 177, in run
    r = init_runner(**kwargs)
  File "/home/danny/.local/lib/python3.7/site-packages/ansible_runner/interface.py", line 43, in init_runner
    dump_artifacts(kwargs)
  File "/home/danny/.local/lib/python3.7/site-packages/ansible_runner/utils.py", line 189, in dump_artifacts
    kwargs['inventory'] = dump_artifact(json.dumps(obj), path, 'hosts.json')
  File "/home/danny/.local/lib/python3.7/site-packages/ansible_runner/utils.py", line 123, in dump_artifact
    with open(fn, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/home/danny/dev/mellanox-onyx/inventory/hosts.json'
```

The hosts.json in question seems to be written with 0400 permissions:
```
**$ stat /home/danny/dev/mellanox-onyx/inventory/hosts.json
  File: /home/danny/dev/mellanox-onyx/inventory/hosts.json
  Size: 171             Blocks: 8          IO Block: 4096   regular file
Device: 802h/2050d      Inode: 22549093    Links: 1
Access: (0400/-r--------)  Uid: ( 1002/   danny)   Gid: ( 1002/   danny)
Access: 2021-05-19 23:41:44.473592471 -0700
Modify: 2021-05-19 23:41:44.145590887 -0700
Change: 2021-05-19 23:41:44.145590887 -0700
 Birth: -
 ```
 
 Could possibly be this bit that's offending?
 
 https://github.com/ansible/ansible-runner/blob/0f5835bd7fe3c7ecdc4d421f62538e3650a329ee/ansible_runner/utils.py#L117-L131
