### ISSUE TITLE
怎么取消输出的颜色字体代码

### ISSUE THREAD

**Issue by Luoganggang** [ansible/ansible-runner#668]
![image](https://user-images.githubusercontent.com/39610717/114598882-fd2c6400-9cc4-11eb-91a8-257c768165b5.png)
![image](https://user-images.githubusercontent.com/39610717/114599124-48df0d80-9cc5-11eb-9310-a8e7d5767f81.png)
怎么取消输出的颜色字体代码

**Comment by Fanduzi** [comment]
```
cat env/envvars

---
ANSIBLE_NOCOLOR: 1
```

**Comment by Fanduzi** [comment]
I'm trying to put the output into a front-end codemirror, but I'm having the same problem as you, and I don't know how to handle this `[0;33m`, I can only choose to set `ANSIBLE_NOCOLOR: 1`

**Comment by Luoganggang** [comment]
谢谢，采用这种方法前我采用的是用正则截取掉颜色代码

**Comment by Luoganggang** [comment]
谢谢，采用这种方法前我采用的是用正则截取掉颜色代码

**Comment by wenottingham** [comment]
Yes, this comes from ansible, not runner itself.
