### ISSUE TITLE
Inventory is dumped with unreadable unix permissions

### ISSUE THREAD

**Issue by dabukalam** [ansible/ansible-runner#702]
I tried to do [this same thing](https://github.com/ansible/ansible-runner/issues/642) this morning, but ran into a different traceback:

```
  File "/home/danny/.local/lib/python3.7/site-packages/ansible_runner/interface.py", line 177, in run
    r = init_runner(**kwargs)
  File "/home/danny/.local/lib/python3.7/site-packages/ansible_runner/interface.py", line 43, in init_runner
    dump_artifacts(kwargs)
  File "/home/danny/.local/lib/python3.7/site-packages/ansible_runner/utils.py", line 189, in dump_artifacts
    kwargs['inventory'] = dump_artifact(json.dumps(obj), path, 'hosts.json')
  File "/home/danny/.local/lib/python3.7/site-packages/ansible_runner/utils.py", line 123, in dump_artifact
    with open(fn, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/home/danny/dev/mellanox-onyx/inventory/hosts.json'
```

The hosts.json in question seems to be written with `0400` permissions:
```
**$ stat /home/danny/dev/mellanox-onyx/inventory/hosts.json
  File: /home/danny/dev/mellanox-onyx/inventory/hosts.json
  Size: 171             Blocks: 8          IO Block: 4096   regular file
Device: 802h/2050d      Inode: 22549093    Links: 1
Access: (0400/-r--------)  Uid: ( 1002/   danny)   Gid: ( 1002/   danny)
Access: 2021-05-19 23:41:44.473592471 -0700
Modify: 2021-05-19 23:41:44.145590887 -0700
Change: 2021-05-19 23:41:44.145590887 -0700
 Birth: -
 ```
 
 Could possibly be this bit that's offending?
 
 https://github.com/ansible/ansible-runner/blob/0f5835bd7fe3c7ecdc4d421f62538e3650a329ee/ansible_runner/utils.py#L117-L131

_Originally posted by @dabukalam in https://github.com/ansible/ansible-runner/issues/642#issuecomment-844777469_

**Comment by bprins** [comment]
Running into the same issue when using a static `private_data_dir` and an INI formatted string with the `inventory` parameter. The problem seems to be that, after the first run, the inventory file in the `private_data_dir` is not writeable for subsequent runs.

**Comment by rubyAce71697** [comment]
I am able to make subsequent runs for same host/hosts. But for new hosts it is not writable.

**Comment by S0LERA** [comment]
> 
> 
> I am able to make subsequent runs for same host/hosts. But for new hosts it is not writable.

Hello, I'm doing some tests and that's exactly what happens to me too.

**Comment by gdeleon23** [comment]
Hello, same problem to me.

**Comment by pcleon** [comment]
me too;
two file under inventory and project are both 400
```

inventory:
total 4
-r--------. 1 genpw genpw 14 Jan 26 15:15 hosts.json

project:
total 4
-r--------. 1 genpw genpw 178 Jan 26 15:15 main.json
```

**Comment by TheTechromancer** [comment]
Running into this as well.

**Comment by Smixi** [comment]
I got the same issue. Is there a way to not write the inventory at all, so we don't have to bother about permissions, or a temporary one. It doesn't feel legitimate to have an inventory passed as a dictionnary that is written (with potentially secrets in it).  Is this because of how Ansible handle them ? (duplicated : https://github.com/ansible/ansible-runner/issues/853)
