### ISSUE TITLE
Failure to run on Mac OS X

### ISSUE THREAD

**Issue by shawn-hurley** [ansible/ansible-runner#72]
Runner fails at os.mknod(artifact_path, stat.S_IFREG | stat.S_IRUSR | stat.S_IWUSR) lin 143 in runner.py.

This appears to be because of this issue: https://stackoverflow.com/questions/32115715/os-mknod-fails-on-macos

I tried to run this as sudo user as well and got an "Invalid argument" error.

**Comment by cdvv7788** [comment]
There is a pull request that presents a portable replacement for mknod. Check if that branch runs for you: https://github.com/ansible/ansible-runner/pull/55

**Comment by shawn-hurley** [comment]
I can't seem to pull down the branch `os_mknod_fix` from the PR authors fork, and I notice that it no longer shows up in GitHub UI when I browse the branches there. Any suggestions?

**Comment by shawn-hurley** [comment]
Manually made the changes and tested. This PR will fix this issue as well.
