### ISSUE TITLE
runner_on_failed event needs to reflect errors rescured by blocks

### ISSUE THREAD

**Issue by matt8754** [ansible/ansible-runner#726]
Similar to ignore_errors, when a task error is rescued by using blocks, the runner_on_failed event should reflect it.  This is quite important for Foreman which it relies on this event to decide whether a playbook is failed.

**Comment by matburt** [comment]
Runner itself only reports what the Ansible event itself exposes and doesn't know anything more than what ansible-core reports. My intuition is that the rescue block happens temporally after we've received the `runner_on_failed` event and without delaying that failed event until after the rescue there's no way to know for certain if a rescue were going to occur. That would be a pretty massive change conceptually.

From Runner's perspective it's going to be up to the consumer to understand the effect that has on task level events.
