### ISSUE TITLE
provide auto-delete artifact directory upon completion

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-runner#739]
rather than every consumer of runner having to implement the logic, consider an api parameter that instructs runner to delete it's artifacts when no longer needed by runner

**Comment by matburt** [comment]
This *somewhat* exists already: https://github.com/ansible/ansible-runner/blob/devel/ansible_runner/interface.py#L166

**Comment by Akasurde** [comment]
resolved_by_pr #1111
