### ISSUE TITLE
Permissions are not changeable because dir /runner is a Volume

### ISSUE THREAD

**Issue by jrhoward** [ansible/ansible-runner#741]
https://github.com/ansible/ansible-runner/blob/9652fa0753a31364dbb62cd787cfe07aab8e730b/Dockerfile#L54

Hi. I am trying to build off this base and dont want to run a user with guid 0.

because /runner is a Docker VOLUME I cannot change the permissions forcing me to run with a user with guid 0.

Is that the intended functionality ?

Any chance we can remove the VOLUME /runner ?

I am happy to do the pull request

**Comment by shanemcd** [comment]
Yeah, I can't really think of any real reason this needs to be declared as an explicit VOLUME. I'd accept this PR.

**Comment by jrhoward** [comment]
Hi @shanemcd , I have created a pull request and referenced this issue
