### ISSUE TITLE
(Container) ansible-galaxy install/git clone: strict host key checking

### ISSUE THREAD

**Issue by 81Denton** [ansible/ansible-runner#744]
**ISSUE TYPE**
Bug Report

**SUMMARY**
When you build a container, the env var `ANSIBLE_HOST_KEY_CHECKING` does not affect ansible-galaxy install/git clone. This means that it is not possible to disable strict host key checking for `ansible-galaxy role/collection install`.
Adding the git repo to ~/.ssh/known_hosts via `ssh-keyscan -t rsa mygitrepo.xyz >> ~/.ssh/known_hosts` does not fix this either.

Workarounds for this are setting StrictHostKeyChecking to no in your SSH config, or setting the env var `$GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"` before performing ansible galaxy role/collection install.

**STEPS TO REPRODUCE**
Add a git repo to roles/requirements.yml, ie
```
---
- src: git@mygitrepo.xyz:ansible/roles/myrole.git
  scm: git
  name: myrole
```
When building the container, set the aforementioned env var and execute ansible-galaxy:
```
export ANSIBLE_HOST_KEY_CHECKING=False
ansible-galaxy install role -r git@mygitrepo.xyz:ansible/roles/myrole.git`
```
The result:
```
[WARNING]: - myrole was NOT installed successfully: - 
command /usr/bin/git clone git@mygitrepo.xyz:ansible/roles/myrole.git myrole
failed in directory /runner/.ansible/tmp/ansible-local-57r68lns17/tmpnhtygda5
(rc=128) - Cloning into 'myrole'... Host key verification failed.  
fatal: 
Could not read from remote repository.  Please make sure you have the correct
access rights and the repository exists.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```
The repo checkout performed by the `ansible-runner` command does not throw these errors.

**EXPECTED RESULTS**
You should be able to disable strict host key checking via `$ANSIBLE_HOST_KEY_CHECKING` or another var.

**ACTUAL RESULTS**
Role installation fails.

**Comment by wenottingham** [comment]
Hi -

This repo is for issues with ansible-runner itself. Off the top of my head, I don't think that `ANSIBLE_HOST_KEY_CHECKING`, which is for ansible-playbook reaching out via the SSH connection plugin to manage machines, is designed to be used by `ansible-galaxy` checking out git repos over SSH.

What you describe sounds like it's an issue with ansible-galaxy, which comes from ansible itself, and would need to be filed at https://github.com/ansible/ansible/issues so the right people will see it and can look at it.

**Comment by 81Denton** [comment]
Thanks for the info, I'll go open an issue there.
