### ISSUE TITLE
Documentation needs updated with removal of `adhoc` and `playbook` commands.

### ISSUE THREAD

**Issue by Shrews** [ansible/ansible-runner#753]
Since the `adhoc` and `playbook` commands were removed from the code base, the documentation has been very much out of date.

For example:

- The `execution_environments.rst` file seems to be mostly irrelevant now, or should at least be updated to show how to use an EE now.
- The `standalone.rst` doc still contains references to the removed commands.

**Comment by benthomasson** [comment]
This page needs to be updated as well: https://www.ansible.com/blog/introduction-to-ansible-builder
