### ISSUE TITLE
How to set write ansible run log to Specify file

### ISSUE THREAD

**Issue by w38351479** [ansible/ansible-runner#755]
I use ansible_runner.interface.run_command_async,  I want write run log to specify file。Default input_fd/output_fd/error_fd ,but I dont know how to get this task uuid，so I want specify log file. Can anyone help me？ thanks！

**Comment by samdoran** [comment]
For `ansible` commands, it's not possible to change `input`/`output`/`error` file descriptors.

The output from the job is written to files in the private data directory. This defaults to `/tmp/.ansible-runner-[random]`. Specifying the private data directory will make it easier to locate output from a job.

Alternatively, specifying `artifact_dir` controls where artifacts for a job run are located.

```
run_command_async('ansible', ['localhost', '-m', 'pause', '-a', 'seconds=10'], private_data_dir='/tmp/output', artifact_dir='/tmp/artifacts/')
```

To discuss this further, please reach out on IRC #ansible-runner on irc.libera.chat
