### ISSUE TITLE
Add arm64 build target for docker image

### ISSUE THREAD

**Issue by ck3mp3r** [ansible/ansible-runner#760]
Currently only linux/amd64 images are available. Would be awesome if you could add arm64 images.

**Comment by mkjpryor** [comment]
+1

This is a pretty massive blocker for using `ansible-runner` on a Mac with an M1 chip.

**Comment by sivel** [comment]
We have decided to no longer maintain, support, or create container images for ansible-runner going forward.

Please see https://github.com/ansible/ansible-runner/issues/1199 for more information.

**Comment by michaelniemand** [comment]
any news on this?
