### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by scottdfedorov** [ansible/ansible-runner#783]
Fresh install of ansible-runner on CentOS7. Both python2 and python3 are installed, but installed runner to be on python2 with `sudo python2 -m pip install ansible-runner` which installed ok.

Now attempting to run `ansible-runner --help` and getting the following error:

```
ansible-runner --help
Traceback (most recent call last):
  File "/usr/bin/ansible-runner", line 6, in <module>
    from ansible_runner.__main__ import main
  File "/usr/lib/python2.7/site-packages/ansible_runner/__init__.py", line 3, in <module>
    from .interface import run, run_async, \
  File "/usr/lib/python2.7/site-packages/ansible_runner/interface.py", line 88
    print(f'Unable to find process isolation executable: {pi_executable}')
                                                                        ^
SyntaxError: invalid syntax
```

**Comment by scottdfedorov** [comment]
Looking at the specific line referenced, it seems that even though the file is in the python2.7 folder, that method, printing with f-string (`print(f' ...`) was only added to python3 I believe. 

@jladdjr You had the last commit on that line. Any help? :)

**Comment by shanemcd** [comment]
Ansible Runner no longer supports Python 2. You'll have to use the latest 1.x release.

**Comment by scottdfedorov** [comment]
> Ansible Runner no longer supports Python 2. You'll have to use the latest 1.x release.

Is this in the documentation somewhere I missed? It specifically says:
> Python 2.7+ and 3.6+ are supported and installable via pip:

and the change log from 1.4.7 to 2.0.0 doesn't note anything like that.
