### ISSUE TITLE
Return a machine UUID number in `ansible-runner worker --worker-info` output

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible-runner#788]
AWX tracks a `uuid` for each machine in a cluster. For normal cluster nodes, this is generated and saved in a settings file.

That's not really possible with remote execution nodes, so we need to come up with some other solution. Either ansible-runner would need to save a file in a known location, or we find some existing identifier off-the-shelf.

It looks like we could use the same logic as Ansible core does for the machine id: https://github.com/ansible/ansible/issues/10221

heads up to @chrismeyersfsu

**Comment by shanemcd** [comment]
My first thought was maybe use the MAC address for this, but that would likely cause issues in the future when we have pod-based execution nodes (multiple containers on the same host would report the same mac address).

I'm thinking that for VM-based execution nodes this could be a UUID file laid down somewhere by the installer. For containers, we actually already have a way of obtaining a uuid:

https://github.com/ansible/awx-operator/blob/4651216cc0d064156770b918a26b97f974f707fc/roles/installer/templates/deployment.yaml.j2#L241-L244

I understand we are not doing pod-based execution nodes for this release, this was just more context for when we get around to it.

**Comment by AlanCoding** [comment]
My link to the Ansible issue was meant to imply a specific implementation. It was closed with [this PR](https://github.com/ansible/ansible/pull/10284) which did

```python
        machine_id = get_file_content("/var/lib/dbus/machine-id") or get_file_content("/etc/machine-id")
        if machine_id:
            machine_id = machine_id.split('\n')[0]
            self.facts["machine_id"] = machine_id
```

On Fedora, those 2 locations return the same value. I don't have any preference here, so I would suggest that the easiest thing would be to mimic their logic exactly. This has a documentation advantage that this is already a thing in Ansible facts, which you can verify:

```
ansible -i localhost, --connection=local -m setup localhost | grep "ansible_machine_id"
```

**Comment by AlanCoding** [comment]
Implemented in linked PR
