### ISSUE TITLE
patchback creating branch for backports

### ISSUE THREAD

**Issue by pabelanger** [ansible/ansible-runner#795]
Can patchback be configured to use a different repo to open PRs against?  Otherwise, all users of ansible-runner have to clone them now.

@shanemcd @webknjaz

**Comment by webknjaz** [comment]
No. But you can enable automatic deletion of the branches upon merge in the repo settings.

**Comment by webknjaz** [comment]
P.S. I was thinking about this problem in the past and concluded that it may be too complex for such a simple stateless robot. I recall pyup did auto-create forks under its org at some point and migrated to the in-repo branches later. I don't know why but I have a hunch they've hit some org-level rate limits. So if Patchback was to support this, it might require supporting a setup where a user would install it into two repos (upstream and fork) to avoid this problem (which sounds rather complicated to setup and less user-friendly).

FWIW feel free to file a feature request at https://github.com/sanitizers/patchback-github-app/issues/new explaining how you'd like it to work and maybe I'll implement it when I have time :)

**Comment by shanemcd** [comment]
We probably should enable auto-deletion.

**Comment by Akasurde** [comment]
We decided not to proceed with patchback. Closing this as `won't fix`.

**Comment by webknjaz** [comment]
> Otherwise, all users of ansible-runner have to clone them now.

FYI GitHub now has a checkbox on forking saying "only copy the default branch".
