### ISSUE TITLE
Support for cgroupsv2

### ISSUE THREAD

**Issue by Sakirnth-Z** [ansible/ansible-runner#810]
Hi,

At the moment ansible-runner only works with cgroupsv1. cgroupsv1 filesystem is not mounted by default anymore in the new version of Debian (Debian Bullseye). Therefore cgroupsv2 should be supported now in ansible-runner.

Could you please adapt the code that it will work with cgroupsv2.

Here is a link to cgroupsv2 documentation: 
https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html

And this is the original bug report on Debian, here you can find more informations:  
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=993371

Thank you very much and cheeers
Saki

**Comment by chrismeyersfsu** [comment]
The code in runner that interfaces directly in cgroups was used only in the Resource Profiling feature in AWX. The dependent Resource Profiling feature has been removed and now we just need to remove the corresponding code from runner.

Are you using the Resource Profiling feature?

**Comment by Sakirnth-Z** [comment]
Thanks for your answer. Therefore it's dead code now?

Personally I do not use this feature. But it was reported in debian bugs, so I guess some people are using it.

Cheers,
Saki

**Comment by samdoran** [comment]
Further discussion is needed to determine if we want to keep the resource profiling feature or remove it entirely.

**Comment by Akasurde** [comment]
resolved_by_pr #997

**Comment by Sakirnth-Z** [comment]
Thank you for your work. In Debian I patched the version 2.1.3 with this patch.

Greetings
Sakirnth
