### ISSUE TITLE
Change ansible_runner version

### ISSUE THREAD

**Issue by FloLaco** [ansible/ansible-runner#824]
Hi,

I would like to build an `ansible-runner` wheel by myself because I've added some fix and feature and PR isn't approved at this time.
So I make a `make dist` command. But it build the wheel with a strange version number : `ansible_runner-2.0.0.0a4.dev135-py3-none-any.whl`. Where can I change this version number ? I didn't find anywhere in the code the source of this version.

Regards

**Comment by Shrews** [comment]
We use [pbr](https://docs.openstack.org/pbr/latest/) which calculates version info from git tags. If you are attempting to package from the `devel` branch, you will get odd looking versions. You can read more about that [here](https://docs.openstack.org/pbr/latest/user/packagers.html). Based on that documentation, you might be able to set the `PBR_VERSION` environment variable manually to achieve what you want, but you might want to just try packaging an official stable release branch instead.

**Comment by samdoran** [comment]
Closing per above.
