### ISSUE TITLE
Issue with ansible_runner interface and inventory file

### ISSUE THREAD

**Issue by FloLaco** [ansible/ansible-runner#827]
Hi,
I discovered a bug which depend of my project folder hierarchy.
I'm using the `ansible_runner` interface on a basic python script. Depending on where is my python script, ansible_runner can't find the inventory file.

### Working example : 
```
.
├── ansible.cfg
├── env
│   └── passwords
├── get_facts.yaml
├── main.py
└── ssmyhostsh
```

`main.py` extract : 
```
r = ansible_runner.run(private_data_dir='/home/florian/ansible-runner-test', playbook='get_facts.yaml', inventory="myhosts", passwords=passwords)
```

Execution : 
```
(ansible-runner-git) florian@dsrauto-dev1:~/ansible-runner-test2$ python main.py
SSH password:

PLAY [Get facts] ***************************************************************

TASK [Get facts] ***************************************************************
ok: [testbed_BB1]

TASK [Show version] ************************************************************
ok: [testbed_BB1] => {
    "msg": "12.2(55)SE9"
}

PLAY RECAP *********************************************************************
testbed_BB1                : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Non working example : 
```
.
├── ansible
│   ├── ansible.cfg
│   ├── get_facts.yaml
│   ├── myhosts
│   └── set_passwords.yml
└── main.py
```
As you can see, my python script is not in the same folder as my `private_data_dir`

`main.py` extract  : 
```
r = ansible_runner.run(private_data_dir='/home/florian/ansible-runner-test2/ansible', playbook='get_facts.yaml', inventory="myhosts", passwords=passwords)

```

Failed execution : 
```
(ansible-runner-git) florian@dsrauto-dev1:~/ansible-runner-test2$ python main.py
SSH password:

PLAY [Get facts] ***************************************************************

TASK [Get facts] ***************************************************************
fatal: [myhosts]: FAILED! => {"changed": false, "msg": "Connection type ssh is not valid for this module"}

PLAY RECAP *********************************************************************
myhosts                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### The reason : 
At line https://github.com/ansible/ansible-runner/blob/2323686deac3a0e6691b7bd63c156f8422529746/ansible_runner/utils/__init__.py#L213 , it checks if the `inventory` file exist, but it checks relatively from where my python script is, and not relatively with the `private_data_dir`. And the documentation say "Path to the inventory file in the `private_data_dir`". So I'm using it correctly.

It added some `print()` to check the value of `kwargs['inventory']` before and after, and here is the value : 
Before : `myhosts`
After :  `/home/florian/ansible-runner-test2/ansible/inventory/hosts`

### How to fix : 
Change this line : 
`            if not os.path.exists(obj):`
with this line : 
`            if not os.path.exists(os.path.join(private_data_dir, obj)):`

I'll submit a PR

**Comment by FloLaco** [comment]
My change works like a charm, only if my playbook is not on the `project/` folder.
If my playbook is stored on `project/` folder, it does not work (even on the original code). I suppose this is because the base directory is set in `project/` : 
`[WARNING]: Unable to parse /home/florian/ansible-runner-test2/ansible/project/myhosts as an inventory source`

Is it normal ? 
If I check the doc : 

>     :param inventory: Overrides the inventory directory/file (supplied at ``private_data_dir/inventory``) with
>         a specific host or list of hosts. This can take the form of:
> 
>             - Path to the inventory file in the ``private_data_dir``


The docs does not talk about relative or absolute path. Each `tests` is testing absolute path ...
According to the quote above, I understand that it can be relative. 
Can you confirm me ?

**Comment by samdoran** [comment]
In this case, passing an absolute path to inventory is the recommended approach. From [the docs](https://ansible-runner.readthedocs.io/en/stable/intro/#inventory):

> Giving an absolute path for the inventory location is best practice, because relative paths are interpreted relative to the current working directory which defaults to the project directory.
