### ISSUE TITLE
sending the playbook contents as a dictionary to the runner python module not working. 

### ISSUE THREAD

**Issue by m4ri0g** [ansible/ansible-runner#852]
Hello As requested in the libera chat i open this issue here. 

https://github.com/ansible/ansible-runner/blob/devel/ansible_runner/interface.py#L138-L139
according to this this parameter to the enty poing will take a list as a data structure or even just a string of content. but it seems it only accepts the 'string' of a filename. 

I try this: 

```
import ansible_runner

inv = {'all': {'hosts': 'vms' }}

play_src={
{
  "gather_facts": false,
  "tasks": [
    {
      "debug": {
        "msg": "hello"
      },
      "name": "debug output"
    }
  ],
  "hosts": "all",
  "become": true
}

r = ansible_runner.run(private_data_dir='.', inventory=inv, playbook=play_src)

```
this gives an error: 

  File "./test_runner.py", line 45, in <module>
    r = ansible_runner.run(private_data_dir='.', inventory=inv, playbook=play_src)
  File "/usr/home/ansible/venv/lib/python2.7/site-packages/ansible_runner/interface.py", line 178, in run
    r.run()
  File "/usr/home/ansible/venv/lib/python2.7/site-packages/ansible_runner/runner.py", line 112, in run
    command = [a.decode('utf-8') for a in self.config.command]
AttributeError: 'dict' object has no attribute 'decode'

it appears that runner is expecting a string (decode attribute is only available for strings. so I  hardcoded the yaml file as a string. 

```
play= """
---
- hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: debug output
      debug:
        msg: 'hello'
"""

print play.decode('utf-8')


r = ansible_runner.run(private_data_dir='.', inventory=inv, playbook=play)
```
this gives the error: 

```
ERROR! the playbook:
---
- hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: debug output
      debug:
        msg: 'hello'
 could not be found
```

the expected behavior is that the python dictionary is used as a playbook source.

**Comment by matburt** [comment]
This worked at one point... I reckon recent refactorings broke it.

**Comment by matburt** [comment]
It was originally implemented here: https://github.com/ansible/ansible-runner/pull/21

**Comment by m4ri0g** [comment]
I ran on python3 as well and latest ansible-runner 2.0.2 same results. different error: 

```
Traceback (most recent call last):
  File "./test_runner.py", line 51, in <module>
    r = ansible_runner.run(private_data_dir='.', inventory=inv, playbook=play_src)
  File "/usr/home/secops_ansible/ansible/lib/python3.6/site-packages/ansible_runner/interface.py", line 254, in run
    r = init_runner(**kwargs)
  File "/usr/home/secops_ansible/ansible/lib/python3.6/site-packages/ansible_runner/interface.py", line 119, in init_runner
    rc.prepare()
  File "/usr/home/secops_ansible/ansible/lib/python3.6/site-packages/ansible_runner/config/runner.py", line 161, in prepare
    debug(f"command: {' '.join(self.command)}")
TypeError: sequence item 3: expected str instance, dict found
```
is there a way to roll back the changes so that it does work again?

**Comment by matburt** [comment]
You can try going back to the previously released version of Runner in the 1.x release.

**Comment by m4ri0g** [comment]
the error i posted yesterday was actually on version 1.4.7 on which version is it known to work?

**Comment by matburt** [comment]
good question! Let me know when you find it!

Or.... you can fix the bug for us 😄

**Comment by m4ri0g** [comment]
it does not even work in version 1.0.1 which is the earliest version on pip. 
will see if i can find it in the code.. not sure where to look though!

**Comment by samdoran** [comment]
I see two issues being reported here:

1. Passing the playbook as a string rather than a string that is path to a playbook file
2. Passing the playbook as a dict

In case 1, runner is looking for a playbook named `\n---\n- hosts: all\n  gather_facts: no\n  become: yes\n\n  tasks:\n    - name: debug output\n      debug:\n        msg: 'hello'\n`. I would expect that to fail and this has never worked, even in the original commit. I don't think that's something we should support, though we could probably improve the error message:

```
[
    'ansible-playbook', 
    '-i', '/Users/sdoran/Source/ansible-runner/issues/852/play_src_str/inventory', 
    "\n---\n- hosts: all\n  gather_facts: no\n  become: yes\n\n  tasks:\n    - name: debug output\n      debug:\n        msg: 'hello'\n"
]
```

Case 2 is a bug introduced in b21adbd65e995ed2358b463cdd306e088cb3dd9b that should be fixed. It's quite handy to pass in a playbook as a real dictionary.

**Comment by m4ri0g** [comment]
> I see two issues being reported here:
> 
> 1. Passing the playbook as a string rather than a string that is path to a playbook file
> 2. Passing the playbook as a dict
> 
> In case 1, runner is looking for a playbook named `\n---\n- hosts: all\n gather_facts: no\n become: yes\n\n tasks:\n - name: debug output\n debug:\n msg: 'hello'\n`. I would expect that to fail and this has never worked, even in the original commit. I don't think that's something we should support, though we could probably improve the error message:
> 
> ```
> [
>     'ansible-playbook', 
>     '-i', '/Users/sdoran/Source/ansible-runner/issues/852/play_src_str/inventory', 
>     "\n---\n- hosts: all\n  gather_facts: no\n  become: yes\n\n  tasks:\n    - name: debug output\n      debug:\n        msg: 'hello'\n"
> ]
> ```
> 
> Case 2 is a bug introduced in [b21adbd](https://github.com/ansible/ansible-runner/commit/b21adbd65e995ed2358b463cdd306e088cb3dd9b) that should be fixed. It's quite handy to pass in a playbook as a real dictionary.

I do not expect case 1 to work. it is just that the runner is expecting a string according to the docstring.: 

> The playbook (either supplied here as a list or string...

it is not very clear what kind of list or string is waiting for. so I tried my luck by encoding the yaml as a string. knowing it would not work.. but it is one of the things i have tried.

**Comment by samdoran** [comment]
Looking at `isplaybook()` a bit closer, it is expecting a list of plays. That was an intentional change made in b21adbd. Since a playbook is technically a list of plays, I can see how this would be valid.

Seems like we could either massage a dict into a list, or have better error reporting.

This will restore the previous behavior:

```patch
diff --git ansible_runner/utils/__init__.py ansible_runner/utils/__init__.py
index 49cee182be..efeb23d573 100644
--- ansible_runner/utils/__init__.py
+++ ansible_runner/utils/__init__.py
@@ -69,7 +69,7 @@ def isplaybook(obj):
     Returns:
         boolean: True if the object is a list and False if it is not
     '''
-    return isinstance(obj, Iterable) and (not isinstance(obj, string_types) and not isinstance(obj, Mapping))
+    return isinstance(obj, Iterable) and not isinstance(obj, string_types)
 
 
 def isinventory(obj):
```

**Comment by samdoran** [comment]
I definitely agree the doc string is inaccurate and should be updated since a string was never valid.

**Comment by m4ri0g** [comment]
i have tested it. it only works on python3.8 
does it break backwards compatibility? it is supposed to work from python 2.7..

**Comment by samdoran** [comment]
I didn't _have_ to do it that way, but I don't believe this project supports Python < 3.8. We only test on Python >=3.8. I'll yield to @matburt or @shanemcd on whether we should be concerned with Python 2 compatibility.

**Comment by m4ri0g** [comment]
> I didn't _have_ to do it that way, but I don't believe this project supports Python < 3.8. We only test on Python >=3.8. I'll yield to @matburt or @shanemcd on whether we should be concerned with Python 2 compatibility.

https://ansible-runner.readthedocs.io/en/stable/install.html#using-pip
it states python 2.7+, 3.6+ are supported. 
i believe not everyone is using the latest version of python 3. and of course that python 2 can be dropped. but it has to be clearly   stated. the := operator is only valid from python3.8+

**Comment by samdoran** [comment]
Seems like that documentation needs to be updated as well.

**Comment by matburt** [comment]
2.x is out, I'm okay with requiring 3.8+ since that's the direction ansible itself is heading.

**Comment by m4ri0g** [comment]
I am not sure that ruling out everyone using python3. is a good idea. 
the walrus operator is causing the pr validation to fail. ansible/zuul is perhaps not python3.8 

the syntax error could be fixed doing this: 

```
diff --git a/ansible_runner/utils/__init__.py b/ansible_runner/utils/__init__.py
index f516d1e..6cd78c4 100644
--- a/ansible_runner/utils/__init__.py
+++ b/ansible_runner/utils/__init__.py
@@ -201,7 +201,8 @@ def dump_artifacts(kwargs):

         kwargs['envvars']['ANSIBLE_ROLES_PATH'] = roles_path

-    if playbook := kwargs.get('playbook'):
+    playbook = kwargs.get('playbook')
+    if playbook:
         # Ensure the play is a list of dictionaries
         if isinstance(playbook, MutableMapping):
             playbook = [playbook]
```

**Comment by samdoran** [comment]
It looks like the linter test is running with Python 3.6 in CI. We need to fix that.
