### ISSUE TITLE
fatal or failed error_message are not displayed in stdout

### ISSUE THREAD

**Issue by shaofanhan** [ansible/ansible-runner#857]
ansible-runner stdout donot display fatal or failed error_message, but it is displayed when using ansible command.

- ansible-runner stdout below
![image](https://user-images.githubusercontent.com/16680069/135395776-37bde20e-676a-4c6f-b3f2-79653215f4bf.png)

- ansible command output below
![image](https://user-images.githubusercontent.com/16680069/135395823-2fdb5fef-4cec-4bd5-869e-6171d968fe54.png)

**Comment by samdoran** [comment]
Could you provide a simple playbook that reproduces this issue?

**Comment by shaofanhan** [comment]
> Could you provide a simple playbook that reproduces this issue?

It will always happen in some environment, no matter what playbooks are.

I look into ansible-runner and found the related code below. The 'v2_runner_on_failed' method mentioned in picture. 

    def v2_runner_on_failed(self, result, ignore_errors=False):
        # FIXME: Add verbosity for exception/results output.
        host_start, end_time, duration = self._get_result_timing_data(result)
        event_data = dict(
            host=result._host.get_name(),
            remote_addr=result._host.address,
            res=result._result,
            task=result._task,
            start=host_start,
            end=end_time,
            duration=duration,
            ignore_errors=ignore_errors,
            event_loop=self._get_event_loop(result._task),
        )
        with self.capture_event_data('runner_on_failed', **event_data):
            super(BaseCallbackModule, self).v2_runner_on_failed(result, ignore_errors)

**Comment by shaofanhan** [comment]
> Could you provide a simple playbook that reproduces this issue?

the cause is ansible and ansible-base version too high.

**Comment by shaofanhan** [comment]
the cause is ansible and ansible-base version too high.
