### ISSUE TITLE
License incompatibility

### ISSUE THREAD

**Issue by erickb-n** [ansible/ansible-runner#860]
It appears that there is some license incompatibility in this project.  The stated license is Apache but there are several files (below) that are GPLv3 licensed.  Would it be possible to make these files dual licensed or add exceptions to them?

- ansible_runner/display_callback/module.py
- ansible_runner/display_callback/events.py
- ansible_runner/display_callback/display.py
- ansible_runner/callbacks/minimal.py
- ansible_runner/callbacks/awx_display.py
- ansible_runner/display_callback/minimal.py
- ansible_runner/display_callback/__init__.py

Whether you agree to do so or not, thanks for ansible_runner

**Comment by shanemcd** [comment]
I think this is because these files are only imported by Ansible, which is GPLv3.

**Comment by erickb-n** [comment]
@shanemcd I am trying to verify that in the ansible repo but seem to be getting lost in the weeds, any pointers as to where I should look?  Thanks.

**Comment by shanemcd** [comment]
@erickb-n Which part are you trying to verify? 

For the Ansible license: https://github.com/ansible/ansible/blob/f4d4391a1f5d4d2b4159d9976216c5861023be2c/setup.py#L333

If you are trying to figure out where / how Ansible imports those files, you will not find that in the Ansible repo. Runner tells Ansible which callbacks to use here: https://github.com/ansible/ansible-runner/blob/b9a4a79fa489d823b991c453c23877bc500f5a1d/ansible_runner/config/_base.py#L267-L269

**Comment by erickb-n** [comment]
@shanemcd Yes, I am trying to figure out where/how those files are imported.
