### ISSUE TITLE
Update container docs to point to new location on quay.

### ISSUE THREAD

**Issue by bilaloslo92** [ansible/ansible-runner#863]
The docker image for ansible runner was last pushed to Docker hub 6 months ago: https://hub.docker.com/r/ansible/ansible-runner

Is this something that has stopped working?

**Comment by shanemcd** [comment]
Sorry about that. I just updated that repo's readme to point to the new image location: http://quay.io/ansible/ansible-runner. Repurposing this issue to track updating the link in https://github.com/ansible/ansible-runner/blob/devel/docs/container.rst

**Comment by bilaloslo92** [comment]
> Sorry about that. I just updated that repo's readme to point to the new image location: http://quay.io/ansible/ansible-runner. Repurposing this issue to track updating the link in [https://github.com/ansible/ansible-runner/blob/devel/docs/container.rst](https://github.com/ansible/ansible-runner/blob/devel/docs/container.rst?rgh-link-date=2021-10-11T21%3A04%3A51Z)

Thanks! In addition, I hope the tag can be better numbered rather than having latest. Because then you actually never know which version of the image you are running.

**Comment by samdoran** [comment]
I agree it would be great to have container tags that match the runner version in the container. We should track that in a separate issue, though.
