### ISSUE TITLE
Silent fail without <private_data_dir>/project/ directory

### ISSUE THREAD

**Issue by Ladas** [ansible/ansible-runner#88]
I need to have at least blank <private_data_dir>/project/ dir, otherwise the ```ansible-runner run ...``` doesn't finish. I couldn't find any failure, it just prints warning about <private_data_dir>/env/... files and then ends. With the empty ```project``` dir, it works correctly.

**Comment by Ladas** [comment]
@matburt ping. This doesn't block me, it just looks like interesting bug to me. :-) (it took me a while to find the silent failure)

**Comment by privateip** [comment]
@Ladas are you running playbooks or roles?  Reason i ask is the code paths are different for the moment

**Comment by Ladas** [comment]
@privateip I am using --playbook

**Comment by matburt** [comment]
We definitely need to unify these code paths... the empty project dir causing problems is definitely not good.

**Comment by privateip** [comment]
yes agreed.  Im working on an update to do that right now and should be ready next week some time.

**Comment by matburt** [comment]
I've fixed t his independently of unifying the code paths here: https://github.com/ansible/ansible-runner/commit/dbe1c2363fd69400751a4da7cd2ec20704d8fc4c

Will cover code path reunification on #48
