### ISSUE TITLE
how to set host_vars with ansible-runner

### ISSUE THREAD

**Issue by Drewolf** [ansible/ansible-runner#881]
I have a playbook that uses variables in the host_vars directory。like this:

```
cat /etc/ansible/host_vars/foosball

ntp_server: acme.example.org
database_server: storage.example.org
```

so, how to set host_vars with ansible-runner ?

**Comment by samdoran** [comment]
Inventory variables for runner are no different than [defining inventory variables in Ansible Core](https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#splitting-out-vars). The `host_vars` directory needs to be adjacent to the inventory file.

By default, Runner looks in `<private_data_dir>/inventory` for inventory. If it is somewhere else, specify the location:

`ansible-runner run --inventory /etc/ansible/hosts ...`

To discuss this further, please reach out on IRC #ansible-runner on irc.libera.chat.
