### ISSUE TITLE
Add a way to check if an element of a collection is valid

### ISSUE THREAD

**Issue by greg-hellings** [ansible/ansible-runner#925]
There seems to be no reasonable way, at the moment, to query Ansible/Ansible Runner to check if a collection or an element in it is present. For instance, if I attempt to run a playbook named `foo.yml`, I can check for the existence of that file. However, if I want to run playbook `ns.collection.foo` from collection `ns.collection`, there is no good way to check with Ansible that this playbook actually exists.

Please expose a method of detecting that these values are valid. It could also be good for other items in a collection as well.

**Comment by samdoran** [comment]
Collection validation is outside the scope of Runner. Failing nicely if the playbook file is not found is what Runner should do.

To discuss this further, please reach out on IRC in #ansible-runner on irc.libera.chat.
