### ISSUE TITLE
how to use in a python file with a JSON string for hosts

### ISSUE THREAD

**Issue by simonjcarr** [ansible/ansible-runner#948]
I am trying to use ansible-runner in a python script. My hosts list is dynamically generated from a database. I want to pass this hosts list to ansible-runner directly as a string (not as a reference to a file)

Here is my runner command

```
import ansible_runner

def new_server(inventory):
    print(inventory)
    return ansible_runner.run(inventory=inventory, private_data_dir="./ansible_lib", playbook="ping.yml")
```

This is what my inventory looks like

```
{"_meta": {"hostvars": {}}, "17041958": {"hosts": ["157.*.*.251"]}}
```

Here is my private_data_dir structure

```
= ansbile_lib
== env
=== ssh_key
== inventory
=== hosts //This file is empty, but without it, ansible-runner refuses to run
== project
=== ping.yml
```

The output from ansible-runner is

```
[WARNING]: Unable to parse /Users/soxprox/Development/soxprox/code/soxprox_code
_server_automation_python/ansible_lib/project/ansible_lib/inventory/hosts as an
inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'

PLAY [ping a host] *************************************************************
skipping: no hosts matched

PLAY RECAP *********************************************************************
```

As you can see, even though I am passing in a json string to the inventory parameter, anisble-runner is still trying to read hosts from the hosts file. I have tested this json format with ansible directly (by pointing ansible to a python script) and it works just fine.

**EDIT** I have just noticed that there is content in my inventory/hosts file. It is being written there by ansible-runner when it receives the json string. However...

I am still getting the error no hosts matched
If I try to run my script a second time, ansible-runner gives me a permission denied error on the inventory/hosts file as it still has a lock on the file. How do I get get ansible-runner to drop that lock? It might be that this is due to issue 1 no hosts matched, but that is a normal operational status and I would have thought ansible-runner could handle that and shut down cleanly.

**Comment by Akasurde** [comment]
@simonjcarr You need to pass the inventory JSON as - 

```
{"all": {"hosts": {"host1": null, "host2": null}}, "db": {"hosts": {"hosts3": null}}}
```

So your script might look like this - 

```python
...
inventory_json_str = '{"all": {"hosts": {"vm1": null}}}'
r = ansible_runner.run(
    host_pattern='all',
    module='ping',
    inventory=inventory_json_str,
)
...
```
