### ISSUE TITLE
Return code/exit status of command line doesn't fit artifacts/<ident>/rc

### ISSUE THREAD

**Issue by Ladas** [ansible/ansible-runner#95]
Running ```ansible-runner``` command line seems to be always giving return code 0. Even if there is a failure and I see the value 1 in artifacts/<ident>/rc

**Comment by Ladas** [comment]
@matburt doesn't block us, for now I just read the rc from artifacts/<ident>/rc

**Comment by matburt** [comment]
This is a dupe of https://github.com/ansible/ansible-runner/issues/48

It's something I'm looking at right now
