### ISSUE TITLE
Execution of ansible-runner hangs with no output either to stdout or stderr.

### ISSUE THREAD

**Issue by iv1111** [ansible/ansible-runner#993]
Hello,

I've been using a standalone `ansible-runner` application in the context of [ManageIQ](https://github.com/ManageIQ/manageiq). Recently, I've been having a problem with the usage of `ssh_key` (as described here int the [documentation](https://ansible-runner.readthedocs.io/en/stable/intro/)).

After placing my unencrypted private SSH key into that file and running my playbook with the `ansible-runner` I've noticed that the runner hangs indefinitely and I can see no output at all (even in debug mode) under `/tmp/ansible-runnerX/artifacts/result/{stdout,stderr}` directory. I have tried to reproduce the steps that the runner does by looking at `/tmp/ansible-runnerX/artifacts/result/command`. 

It seems that this is the step where it hangs: `ssh-add /tmp/ansible-runnerX/artifacts/result/ssh_key_data`. It looks like the `ssh_key_data` is a named pipe that you can't read anything from. I've tried opening it with other applications like ```vim``` with the same result (it hangs).

A brief search showed me some similar problems observed in AWX:

- https://github.com/ansible/awx/issues/11453
- https://github.com/ansible/awx/issues/11613
- https://github.com/ansible/awx/issues/11051
- https://github.com/ansible/awx/issues/10489

I don't understand why this problem occurs now as I've tested both encrypted and unencrypted private keys with `ansible-runner` in the past and it worked well.

**Context:**
- GNU/Linux RHEL 8.4
- ansible-runner: 2.1.1
- Python 3.9.7

**Comment by TheOnion7** [comment]
As I mentioned in [ansible/awx/#11613](https://github.com/ansible/awx/issues/11613) , in my case , the culprit was falcon-sensor. Hope it will help you out.

**Comment by iv1111** [comment]
@TheOnion7 You're absolutely right. I confirm that the problem is the _falcon-sensor_. It seems to interfere with whatever is supposed to populate the _ssh_key_data_ pipe. Thanks for your help!

Question to the `ansible-runner` team. Do you plan a workaround for this issue? It unfortunately makes using private key access with the runner unusable (if ```falcon-sensor``` is enabled).

**Comment by matburt** [comment]
I'm open to suggestions. The use of named pipes here is to specifically prevent sensitive data from landing on the filesystem. It seems like the real problem is that falcon-sensor breaks normal usage of named pipes? The only remediation would be to *not* use named pipes which has its own set of caveats and problems.

**Comment by iv1111** [comment]
Yeah, if we look at it from another angle then the ```falcon-sensor``` blocks the execution of a non-malicious application, which it shouldn't.

However, once this occurs the ```ansible-runner``` just sits there writing neither to ```stdin``` nor to ```stderr```. I think it would be more dev/user friendly if the ```stderr``` would at least indicate that it's not possible to read from the ```ssh_key_data``` or that it timed out doing so. 

Also, adding the corresp. information about the ```falcon-sensor``` as a side note [here](https://ansible-runner.readthedocs.io/en/stable/intro/) under this section would be beneficial too.

![image](https://user-images.githubusercontent.com/69972357/153828760-173ce7b0-02f6-47a3-926b-f66bf26b3671.png)

**Comment by matburt** [comment]
Knowing we are blocked on an a pipe that will never return data seems like we would need to solve the halting problem first. I'm open for a PR that adds information to the docs, though.

**Comment by iv1111** [comment]
> Knowing we are blocked on an a pipe that will never return data seems like we would need to solve the halting problem first.

Determining that an algorithm terminates is certainly undecidable but what I meant is perhaps a timeout can be added that'd trigger if no data comes from the pipe for a certain amount of time and would terminate the execution writing a message to ``stderr``.

If that's not possible/worth the effort, then maybe at least in a ``--debug`` mode one could be more verbose and write a message to ``stdout`` before starting to wait for the pipe, e.g. "initiating the reading from ssh_key_data named pipe" (or similar). This way it would give an indication to the user what the last operation was before it got stuck.
